### ISSUE TITLE
rds-deployment/rds-update-certificate/scripts/Script.ps1 always installs PS AzureRM module

### ISSUE THREAD

**Issue by jagilber** [Azure/RDS-Templates#12]
when deploying template, azurerm module always installs.
changing from:
``
	#  install AzureRM module
	#
	if (-not (get-module AzureRM))
	{
		log "installing AzureRm powershell module..."
		install-module AzureRM -force
	}
``
changing to:
``
	#  install AzureRM module
	#
	if (-not (get-module AzureRM*))
	{
		log "installing AzureRm powershell module..."
		install-module AzureRM -force
	}
``

**Comment by afilenkov** [comment]
Merged into develop
