### ISSUE TITLE
rds-deployment/rds-update-certificate/scripts/Script.ps1 removing external dependency

### ISSUE THREAD

**Issue by jagilber** [Azure/RDS-Templates#15]
rds-deployment/rds-update-certificate/scripts/Script.ps1 removing external dependency on gallery script 
[set-rdpublishedname.ps1](https://gallery.technet.microsoft.com/Change-published-FQDN-for-2a029b80)

reasons:
- external dependency url link could be inadvertently changed due to gallery design
- logic in gallery script is small (determines if HA and runs single command)
- no commit history in gallery
- can easily be incorporated to potentially improve resiliency

submitting PR after final testing

**Comment by afilenkov** [comment]
Merged into develop
