### ISSUE TITLE
rds-deployment/rds-update-certificate/scripts/Script.ps1 removing external dependency impersonate

### ISSUE THREAD

**Issue by jagilber** [Azure/RDS-Templates#16]
rds-deployment/rds-update-certificate/scripts/Script.ps1 removing external dependency on gallery script 
[new-impersonateuser.ps1](https://gallery.technet.microsoft.com/Impersonate-a-User-9bfeff82)

reasons:
- external dependency url link could be inadvertently changed due to gallery design
- logic in gallery script is small (calls win32 advapi32 LogonUser)
- no commit history in gallery
- can easily be incorporated to potentially improve resiliency

submitting PR after final testing

**Comment by afilenkov** [comment]
Merged into develop
