### ISSUE TITLE
Optional OU Path issue with WVD Provision a Host Pool

### ISSUE THREAD

**Issue by miked1313** [Azure/RDS-Templates#164]
I am running into an issue with Windows Virtual Desktop - Provision a host pool in Azure Resource Manager Marketplace

When you set Specify domain to join to yes the OU path I am entering is failing validation and I cannot continue.  This same exact OU path worked about a month ago.

Domain to Join:  `adbyo.acexamplecompany.sandbox.ac`

OU Path:  `OU=Win10Multi,OU=WVD,OU=Servers,OU=Endpoints,OU=AC Example Company,DC=adbyo,DC=acexamplecompany,DC=sandbox,DC=ac`

It looks like it is because spaces are not supported for OU names because this DN passes validation.
`OU=Win10Multi,OU=WVD,OU=Servers,OU=Endpoints,OU=ACExampleCompany,DC=adbyo,DC=acexamplecompany,DC=sandbox,DC=ac`

**Comment by ChristianMontoya** [comment]
@miked1313 : This has been made more flexible and doesn't break anymore.

Please let re-open if this is not the case.
