### ISSUE TITLE
rds-deployment-ha-broker/scripts/RdcbHaPostConfig.ps1 calling optional module Get-ADDomain

### ISSUE THREAD

**Issue by jagilber** [Azure/RDS-Templates#17]
rds-deployment-ha-broker/scripts/RdcbHaPostConfig.ps1 calling Get-ADDomain which is not installed by default on windows 2012.

`27 $domainNetbios = (Get-ADDomain -Current LocalComputer).NetBIOSName `

**Comment by mmarch** [comment]
we have no goal of supporting WS2012 RTM
the two supported server OS versions are WS2012R2 and WS2016

Get-ADDomain is available on WS2012R2 (Powershell 4.0), so IMO this fix is not required

**Comment by jagilber** [comment]
closing issue, ha-broker only for 2k16
