### ISSUE TITLE
 rds-update-certificate / Scripts / Script.ps1 issues with trusted cert (cant rdp)

### ISSUE THREAD

**Issue by jagilber** [Azure/RDS-Templates#18]
rds-update-certificate / Scripts / Script.ps1 issues with trusted cert.
not able to rdp due to gateway config in rdp file.
'gatewayhostname' not set to cert subject name in rdp file.

- testing self-signed
- trusted
- wildcard trusted

cert subject jagilber.com

### **bad rdp file:**
drivestoredirect:s:*
redirectdrives:i:1
session bpp:i:32
prompt for credentials on client:i:1
server port:i:3389
allow font smoothing:i:1
promptcredentialonce:i:1
videoplaybackmode:i:1
audiocapturemode:i:1
gatewayusagemethod:i:1
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
**full address:s:broker.eastus.cloudapp.azure.com**
**gatewayhostname:s:rdsdepha3.eastus.cloudapp.azure.com**
workspace id:s:broker.rdsdepha3.lab
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.Desktop_Collecti
use multimon:i:1
**alternate full address:s:broker.eastus.cloudapp.azure.com**

### **good rdp file: (manually modified)**
redirectclipboard:i:1
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:1
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:1
session bpp:i:32
prompt for credentials on client:i:1
server port:i:3389
allow font smoothing:i:1
promptcredentialonce:i:1
videoplaybackmode:i:1
audiocapturemode:i:1
gatewayusagemethod:i:1
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
**full address:s:broker.rdsdepha3.lab**
**gatewayhostname:s:gateway.jagilber.com**
workspace id:s:broker.rdsdepha3.lab
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.Desktop_Collecti
use multimon:i:1
**alternate full address:s:broker.rdsdepha3.lab**

testing fixes

**Comment by afilenkov** [comment]
Merged into develop
