### ISSUE TITLE
WVD - Autoscaling not working

### ISSUE THREAD

**Issue by Napstero** [Azure/RDS-Templates#186]
Hello,

I’ve tried to use the autoscaling for Windows Virtual Desktop script mentioned there :
https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script
I can see in the logs that the script is connecting to the pool and checking the number of host.
But the host doesn’t start in azure.
I’ve join you the log files :
[WVDTenantUsage.log](https://github.com/Azure/RDS-Templates/files/3377100/WVDTenantUsage.log)
[WVDTenantScale.log](https://github.com/Azure/RDS-Templates/files/3377101/WVDTenantScale.log)

Thanks for your help,

Kevin

**Comment by jagdishbagul01** [comment]
Hello,

I’ve configured the autoscaling for Windows Virtual Desktop as per instruction given there on :
https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script

In these instructions config.xml file is mentioned but in basicScale.ps1 it is mentioedn to use config.json

Could you please update the instruction and update how to add values in config.json

**Comment by de-re-ve** [comment]
Hello,

I had issues with the JSON being picked instead of the XML file as well. While checking the basicScale script, I realized that the JSON file is being incorporated and not the XML. I updated the JSON file with the necessary information and tried working with that. 

However, now I am encountering a PS error when running the script:
Set-ScriptVariable is not recognized as the name of a cmdlet. 

Apparently, I have another module missing from my PS (classic).

**Comment by TVDKoni** [comment]
Hi de-re-ve

There is a function in the script:
function SetScriptVariable ($Name,$Value) {
  Invoke-Expression ("`$Script:" + $Name + " = `"" + $Value + "`"")
}

Rename it to Set-ScriptVariable

**Comment by de-re-ve** [comment]
> Hi de-re-ve
> 
> There is a function in the script:
> function SetScriptVariable ($Name,$Value) {
> Invoke-Expression ("`$Script:" + $Name + " = `"" + $Value + "`"")
> }
> 
> Rename it to Set-ScriptVariable

Can't believe I missed that one. Thank you!

**Comment by TVDKoni** [comment]
Dear Kevin

Do you have configured the MaxSessionLimit on your hostpool?

**Comment by Napstero** [comment]
Hello TVDKoni,

I tried again now that WVD is in GA and still the same issue. Same log file... Nothing is happening.
I tried with the basicScale-MSI.ps1 script and the basicScale.ps1

Has someone managed to get it working ?

**Comment by TVDKoni** [comment]
Hi Napstero

Here my own modified version which works perfect in my environment.

Script: https://file.io/gN559E
Config: https://file.io/7f06qf

Make sure your VM size is listed in the config.

Regards
Konrad

**Comment by Napstero** [comment]
Hi Konrad,

Unfortunately your links are note working "file not found". Could you please upload them again.

Many thanks,

Kevin

**Comment by Napstero** [comment]
Hi Konrad,

Unfortunately it's still not working. I must miss something but i don't know what.
[ScaleHostPool-20191023110747.log](https://github.com/Azure/RDS-Templates/files/3762361/ScaleHostPool-20191023110747.log)

I'v joined you the log file.

Thanks,
Kevin

**Comment by TVDKoni** [comment]
Hi Kevin

Remove the KeyVaultClient part from the script. That's a special solution to get the credentials from the KeyVault. You need to get the login credentials somehow different. Just hardcode it for a first test.

Regards
Konrad

**Comment by csry07** [comment]
I am having issue as well. I have tried the BasicScale.ps1 and also the files from TVDKoni. The issue states the Resouce Group Name is null. Though in the json file I have defined the resource group name.

**Comment by csry07** [comment]
Error(Start-AzureRmVM): "Cannot validate argument on parameter 'ResourceGroupName'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again."

**Comment by csry07** [comment]
I also get this error with my stored service principal account. 

Add-AzureRmAccount : The provided account  does not have
access to subscription ID "". Please try logging in with
different credentials or a different subscription ID.

When I attempt to add the service principal name to the subscription I cant find it to add it.

**Comment by jit294** [comment]
Hi csry07,

Did you manage to get this resolved? I'm having the exact same issue and am completely stumped!

**Comment by viswanadham-k** [comment]
Hi All,

Can you please access the below link and configure the latest version of WVD Scaling tool it is recommended by Microsoft. This version have your issue fix.

https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script

Let us know if you are still facing issues.

Thanks,

**Comment by ChristianMontoya** [comment]
As @viswanadham-k mentioned, please try the new script that uses logic apps and is fully described here in the public documentation: [Set up scaling script](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script).

Closing this out. Please create a new issue if scenario reproduces.
