### ISSUE TITLE
"Mandatory parameter DefaultDesktopUsers is missing" when deploying WVD update

### ISSUE THREAD

**Issue by delradie** [Azure/RDS-Templates#191]
Hi All

I've come back on to working to use WVD for our RemoteApp deployments after having to move on to other priorities for a while. Back in may we had reliable updates running using the "Update existing WVD host pool" template (https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Update%20existing%20WVD%20host%20pool)

When deploying a WVD update (from custom image) now in the same way we are now getting a failed Resource Deployment due to missing parameter "DefaultDesktopUsers" when executing the DSC Extension stage

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{ "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'dscextension'. Error message: "The DSC Extension failed to execute: Mandatory parameter DefaultDesktopUsers is missing.More information about the failure can be found in the logs located under 'C:\WindowsAzure\Logs\Plugins\Microsoft.Powershell.DSC\2.77.0.0' on the VM."." } ] }}"}]}

Having compared with the new deployment template I can see that the new deployment does have this, bit not the update. I'm about to start looking at updating this myself but wanted to check if anyone else has had the same problem and may be looking at this already?

**Comment by delradie** [comment]
OK, so I've got past this error now, and have submitted a PR with the template update in. I'm now working on the next error received:

The DSC Extension received an incorrect input: A parameter cannot be found that matches parameter name 'SubscriptionId'.
Another common error is to specify parameters of type PSCredential without an explicit type. Please be sure to use a typed parameter in DSC Configuration, for example:
	configuration Example {param([PSCredential] $UserAccount) ... }

Will keep everyone posted. As my primary task requires me to update our WVD pool reliably I need this to work.

Cheers all

Mark

**Comment by ChristianMontoya** [comment]
@delradie : apologies for not responding sooner. We have made this field optional throughout the solution, so it should be resolved now.

Please re-open if that's not the case.
