### ISSUE TITLE
Using template to deploy leaves password unencrypted

### ISSUE THREAD

**Issue by evgaff** [Azure/RDS-Templates#192]
In the automation account, the password is unencrypted as a variable.  It appears this functionality is part of the runbook and requires editing outside this repo.  This fails AzSK controls but is also easily fixed.

`New-AzAutomationVariable -AutomationAccountName <automation_account_name> -Name 'password' -Encrypted $true -Value <password> -ResourceGroupName <RG>`

**Comment by ChristianMontoya** [comment]
@evgaff : Yes, we made this fix in a PR so it is now being treated as a credential object.

Please re-open if you experience different behavior.
