### ISSUE TITLE
WVD Manangement Site

### ISSUE THREAD

**Issue by QuiggUK** [Azure/RDS-Templates#196]
When I load the site and login with my credentials I get this 
"Server App" is not consented, So Please consent Server App.

I have made sure I have done consented the enterprise application with my AAD ID and give my user the roles Owner and Tenant Creator

**Comment by f15falcon** [comment]
Your creds also have to be an owner on the HostPool side so your app can talk to the RDS tenant and get your infrastructure information.
New-RdsRoleAssignment -RoleDefinitionName 'RDS Owner' -TenantName <TenantName> -SignInName <yourUPN>

**Comment by QuiggUK** [comment]
Hello

This is the error I get when I try your resolution

PS C:\WINDOWS\system32> New-RdsRoleAssignment -RoleDefinitionName 'RDS Owner' -TenantName ****.onmicrosoft.com -SignInName ryan@****.com
New-RdsRoleAssignment : User is not authorized to query the management service.
ActivityId: 95e82056-7a5b-400f-810b-96ba5fb8d8b4
Powershell commands to diagnose the failure:
Get-RdsDiagnosticActivities -ActivityId 95e82056-7a5b-400f-810b-96ba5fb8d8b4
At line:1 char:1
+ New-RdsRoleAssignment -RoleDefinitionName 'RDS Owner' -TenantName ska ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (Microsoft.RDInf...sRoleAssignment:NewRdsRoleAssignment) [New-RdsRoleAssignment], RdsPowerShellException
    + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.RDInfra.RDPowershell.Authorization.NewRdsRoleAssignment

Thanks
Ryan

**Comment by TVDKoni** [comment]
Dear Ryan

TenantName is the WVD Tenant not the Azure Tenant.

**Comment by sabirmohamed** [comment]
> Dear Ryan
> 
> TenantName is the WVD Tenant not the Azure Tenant.

***Agree with TVDKoni

New-RdsRoleAssignment -RoleDefinitionName 'RDS Owner' -TenantName WVDTenant -SignInName sabir.mohamed.admin@******.onmicrosoft.com

**Comment by ChristianMontoya** [comment]
@QuiggUK : Are you still facing this issue? Or can we close?

**Comment by ChristianMontoya** [comment]
Closing this out now. Please re-open if necessary.
