### ISSUE TITLE
WVD Management GUI - Validation error when adding users to App Groups.

### ISSUE THREAD

**Issue by andersidahl** [Azure/RDS-Templates#211]
Windows Virtual Desktop Management Web does not allow assigning users to App Groups! ![Screenshot_83](https://user-images.githubusercontent.com/10434858/63001415-e096b380-be73-11e9-8a3c-715c528a117b.png)
![Screenshot_84](https://user-images.githubusercontent.com/10434858/63001423-e391a400-be73-11e9-81b5-b4eee202328e.png)
More than one special character in the first part of the UPN causes validation error.

**Comment by viswanadham-k** [comment]
Hi Andersidahl,
Can you please deploy with latest build of Management UX tool from below location
https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/wvd-management-ux/deploy
Let me know if you are still facing issues.
