### ISSUE TITLE
Deployment of Management fails. 3-wvd-management-ux

### ISSUE THREAD

**Issue by bigpom** [Azure/RDS-Templates#213]
Azure user has contributor/User Access Administrator on the subscription. 
MFA is not enabled on the account. 
App Services are created but no contents in the wwwroot folder. 
![image](https://user-images.githubusercontent.com/24660585/63281475-cb0df900-c27a-11e9-96ce-553fa3672b53.png)

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    }
  ]
}

Thank you in advance

**Comment by viswanadhamkudapu** [comment]
Azure login it's not happen through PowerShell Script automation with your user credentials. Can you please execute below PowerShell Script in your local machine with your user credentials then you know about failure.
Before executing PowerShell script ensure your local machine is installed AzureRm, AzureAD Modules if not please read and find the description of the PowerShell Script.

<#
.Description 
    A Sample PowerShell script to check the azure authentication with PowerShell automation.

Run this PowerShell Script in Administrator mode.
This script depends on 2 powershell modules: AzureRM and AzureAD to get them execute 2 following commands.
Use "-AllowClobber" parameter if you have more than one version of PS modules installed
PS C:\>Install-Module AzureRM  -AllowClobber
PS C:\>Install-Module AzureAD  -AllowClobber

.PARAMETER TenantAdminCredentials
 Required
 Provide credentials which you are provided to ManagementUX template Deployment.

.PARAMETER SubscriptionID
 Required
 Provide SubscriptionID of where you are deployed ManagementUX Application.

#>
Param(
[Parameter(mandatory = $true)]
[PSCredential]$azureAdminCredentials,
[Parameter(mandatory = $true)]
[string]$SubscriptionId
)

#Authenticating to azure
Add-AzureRmAccount -SubscriptionId $SubscriptionId -Credential $azureAdminCredentials
Get-AzureRmWebApp

#Authenticating to Azure AD
Connect-AzureAD -Credential $azureAdminCredentials
Get-AzureADServicePrincipal

**Comment by bigpom** [comment]
Thank you, but the user has 'Contributor' and 'User Access Administrator' per the instructions.

**Comment by ravitejabeeram** [comment]
@bigpom Did you figure out? I am facing same issue.

**Comment by bigpom** [comment]
@ravitejabeeram No, the issue still exists for me.

**Comment by viswanadham-k** [comment]
Hi All,
Thank you for deploying the management tool, reason of this error: azure power shell cmdlets unable to authenticate  azure with your user credentials. So can you please execute the below power shell script in your local machine to know about failure. Before executing PowerShell script ensure your local machine is installed AzureRm, AzureAD Modules if not please read and find the description of the PowerShell Script.

<#
.Description 
    A Sample PowerShell script to check the azure authentication with PowerShell automation.

Run this PowerShell Script in Administrator mode.
This script depends on 2 powershell modules: AzureRM and AzureAD to get them execute 2 following commands.
Use "-AllowClobber" parameter if you have more than one version of PS modules installed
PS C:\>Install-Module AzureRM  -AllowClobber
PS C:\>Install-Module AzureAD  -AllowClobber

.PARAMETER azureAdminCredentials
 Required
 Provide credentials which you are provided to ManagementUX template Deployment.

.PARAMETER SubscriptionID
 Required
 Provide SubscriptionID of where you are deployed ManagementUX Application.

#>
Param(
[Parameter(mandatory = $true)]
[PSCredential]$AzureAdminCredentials,
[Parameter(mandatory = $true)]
[string]$SubscriptionId
)

#Authenticating to azure
Add-AzureRmAccount -SubscriptionId $SubscriptionId -Credential $AzureAdminCredentials
Get-AzureRmWebApp

#Authenticating to Azure AD
Connect-AzureAD -Credential $AzureAdminCredentials
Get-AzureADServicePrincipal

Solution:
Create a User in your azure tenant and provide azure subscription "Contributor" access to him. Then again execute this powershell script. If successfully executed then deploy the management ux with this particular user.

**Comment by bigpom** [comment]
Ran powershell successfully, but then realized user did not have permission to create a new Enterprise Application due to our security policy. Adjusted users permission to grant them the right and it ran without issue. Thank you all for the help
