### ISSUE TITLE
basicscale.ps1 incorrect variable and function name 4-WVD-scaling-script 

### ISSUE THREAD

**Issue by cbSean** [Azure/RDS-Templates#215]
In BasicScale.ps1 Line 109 `SetScriptVariable` is missing a hyphen and should be `Set-ScriptVariable` this resolves issues assigning variables in lines 147-149

Also Line 166 it is looking for an existing $isWVDServicePrincipal which doesn't exist in the config.json it is just $isServicePrincipal.  So that line can be changed to `$isWVDServicePrincipal = ($isServicePrincipal -eq "True")` .  Or remove line 166 and have line 167 do the check instead by changing it to ` if (!$isServicePrincipal) `

**Comment by cbSean** [comment]
Sorry for appending the 4-WVD-scaling-script in to the title.  I don't see where I can attach the label to the post.

**Comment by viswanadham-k** [comment]
Hi cbSean,
Can you please use below location basic scale script Microsoft recommended and follow the "Azure WVD Scaling-MSI.docx" documentation to configure the basic scale script in your VM.

https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/wvd-scaling-script

Let me know if you are facing any issues.

**Comment by ChristianMontoya** [comment]
@cbSean : Were you able to deploy the script? Can I go ahead and close?

**Comment by viswanadham-k** [comment]
Hi @cbSean 

Can you please access the below link and configure the latest version of WVD Scaling tool it is recommended by Microsoft. This version have your issue fix.

https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script

Let us know if you are still facing any issues.

Thanks,

**Comment by ChristianMontoya** [comment]
As @viswanadham-k mentioned, please try the new script that uses logic apps and is fully described here in the public documentation: [Set up scaling script](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script).

Closing this out. Please create a new issue if scenario reproduces.
