### ISSUE TITLE
Management UX deployment issue

### ISSUE THREAD

**Issue by ravitejabeeram** [Azure/RDS-Templates#216]
Deployment of managemetUX is failed after 2 hours with a timeout error. Tried multiple times but still is same.

**Comment by ravitejabeeram** [comment]
{ "id": "/subscriptions/b5000e4a-a735-4f1a-a684-2ee0a7739bcd/resourceGroups/TejaWVDTestRG/providers/Microsoft.Resources/deployments/Microsoft.Template/operations/D79CACC776A2A625", "operationId": "D79CACC776A2A625", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-08-22T14:07:29.0986194Z", "duration": "PT2H9.4291528S", "trackingId": "b07a4076-faae-4fc8-8d1e-ac0dda4f40db", "statusCode": "RequestTimeout", "statusMessage": { "error": { "code": "ResourceDeploymentFailure", "message": "The resource provision operation did not complete within the allowed timeout period. Please see https://aka.ms/arm-deploy for usage details." } }, "targetResource": { "id": "/subscriptions/b5000e4a-a735-4f1a-a684-2ee0a7739bcd/resourceGroups/TejaWVDTestRG/providers/Microsoft.Automation/automationAccounts/wvdsaas-autoAccount-eyvp6rqzacap2/jobs/1ebeea25-4878-5995-b844-ff35d9777f6b", "resourceType": "Microsoft.Automation/automationAccounts/jobs", "resourceName": "wvdsaas-autoAccount-eyvp6rqzacap2/1ebeea25-4878-5995-b844-ff35d9777f6b" } }}

**Comment by ravitejabeeram** [comment]
Does anyone encountered this?

**Comment by TVDKoni** [comment]
Can occure, if you have already an automation account and already used your free minutes. Try to change the sku of the automation account in the template.
