### ISSUE TITLE
Management UI Deployment Issue

### ISSUE THREAD

**Issue by ravitejabeeram** [Azure/RDS-Templates#219]
Management UI deployment is getting failed with the following error.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n }\r\n}"}]}

User I am using is a global administrator, doesn't have MFA enabled, RDS Owner and has Owner/Contributor rights on the subscription.

I noticed some old threads referring to permissions but in my case, all are in place. Does anyone else have the same issue with deployment? 
![WVD Issue1](https://user-images.githubusercontent.com/33288298/63593810-cb600a00-c582-11e9-8871-b18d9a700eac.JPG)

**Comment by Steveborough** [comment]
same issue here

**Comment by Steveborough** [comment]
although MFA is disabled, check your conditional access policy (if you have) and exclude this user as well. You can get more in-depth error logs from manually running the runbook it creates and checking the errors section

**Comment by ravitejabeeram** [comment]
This user is already excluded from conditional access policy.

**Comment by viswanadham-k** [comment]
Hi RaviTeja,
Thank you for deploying the management tool, reason of this error: azure power shell cmdlets unable to authenticate azure with your user credentials. So can you please execute the below power shell script in your local machine to know about failure. Before executing PowerShell script ensure your local machine is installed AzureRm, AzureAD Modules if not please read and find the description of the PowerShell Script.

<#
.Description
A Sample PowerShell script to check the azure authentication with PowerShell automation.

Run this PowerShell Script in Administrator mode.
This script depends on 2 powershell modules: AzureRM and AzureAD to get them execute 2 following commands.
Use "-AllowClobber" parameter if you have more than one version of PS modules installed
PS C:>Install-Module AzureRM -AllowClobber
PS C:>Install-Module AzureAD -AllowClobber

.PARAMETER azureAdminCredentials
Required
Provide credentials which you are provided to ManagementUX template Deployment.

.PARAMETER SubscriptionID
Required
Provide SubscriptionID of where you are deployed ManagementUX Application.

#>
Param(
[Parameter(mandatory = $true)]
[PSCredential]$AzureAdminCredentials,
[Parameter(mandatory = $true)]
[string]$SubscriptionId
)

#Authenticating to azure
Add-AzureRmAccount -SubscriptionId $SubscriptionId -Credential $AzureAdminCredentials
Get-AzureRmWebApp

#Authenticating to Azure AD
Connect-AzureAD -Credential $AzureAdminCredentials
Get-AzureADServicePrincipal

Solution:
Create a User in your azure tenant and provide azure subscription "Contributor" access to him. Then again execute this powershell script. If successfully executed then deploy the management ux with this particular user.
