### ISSUE TITLE
error while deployment. I think cos my password contains '.'

### ISSUE THREAD

**Issue by dariuszbz** [Azure/RDS-Templates#225]
{ "id": "/subscriptions/c9521a5f-da33-4293-a5ec-30cffce21063/resourceGroups/MySubscriptionNameVDA01/providers/Microsoft.Resources/deployments/Microsoft.Template/operations/5B3D1645A577BB10", "operationId": "5B3D1645A577BB10", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-08-28T08:57:07.3938652Z", "duration": "PT0.2292646S", "trackingId": "634bd18c-5e2e-4306-b9d5-ab57a1e3a3f1", "statusCode": "BadRequest", "statusMessage": { "code": "BadRequest", "message": "{\"Message\":\"The request is invalid.\",\"ModelState\":{\"variable.properties.value\":[\"Invalid JSON primitive: ^^.\\\".\"]}}" }, "targetResource": { "id": "/subscriptions/MySubsciptionID/resourceGroups/MySubscriptionNameVDA01/providers/Microsoft.Automation/automationAccounts/wvdsaas-autoAccount-u5yoegwdhl5qu/variables/password", "resourceType": "Microsoft.Automation/automationAccounts/variables", "resourceName": "wvdsaas-autoAccount-u5yoegwdhl5qu/password" } }}

**Comment by Sawal72** [comment]
We have the same error while deploying with the template. But, the management portals seems to be working fine after deployment.

**Comment by viswanadham-k** [comment]
Hi,
Can you please deploy with latest build from below location
https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/wvd-management-ux/deploy
