### ISSUE TITLE
How to add Hosts to Management Tool

### ISSUE THREAD

**Issue by Richsaunds** [Azure/RDS-Templates#227]
Have setup the management tool UX as per instructions, as part of our demo WVD setup. This has worked and we are able to see our WVD Host Pool. Have seen however there is the option to add a host, and when doing so this presents a registration key. 

However I cannot find any details on how you use this registration key on the host servers themselves, and how to actually add the host servers within the Management Tool, whcih then allows for individual hosts to be drained etc.

Any help on this would be appreciated?

Thanks

**Comment by viswanadham-k** [comment]
Hi,
It won't allow to create host from management portal. We can only generate/regenerate(if date is expired) registration key using "Add Host" button.
This registration key we can use while installing RD agents inside hosts through manual process.

**Comment by ChristianMontoya** [comment]
@Richsaunds : Please see these steps to use the registration token to add a host pool - https://docs.microsoft.com/en-us/azure/virtual-desktop/create-host-pools-powershell
