### ISSUE TITLE
WVD - deployment with a proxy

### ISSUE THREAD

**Issue by TVDKoni** [Azure/RDS-Templates#228]
My internet traffic flows over a proxy. During WVD hostpool deployment I get following error message:

My internet traffic flows over a proxy. During WVD hostpool deployment I get following error message:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{
 "status": "Failed",
 "error": {
 "code": "ResourceDeploymentFailure",
 "message": "The resource operation completed with terminal provisioning state 'Failed'.",
 "details": [
 {
 "code": "VMExtensionHandlerNonTransientError",
 "message": "Handler 'Microsoft.Powershell.DSC' has reported failure for VM Extension 'dscextension' with terminal error code '1001' and error message: 'Manifest download error from https://rdfepirv2am3prdstr07.blob.core.windows.net/3055d769a0ed485d8c5ea8a7cd24073e/Microsoft.Powershell_DSC_europewest_manifest.xml. Error: UnknownError. An exception occurred during a WebClient request.\\r\\n'"
 }
 ]
 }
}"}]}

How Do I have to handle a proxy in WVD hostpool deployment?

**Comment by viswanadham-k** [comment]
Hi,
Do you have access to the VM? Can you check this log file: C:\Windows\Temp\ScriptLog.log and please share with me.

**Comment by ChristianMontoya** [comment]
@TVDKoni : Can you please try adding that blob storage location for the XML? Closing out for the time being, please re-tag or re-open if you need further assistance.
