### ISSUE TITLE
ManagementUX permission problems

### ISSUE THREAD

**Issue by TVDKoni** [Azure/RDS-Templates#230]
Used the deployment script to deploy my ManagementUX. Tried to login after deployment and got app access error:

AADSTS650056: 
Misconfigured application. This could be due to one of the following: The client has not listed any permissions for 'AAD Graph' in the requested permissions in the client's application registration. Or, The admin has not consented in the tenant. Or, Check the application identifier in the request to ensure it matches the configured client application identifier. Please contact your admin to fix the configuration or consent on behalf of the tenant.

Added follwing API permission by hand:
Microsoft Graph (1)  User.Read Delegated
And grantet consent

Now I was able to login correctly. May at the top right, the user is still not shown. And in addition, I'm not able to select a tenant group. The combobox is empty.

We are using AAD and AADDS.

Does one has the right permissions to be set?

What can be the problem?

**Comment by jroeb** [comment]
Same issue here. Did you solve it?

**Comment by TVDKoni** [comment]
Not yet. Don't know which permissions are really required.

**Comment by TVDKoni** [comment]
Redeployed actual zips and now the management interface started to work. Looks like they have fixed something in their code.
