### ISSUE TITLE
WVDMgmtSetup.ps1 Script might have a bug?

### ISSUE THREAD

**Issue by AlexJPawlak** [Azure/RDS-Templates#237]
Line 97 in Powershell script for WVD UX https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/wvd-management-ux/deploy/scripts/New-WVDMgmtSetup.ps1 : 

	$wvdInfraWebAppObjId = $serviceIdinfo.Id.GUID

As I have MFA on and didn't want to turn it off for deployment I ran the script by hand outside of automation environment. I have reached this step and it errored out - the $ServiceIdInfo does have a property Id, but it's just a string property - it doesn't have a nested property of GUID. After I changed it, it worked for me: 

	$WVDServicePrincipal = Get-AzureADServicePrincipal -ObjectId $wvdInfraWebAppObjId #-SearchString $wvdInfraWebAppName | Where-Object {$_.DisplayName -eq $wvdInfraWebAppName}

Can you check if this also affects Automation account? Should be, but maybe there's a wizardry I'm unaware of

Note: I used Azure Cloud Shell to run this. Might be the Cloud Shell has different Modules loaded that return slightly different objects?

**Comment by ChristianMontoya** [comment]
@AlexJPawlak : I think the Cloud shell is different. Do you know if your proposed change would also work on (desktop) PowerShell ?

**Comment by AlexJPawlak** [comment]
Not sure to be honest. I've looked through available source code, ex. here: 

https://github.com/nallagoppula/Azure-powershell/tree/e1d6fb9dfbbbbc75a51900844e7f3f37e9e6cf08/src/Common/Commands.Common.Graph.RBAC/ActiveDirectory

There output of "Get-AzureADServicePrincipal" is Microsoft.Azure.Graph.RBAC.Version1_6.ActiveDirectory.PSADServicePrincipal which has properties: 

        public string[] ServicePrincipalNames { get; set; }

        public Guid ApplicationId { get; set; } 

and inherited from PSADObject: 

        public string DisplayName { get; set; }

        public Guid Id { get; set; }

        public string Type { get; set; }

So based on the above - there's property "Id" and "ApplicationId" but nothing that would contain a nested property of any sort in form of "Id.Guid". Or I'm looking at wrong thing here? Can you reproduce this? Thanks!

**Comment by viswanadham-k** [comment]
Hi @alex-frankel 

Here $serviceIdinfo.Id retrieving the value like below output. So we added $serviceIdinfo.Id.Guid and it retrieving the value of the ID and store into a variable. 

$serviceIdinfo.Id output
![image](https://user-images.githubusercontent.com/54656839/73426822-54ae1080-435b-11ea-9c00-3ac7b2083b69.png)

$serviceIdinfo.Id.Guid output
![image](https://user-images.githubusercontent.com/54656839/73427164-2f6dd200-435c-11ea-8cbe-7c165b924339.png)

Thanks,

**Comment by alex-frankel** [comment]
Hi - I think I was incorrectly mentioned here. This is not something I work on. Looks like you were trying to mention @AlexJPawlak

**Comment by AlexJPawlak** [comment]
I think it has been resolved in 
https://github.com/Azure/RDS-Templates/commit/9430743c47f1293b463bfcb3bbb74a3411943d61#diff-4202f6f05d1cc87a0f9cb3384240a71c
 by @ptgadmin-cse - now the variable seems to be referenced properly. Forgive me my doubts - I was simply unsure if that's something wrong in the script or within my environment or version of libraries I have been using. Should be closed off now I guess. Thanks all!
