### ISSUE TITLE
Will Not Deploy: Conflict

### ISSUE THREAD

**Issue by edm-ms** [Azure/RDS-Templates#239]
I cannot get this to deploy, and I hit the same error every time. It throws some sort of conflict with part of the Azure Automation deployment.

STATUS Conflict
STATUS MESSAGE {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'."
  }
}
PROVISIONING STATE Failed
TIMESTAMP 9/26/2019, 8:34:23 AM
DURATION 1 minute 2 seconds
TYPE Microsoft.Automation/automationAccounts/jobs

**Comment by miketoupin** [comment]
I having the exact same error "The resource operation completed with terminal provisioning state 'Failed'."

I do having permission for App Registration, MFA has been disabled for my UPN...

**Comment by mattgillard** [comment]
same error for me.  Is this supposed to work?

**Comment by viswanadham-k** [comment]
Hi All,
I hope you got this error due to the credentials you enter when deploying the Web App, your credentials weren't a 'Contributor' at the Subscription level. So please check your credentials have "Contributor" access at subscription. If not please assign the role of contributor to your credentials and then deploy template newly.

**Comment by weltan** [comment]
Just FYI for this,

I was getting this error as well, but it now deploys fine. Basically, there are a *lot* of small gotchas that could give you that error, all revolving around access being denied to various resources from the account you just provisioned. Some things I was missing:

1. As @viswanadham-k says, make sure the user you created as the `Azure AD User Principal Name` has Contributor on the Subscription level.
2. Log in to portal.azure.com with that account, just to make sure it's all the way set up, and that MFA is not turned on for that account
3. Double-check and make sure you that the server and client apps have consent by visiting the Windows Virtual Desktop Consent Page (https://rdweb.wvd.microsoft.com/)

Yes, it's all in the docs. Yes, it's very easy to miss even so :) So, basically, keep poking and make sure you read the docs multiple times for something you've missed. 

@viswanadham-k : consider me a slightly frustrated deployer :) the error messaging on these deploys (really for the entire Azure VDI setup flow) is subpar for identifying issues. I know it's still in Preview, so hopefully this can get improved on before this hits GA.

**Comment by mattgillard** [comment]
> Hi All,
> I am part of the this template development. Reason of this error is due to the credentials you enter when deploying the Web App, your credentials weren't a 'Contributor' at the Subscription level. So please check your credentials have "Contributor" access at subscription. If not please assign the role of contributor to your credentials and then deploy template newly.

Yeah sorry I realised this a few hours after I posted.  This was exactly the problem (but a bit unclear).  All good!
