### ISSUE TITLE
Error when Deploying WVD using ARM Template - Unable to download managedDisks-galleryvm.json

### ISSUE THREAD

**Issue by jigjim** [Azure/RDS-Templates#243]
While deploying the WVD hostpool from Azure portal, I downloaded the template. I am using this templates in my Visual Studio C# code to deploy the WVD hostpool by passing different parameter. My template structure is as follow, I have changed the necessary path for json files, when running the code i am getting error. Please help. I believe it has to do something with Artifactlocation value, below are two url i am using for _artifactsLocation. Even from Powershell i am getting same error.

(1) https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/wvd-management-ux/deploy/
(2) https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool/nestedtemplates/managedDisks-galleryvm.json

**### Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/wvd-management-ux/deploy/nestedtemplates/managedDisks-galleryvm.json**

deploy.ps1
deploy.sh
deployer.rb
DeploymentHelper.cs
parameters.json
template.json

**Comment by viswanadham-k** [comment]
Hi,

Are you trying to deploy the Management UX tool or Create and provision WVD hostpool?

**Management UX Tool:** 
(1) https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/wvd-management-ux/deploy/ 
**Create and provision WVD Hostpool:**
(2) https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool/nestedtemplates/managedDisks-galleryvm.json

**Comment by ChristianMontoya** [comment]
@jigjim : For the **Create and provision host pool** template, you'll need to also have the **/nestedtemplates/** and its nested files for the template to work.

**Comment by jigjim** [comment]
This is fixed now. I put the default artificatlocation value to below in template.json file. No other changes and all files are exact when downloaded from deployment hostpool. Thank you for your support,
            "defaultValue": "https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool/"
