### ISSUE TITLE
Microsoft.Template "Conflict Error"

### ISSUE THREAD

**Issue by johndrosa** [Azure/RDS-Templates#245]
I have tried to run this in several accts and had a few colleagues try it as well. We seem to be getting the same errors.
![image](https://user-images.githubusercontent.com/38889348/67527149-509b9400-f684-11e9-92af-4504d1742f51.png)

Here is the accompanying "Raw Error"

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    }
  ]
}

It was suggested by another friend to attempt the deployment via CLI, but I was unsuccessful going that route also.

Please help!!!!

**Comment by patelpr18** [comment]
Getting the same issue despite trying with a number of accounts +1

**Comment by Digiroka** [comment]
Hi, do you have conditional access or MFA enabled for the account you are using to deploy?
If so, try creating a new service account with Contributor access to the target Resource Group, and use this account in the deployment.

**Comment by patelpr18** [comment]
Hi,

I did try using a cloud only account which has MFA disabled and which is excluded from CA policies but still no joy.

If i was to go with the suggestion of the new account, it would still have CA policies applied to it which is where I believe the issue possibly lies.

Kind Regards

Prashant


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by Digiroka** [comment]
conditional access and MFA both broke the process for me, you can check in the output of the created runbooks if they fail. 
Personally, I'm getting a conflict error too now, but for a different reason...

"code": "Conflict", "message": "Job with specified id already exists. Job id: 9db3ef68-debc-5579-b445-a448b74d66e8"

The job doesn't exist already, its a new resource group.

**Comment by johndrosa** [comment]
I was getting the "Job with specified id already exists error" when I used my Microsoft internal acct. I then tried it in my personal, where I have nothing (i delete as I go, little to no charges) and that's where I was getting the "conflict" error. The description is so vague, I have no clue what the conflict actually is.

Has anyone else been able to get this to work?
Can you share the steps you took for a successful deployment?

**Comment by Digiroka** [comment]
Ok, ive just got it to work. I got round the 'deployment already exists' issue by deploying a new RG in a new location with all new naming conventions. I then had the generic 'conflict' issue, which I narrowed down to a bad password.

Steps I took:

1) Created a new service account with contributor right on the subscription (I also gave it Tennant Creator rights on the WVD enterprise app, but I dont think this is required)

2) Log into the azure portal with this account to ensure it doesn't need to change pw on first logon (doh)

3) Deployed the template, creating a new RG to host the application

Job completed without issue.

**Comment by johndrosa** [comment]
> Ok, ive just got it to work. I got round the 'deployment already exists' issue by deploying a new RG in a new location with all new naming conventions. I then had the generic 'conflict' issue, which I narrowed down to a bad password by reviewing the newly created automation account job errors.
> 
> Steps I took:
> 
> 1. Created a new AAD service account with contributor right on the subscription (I also gave it Tennant Creator rights on the WVD enterprise app, but I dont think this is required).
> 2. Log into the azure portal with the new service account to ensure it doesn't need to change pw on first logon (doh)
> 3. Deployed the template, creating a new RG to host the application
> 
> Job completed without issue.

Thank you Digiroka, I'll try these steps to see if I can get it to work. 

I'll post in the thread if it works for me.

**Comment by mendreHOM** [comment]
I have been trying to get this to deploy off and on for months and still not having any luck,  Today I followed the steps outlined above with no luck.

1. Created a new user with subscription contributor access and TenantCreator rights on WVD enterprise application
2. Disabled conditional access for the org.
3. Logged in to Azure Portal as the new Subscription Contributor.
4.  Created a brand new RG during provisioning.
5. Selected a different Region then I have used before.
6. Used a completely new application name than I used in the past.

Still getting a Conflict error "The resource operation completed with terminal provisioning state 'Failed'." 

**Resource**: wvdsaas-autoAccount-uhjnjrmsaexkm/42c52c37-f8c1-5023-b528-0f19f140db96" 
**Type**: Microsoft.Automation/automationAccounts/jobs

**Comment by johndrosa** [comment]
It's still failing for me as well. I have reached out to the PGs for assistance with it. Microsoft Ignite is this week, so there are some delays. I am hoping to get some clarity/assistance by next week some time.

**Comment by Digiroka** [comment]
You should be able to see specific details for the failure if you browse to the run book created as part of the deployment, are review the details in the ‘output’ tab. This is how I was able to identify the bad password.

**Comment by mendreHOM** [comment]
Error occurred while executing NewApplication 
Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.
RequestId: d1fb2152-a4f8-48c9-a297-488ba39ac7e4
DateTimeStamp: Wed, 06 Nov 2019 16:02:43 GMT
HttpStatusCode: Forbidden
HttpStatusDescription: Forbidden
HttpResponseStatus: Completed

Is there a privilege I'm missing?  This user has contributer access on the SUB and TenantCreator on the WVD enterprise application in Azure AD.

**Comment by Digiroka** [comment]
Ok, that’s progress! In my case, I used the newly created service account in the template, and logged into azure with an owner account for deployment. I’m not in the office tomorrow, but I’ll test the process with just my service account when I get the chance, to see if I can replicate.

**Comment by mendreHOM** [comment]
Resolved the issue.  The new user didn't have permission in Azure AD to create Enterprise app.  Once I gave the account the "Application Administrator" Role in Azure AD it published correctly.

**Comment by ChristianMontoya** [comment]
@Digiroka : Were you also able to deploy?

**Comment by Digiroka** [comment]
> @Digiroka : Were you also able to deploy?

@ChristianMontoya - I’ve had it deployed since October, just trying to help others :).
Thanks.

**Comment by johndrosa** [comment]
HI Guys, 
Sorry for not following up on the thread. I was eventually able to get this to deploy successfully back in November, with a little help. 
Here is what I found:
1. I was using my "outlook.com" email address with my MSDN acct. This somehow creates a conflict with PowerShell. My colleagues that had similar failures were "live.com" emails. The ones that deployed successfully other email accts.
2. At the time when I was having issues with this deployment, there were issues with the EastUS endpoints in the deployment of this template. I wasn't given specifics, only that there were issues.
3. I created a new user and granted "contributor" access
4. I logged in using the credentials for the new user. This is the same info that will be entered for “Azure AD User Principal Name” & “Azure Login Password.”
5.  WestUS2 gave me no headaches with the deployment.
6. The template has a built in "remove" script that will delete the excess resources created during deployment.

I was also provided with a PS script to run for verification the tenant was setup correctly.

`<#
.Description
A Sample PowerShell script to check the azure authentication with PowerShell automation.

Run this PowerShell Script in Administrator mode.
This script depends on 2 powershell modules: AzureRM and AzureAD to get them execute 2 following commands.
Use "-AllowClobber" parameter if you have more than one version of PS modules installed
PS C:>Install-Module AzureRM -AllowClobber
PS C:>Install-Module AzureAD -AllowClobber

.PARAMETER azureAdminCredentials
Required
Provide credentials which you are provided to ManagementUX template Deployment.

.PARAMETER SubscriptionID
Required
Provide SubscriptionID of where you are deployed ManagementUX Application.

#>
Param(
[Parameter(mandatory = $true)]
[PSCredential]$AzureAdminCredentials,
[Parameter(mandatory = $true)]
[string]$SubscriptionId
)

#Authenticating to azure
Add-AzureRmAccount -SubscriptionId $SubscriptionId -Credential $AzureAdminCredentials
Get-AzureRmWebApp

#Authenticating to Azure AD
Connect-AzureAD -Credential $AzureAdminCredentials
Get-AzureADServicePrincipal `


Looks like the document has been modified recently. What I found may no longer be relevant.
