### ISSUE TITLE
4-WVD-scaling-script Failed to authenticate with WVD Tenant with a standard account

### ISSUE THREAD

**Issue by RyanLWilliams** [Azure/RDS-Templates#252]
On line 166 of the script the line should be $isWVDServicePrincipal = ($isServicePrincipal -eq "True") instead of $isWVDServicePrincipal = ($isWVDServicePrincipal -eq "True") or the config.json variable name should be updated to isWVDServicePrincipal

**Comment by viswanadham-k** [comment]
Hi RyanLWilliams,
Thank you for testing the WVD Scaling..
Can you please use below github location basic scale script Microsoft recommended and follow the "Azure WVD Scaling-MSI.docx" documentation to configure the basic scale script in your VM.

https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/wvd-scaling-script

Let me know if you are facing any issues.

**Comment by RyanLWilliams** [comment]
Should that script be used instead of the script found in here https://github.com/Azure/RDS-Templates/tree/master/wvd-sh/WVD%20scaling%20script If so please confirm because then this article https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-desktop/set-up-scaling-script.md will need to be updated as it points to the wrong repository.

**Comment by RyanLWilliams** [comment]
Can you confirm this directory https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/wvd-scaling-script should be used over this directory https://github.com/Azure/RDS-Templates/tree/master/wvd-sh/WVD%20scaling%20script

Currently, the MS docs point to https://github.com/Azure/RDS-Templates/tree/master/wvd-sh/WVD%20scaling%20script which also has the PowerShell function for storing credentials

**Comment by viswanadham-k** [comment]
Hi @RyanLWilliams 

Can you please access the below link and configure the latest version of WVD Scaling tool it is recommended by Microsoft. This version have your issue fix.

https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script

Let us know if you are still facing any issues.

Thanks,

**Comment by ChristianMontoya** [comment]
As @viswanadham-k mentioned, please try the new script that uses logic apps and is fully described here in the public documentation: [Set up scaling script](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script).

Closing this out. Please create a new issue if scenario reproduces.
