### ISSUE TITLE
No access to WVD management portal when using groups for role assignment

### ISSUE THREAD

**Issue by Sawal72** [Azure/RDS-Templates#254]
When using AAD groups with RDS role assingments, users get ""Server App" is  not consented".

I have assign a AAD groups the RDS OWNER role, but users which are group member get the warning above. When I give the user the RDS OWNER role, it's works fine.

**Comment by Monual** [comment]
We are having this issue as well.

**Comment by viswanadham-k** [comment]
Hi @Sawal72 and @Monual 
Apologize for the late response, management UX currently does not support any of the "RDS role assignments" made for Azure AD groups. If you would like to use the management UX, you will need to have your specific user account added as for the role assignment. 

Thanks,

**Comment by ChristianMontoya** [comment]
@Monual : Adding as a feature request, but closing out. Thanks for your feedback!
