### ISSUE TITLE
WVD-SAAS-UX-Conflict

### ISSUE THREAD

**Issue by gmilorava** [Azure/RDS-Templates#256]
Hello,
I am getting a Conflict error when deploying MSFT-WVD-SAAS-UX Environment. 
Cant create an Azure Automation job, All others deployed successfully. 

I Have Multi-Factor Authentication (MFA) disabled
I Have permission to create resources in your Azure subscription
I Have permission to create an Azure AD application.

Could someone assist me with the following error?

`{ "id": "/subscriptions/XXXXXXXXXXXXXXXXXXXXX
/resourceGroups/srwvdwebmgmtuirg/providers/Microsoft.Resources/deployments/Microsoft.Template/operations/140713758F9930F5", "operationId": "140713758F9930F5", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-11-06T23:55:05.3829997Z", "duration": "PT1M1.8983005S", "trackingId": "d49d6a6c-e40d-438f-af1a-c9e2a6a481d6", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'." } }, "targetResource": { "id": "/subscriptions/1c5c4d8b-4234-41fb-a069-df5149426ae4/resourceGroups/srwvdwebmgmtuirg/providers/Microsoft.Automation/automationAccounts/wvdsaas-autoAccount-e6nxlj5dxtte4/jobs/e73ec403-826a-5b96-92ad-a5823caf7b1f", "resourceType": "Microsoft.Automation/automationAccounts/jobs", "resourceName": "wvdsaas-autoAccount-e6nxlj5dxtte4/e73ec403-826a-5b96-92ad-a5823caf7b1f" } }}`

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n }\r\n}"}]}`

Please see screenshots below
https://ibb.co/zh1Cd22

https://ibb.co/s5T3ytm

**Comment by viswanadham-k** [comment]
Hi,

One of the customer got this same error, and it was due to the credentials you enter when deploying the Web App. While his user was a Global Admin (and as RDS Tenant Owner), they weren't a 'Contributor' at the Subscription level. So he went into that particular subscription and assigned the role of contributor, and then this deploy template started working.

Hope this helps!

**Comment by ddgdevops** [comment]
I was having the same issue, working on it all night last night. Today i started all over with a new Resource group, to have the same issue in the end..Then just saw your comment, and tested this.. (Also my user was Global admin, and i just added it as contrinutor to the subscription)

That made it work and management ui is running! 

So thanks for sharing! :)

**Comment by gmilorava** [comment]
Hello Guys,

Thanks for you reply. Actually my problem was different. The client had some restriction rules in conditional access. Once he excluded my user from restricted rules everything worked.

Thanks,
George

**Comment by ymaxwell** [comment]
I am running into the same Automation Job creation issue despite using an account that is an Owner for Azure subscription, global admin in AAD, and no MFA enabled on account. "Conflict" is what i see in JSON output when deploying MSFT-WVD-SAAS-UX Environment. Below error occurs when creating the automation job which comes directly after successfully creating Automation Account. 

Does anyone have any additional ideas to get past this?

 
**Resource Group -> Activity Log -> Failed operation -> JSON**
    _"resourceType": {
        "value": "Microsoft.Automation/automationAccounts/jobs",
        "localizedValue": "Microsoft.Automation/automationAccounts/jobs"
    },
    "resourceId": "/subscriptions/xxxxxxx-xxxx-xxx-xxxxx-xxxxxxxxxxxxxx/resourcegroups/VDI_Basic/providers/Microsoft.Automation/automationAccounts/wvdsaas-autoAccount-xxxxxxxxxxx/jobs/xxxxxxx-xxxx-xxx-xxxxx-xxxxxxxxxxxxxx",
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "",
        "localizedValue": ""
    },
    "submissionTimestamp": "2020-01-13T17:48:03.1413201Z",
    "subscriptionId": "xxxxxxx-xxxx-xxx-xxxxx-xxxxxxxxxxxxxx",
    "properties": {
        "statusCode": "Conflict",
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceDeploymentFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\"}}"
    },
    "relatedEvents": []_


**template overview Raw Error**
_{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    }
  ]
}_

![image](https://user-images.githubusercontent.com/8505005/72285091-10efa300-3608-11ea-8542-a2cbb392db04.png)




![image](https://user-images.githubusercontent.com/8505005/72285141-2a90ea80-3608-11ea-8791-f04de065fb5f.png)

**Comment by viswanadham-k** [comment]
Hi,
Thank you for deploying the management tool, reason of this error: azure power shell cmdlets unable to authenticate azure with your user credentials. So can you please execute the below power shell script in your local machine to know about failure. Before executing PowerShell script ensure your local machine is installed AzureRm, AzureAD Modules if not please read and find the description of the PowerShell Script.

<#
.Description
A Sample PowerShell script to check the azure authentication with PowerShell automation.

Run this PowerShell Script in Administrator mode.
This script depends on 2 powershell modules: AzureRM and AzureAD to get them execute 2 following commands.
Use "-AllowClobber" parameter if you have more than one version of PS modules installed
PS C:>Install-Module AzureRM -AllowClobber
PS C:>Install-Module AzureAD -AllowClobber

.PARAMETER azureAdminCredentials
Required
Provide credentials which you are provided to ManagementUX template Deployment.

.PARAMETER SubscriptionID
Required
Provide SubscriptionID of where you are deployed ManagementUX Application.

#>
Param(
[Parameter(mandatory = $true)]
[PSCredential]$AzureAdminCredentials,
[Parameter(mandatory = $true)]
[string]$SubscriptionId
)

#Authenticating to azure
Add-AzureRmAccount -SubscriptionId $SubscriptionId -Credential $AzureAdminCredentials
Get-AzureRmWebApp

#Authenticating to Azure AD
Connect-AzureAD -Credential $AzureAdminCredentials
Get-AzureADServicePrincipal

Solution:
Create a User in your azure active directory and provide azure subscription "Contributor" access to him. Then again execute this powershell script. If successfully executed then deploy the management ux with this particular user.

**Comment by ChristianMontoya** [comment]
Closing this out right now. Please re-open if necessary.
