### ISSUE TITLE
4-WVD-scaling-script multi-tenant configuration issue

### ISSUE THREAD

**Issue by skonrad-MFI** [Azure/RDS-Templates#258]
Hi There, I am attempting to deploy the Start/Stop script for WVD, but I am running into issues. We have a multi tenant environment where our AzureAD and WVD control plane lives in one Azure Tenant, and our WVD VM Infrastructure lives in another Azure Tenant. We have MFA enabled for all Admin accounts.
Does the Start/Stop Scaling script work with a split environment like ours? Does the account that periodically performs the Start/Stop require MFA disabled, or can we use an App Service Registration?

**Comment by ChristianMontoya** [comment]
Closing this issue, but feel free to re-open if you need to.
