### ISSUE TITLE
WVD Management WEBUX

### ISSUE THREAD

**Issue by aniltv09** [Azure/RDS-Templates#260]
After deploying WVD Management WEBUX, was able to login fine but after that it load page but it not showing anything like no tenant or user who logged in just white blank page.

**Comment by jigjim** [comment]
Did you created the tenant with Svc Principal, if so then you can see all tenants.

Jignesh Patel| Enterprise Consultant
727.251.3093 cell
jignesh.patel@coretek.com<mailto:jignesh.patel@coretek.com>
http://www.coretekservices.com<http://www.coretekservices.com/>

Coretek Services
34900 Grand River Ave
Farmington Hills, MI 48335

[cid:image002.jpg@01D374F1.099D7210]<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.coretekservices.com%2F&data=02%7C01%7Cstephanie.smith%40coretek.com%7C2630149d72cf44b680a108d60ea317b8%7Cf7f66891a582418d999ecb1be5354253%7C1%7C0%7C636712490982903741&sdata=%2FfLRiQSx8sUlrF3YMJby1CfXBaROEDiGs%2Blrw05EtKk%3D&reserved=0>    [Citrix_Innovation_Award_Partners_Winner_BLK70 (002)] <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.citrix.com%2Fgo%2Finnovation-award%2Fpartner-innovation.html&data=02%7C01%7Cstephanie.smith%40coretek.com%7C2630149d72cf44b680a108d60ea317b8%7Cf7f66891a582418d999ecb1be5354253%7C1%7C0%7C636712490982903741&sdata=jc1iuushZ%2FnpYpAPv6mRaBo9JKJhII%2BOOZGz05cWFAU%3D&reserved=0> [badge]

Metro Detroit’s 101 Best & Brightest Companies to work for!
National Best & Brightest Companies to work for!

**Comment by aniltv09** [comment]
Yes, It was working fine but now when click on browse it load page (Which shows Windows Virtual Desktop) but not showing who logged in (it shows () instead of signed in user) and cannot sign out too.

**Comment by aniltv09** [comment]
> Did you created the tenant with Svc Principal, if so then you can see all tenants. Jignesh Patel| Enterprise Consultant 727.251.3093 cell jignesh.patel@coretek.com<mailto:jignesh.patel@coretek.com> http://www.coretekservices.com<http://www.coretekservices.com/> Coretek Services 34900 Grand River Ave Farmington Hills, MI 48335 [cid:image002.jpg@01D374F1.099D7210]<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.coretekservices.com%2F&data=02%7C01%7Cstephanie.smith%40coretek.com%7C2630149d72cf44b680a108d60ea317b8%7Cf7f66891a582418d999ecb1be5354253%7C1%7C0%7C636712490982903741&sdata=%2FfLRiQSx8sUlrF3YMJby1CfXBaROEDiGs%2Blrw05EtKk%3D&reserved=0> [Citrix_Innovation_Award_Partners_Winner_BLK70 (002)] <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.citrix.com%2Fgo%2Finnovation-award%2Fpartner-innovation.html&data=02%7C01%7Cstephanie.smith%40coretek.com%7C2630149d72cf44b680a108d60ea317b8%7Cf7f66891a582418d999ecb1be5354253%7C1%7C0%7C636712490982903741&sdata=jc1iuushZ%2FnpYpAPv6mRaBo9JKJhII%2BOOZGz05cWFAU%3D&reserved=0> [badge] Metro Detroit’s 101 Best & Brightest Companies to work for! National Best & Brightest Companies to work for! From: aniltv09 <notifications@github.com> Sent: Friday, November 15, 2019 2:08 PM To: Azure/RDS-Templates <RDS-Templates@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Azure/RDS-Templates] WVD Management WEBUX (#260) After deploying WVD Management WEBUX, was able to login fine but after that it load page but it not showing anything like no tenant or user who logged in just white blank page. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FRDS-Templates%2Fissues%2F260%3Femail_source%3Dnotifications%26email_token%3DAMLMQ7Z7KLOSBYZVM6WVIBTQT3XPZA5CNFSM4JN7BBX2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HZWC4GQ&data=02%7C01%7Cjignesh.patel%40coretek.com%7Cae8b1840a2af44617b9f08d769ff16da%7Cf7f66891a582418d999ecb1be5354253%7C1%7C0%7C637094416635275080&sdata=XCVljYMwMEYixVbgDB76psZVbJOJD%2B8tEB721DuVwDQ%3D&reserved=0>, or unsubscribe<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMLMQ73ULJCBFZEP53J6V5TQT3XPZANCNFSM4JN7BBXQ&data=02%7C01%7Cjignesh.patel%40coretek.com%7Cae8b1840a2af44617b9f08d769ff16da%7Cf7f66891a582418d999ecb1be5354253%7C1%7C0%7C637094416635285067&sdata=hOMj8m4ldyBX05CM3LzqD09UfqhG02Kqyb%2FMbNlFjQI%3D&reserved=0>. This e-mail and its attachments may contain information that is confidential and that may be subject to legal privilege and copyright. References herein to "Coretek" mean Coretek Services. If you are not the intended recipient you may not peruse, use, disclose, distribute, copy or retain the message. If you have received the message in error, please notify the sender immediately by e-mail, facsimile or telephone and return and thereafter destroy the original message.


Yes, It was working fine but now when click on browse it load page (Which shows Windows Virtual Desktop) but not showing who logged in (it shows () instead of signed in user) and cannot sign out too.

**Comment by jroeb** [comment]
same issue here.

svc principal works fine. other users with assigned "RDS Owner" role receive an empty page.

any updates or suggestions on that issue so far?

**Comment by viswanadham-k** [comment]
Hi Aniltv09/Jroeb,

I have investigated your issue and found the solution. 

Solution:When you first load the web address, (This can be found in the overview of your web application), you will be asked to consent on behalf of your organisation. You will need to accept this to progress.

![image](https://user-images.githubusercontent.com/54656839/69514630-fab35800-0f71-11ea-9ffc-0e2efd628734.png)

**Note: Consent popup will take to load some time (40 to 60 seconds). Please be wait until it's loading.**

If you are still facing any issues please ping me on teams (viswanadham.kudapu@peopletech.com).

**Comment by jroeb** [comment]
thank you for your feedback!

the customer had the chance to further investigated on that issue. all the administrative accounts have mfa enabled, which blocks access to the portal page. as soon as he disables mfa for an administative account, he is able to get access to the portal.

any plans to support mfa enabled accounts on that portal? this is a fundamental requirements based on the security policy in most of our customers implementations.

**Comment by ChristianMontoya** [comment]
@jroeb : We have provided new documentation to [create an Azure AD application and deploy resources through PowerShell](https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell), which should allow "MFA-required" users to create a management UX.
