### ISSUE TITLE
unknown_user_type error during deployment

### ISSUE THREAD

**Issue by jpsebasti** [Azure/RDS-Templates#269]
I had been working with Azure Support on this. They didn't realize that they weren't supposed to be supporting this product.  Anyway we were not able to get a resolution so that support ticket was closed and now I'm attempting to get support here.
The account I'm using to attempt the deployment of this WVD UI app has ownership of the subscription and also contributor of the subscription (we have tried various combinations of privs but at last attempt, the account has both ownership and contributor on the subscription).

Attempting the deployment, we are getting the following errors and Azure support has no idea what the issue is:

PS C:\WINDOWS\system32> Get-AzureRmAutomationJobOutput -Id 31c2df9d-4a1d-5962-9918-8b55c596865a -ResourceGroupName nwmwvgmgt-rg -AutomationAccountName wvdsaas-autoAccount-66fha6h7aps74 

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824368312026_00000000000000000001
Time                  : 11/20/2019 9:33:56 PM +00:00
Summary               : 
Type                  : Output

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824702687021_00000000000000000002
Time                  : 11/20/2019 9:34:30 PM +00:00
Summary               : 
Type                  : Output

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824703311982_00000000000000000003
Time                  : 11/20/2019 9:34:30 PM +00:00
Summary               : 
Type                  : Output

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824703780988_00000000000000000004
Time                  : 11/20/2019 9:34:30 PM +00:00
Summary               : 
Type                  : Output

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824704249498_00000000000000000005
Time                  : 11/20/2019 9:34:30 PM +00:00
Summary               : 
Type                  : Output

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824704718478_00000000000000000006
Time                  : 11/20/2019 9:34:30 PM +00:00
Summary               : 
Type                  : Output

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824713937055_00000000000000000007
Time                  : 11/20/2019 9:34:31 PM +00:00
Summary               : unknown_user_type: Unknown User Type
Type                  : Error

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824718156073_00000000000000000008
Time                  : 11/20/2019 9:34:31 PM +00:00
Summary               : Run Connect-AzureRmAccount to login.
Type                  : Error

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824721906074_00000000000000000009
Time                  : 11/20/2019 9:34:32 PM +00:00
Summary               : No subscription found in the context.  Please ensure that the credentials you pr...
Type                  : Error

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824735499784_00000000000000000010
Time                  : 11/20/2019 9:34:33 PM +00:00
Summary               : One or more errors occurred.: unknown_user_type: Unknown User Type
Type                  : Error

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824736437289_00000000000000000011
Time                  : 11/20/2019 9:34:33 PM +00:00
Summary               : One or more errors occurred.
Type                  : Error

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824737218579_00000000000000000012
Time                  : 11/20/2019 9:34:33 PM +00:00
Summary               : unknown_user_type: Unknown User Type
Type                  : Error

ResourceGroupName     : nwmwvgmgt-rg
AutomationAccountName : wvdsaas-autoAccount-66fha6h7aps74
JobId                 : 31c2df9d-4a1d-5962-9918-8b55c596865a
StreamRecordId        : 31c2df9d-4a1d-5962-9918-8b55c596865a_00637098824738155814_00000000000000000013
Time                  : 11/20/2019 9:34:33 PM +00:00
Summary               : One or more errors occurred.: unknown_user_type: Unknown User Type
Type                  : Output

**Comment by ChristianMontoya** [comment]
@jpsebasti : Apologize for the delayed response. We recently migrated from AzureRm commands to Az commands. Would you be able to re-deploy from here and let us know if this works: https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/wvd-management-ux .

Also, does your account require MFA? If so, you may actually need to run the steps to deploy the management UX through PowerShell: https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell

**Comment by ChristianMontoya** [comment]
@jpsebasti : Closing for now. Please try with the guidance I posted above, but feel free to re-open if you need to.
