### ISSUE TITLE
Shutdown issue

### ISSUE THREAD

**Issue by emmettd** [Azure/RDS-Templates#270]
When I was testing this script, I created a WVD environment with 3 WIndows 10 machines (WVD-0, WVD-1, & WVD-2). All 3 machines were up and running. I then had a use launch a browser and go to 
https://rdweb.wvd.microsoft.com/webclient. They clicked on one of the icons and logged in successfully.

I then ran this script, which was during non-peak hours, where only this user was connected to WVD-0. WVD-1 & WVD-2 had 0 users connected. When the script ran, it kicked the user off of WVD-0 and then deallocated WVD-0 & WVD-1, leaving WVD-2 up and running.

In this scenario, I would have expected WVD-0 to be left up and running since it had a user connected and deallocate WVD-1 & WVD-2 being that these 2 machines had 0 users connected.

**Comment by ChristianMontoya** [comment]
@emmettd : Thanks for this. Let me forward to the team, as I thought that the script would have already done this.

**Comment by viswanadham-k** [comment]
Hi @emmettd 

Can you please access the below link and configure the latest version of WVD Scaling tool it is recommended by Microsoft. This version have your issue fix.

https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script

Let us know if you are still facing any issues.

Thanks,

**Comment by ChristianMontoya** [comment]
As @viswanadham-k mentioned, please try the new script that uses logic apps and is fully described here in the public documentation: [Set up scaling script](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script).

Closing this out. Please create a new issue if scenario reproduces.
