### ISSUE TITLE
3-wvd-management-ux

### ISSUE THREAD

**Issue by chi-ltd** [Azure/RDS-Templates#272]
Hi

Trying to deploy the Mgt tool for our WVDs & Host Pool but failing with conflict error:
![logs](https://user-images.githubusercontent.com/43997657/69644239-4cd0a800-105c-11ea-92b7-64d6b39aaac5.jpg)

 "id": "/subscriptions/subscription/resourceGroups/RG/providers/Microsoft.Resources/deployments/Microsoft.Template/operations/15A1776F8605EDD0", "operationId": "15A1776F8605EDD0", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-11-26T14:43:35.9476998Z", "duration": "PT32.9874467S", "trackingId": "5c265b13-dc68-482f-838d-9fe51ae0f885", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'." } }, "targetResource": { "id": "/subscriptions/subscription/resourceGroups/RG/providers/Microsoft.Automation/automationAccounts/wvdsaas-autoAccount-rchhymr5i4d5y/jobs/037685b0-c7bf-5061-8f54-bda37e17d89d", "resourceType": "Microsoft.Automation/automationAccounts/jobs", "resourceName": "wvdsaas-autoAccount-rchhymr5i4d5y/037685b0-c7bf-5061-8f54-bda37e17d89d" } }}

Referecing: https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui#guidance-for-template-parameters
https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/wvd-management-ux

Added contributor permission to my account under subscriptions.  
Tried the service account i used to provision WVD.  Disabled MFA and conditional access.

Ideas?

**Comment by viswanadham-k** [comment]
Hi
I hope you are deployed "East US" region. You can't deploy the management tool in the East US region.
For your reference please walk through the below link
https://docs.microsoft.com/en-us/azure/virtual-desktop/troubleshoot-management-tool

Solution: Deploy the management tool in a different region. Redeploying the tool in a different region shouldn't affect user experience.

**Comment by chi-ltd** [comment]
My WVD resources are in the UK South region along with this template deployment.

**Comment by chi-ltd** [comment]
However, the template looks like it has changed somewhat and is now deploying UK South. 

What is meant by the 'Before you sign in and use the management tool, you'll need to provide consent for the new Azure Active Directory application that is associated with the management tool. By providing consent, you are allowing the management tool to make Windows Virtual Desktop management calls on behalf of the user who's signed into the tool.' section and screenshot?
https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui#guidance-for-template-parameters
