### ISSUE TITLE
Drain mode - 4-WVD-scaling-script

### ISSUE THREAD

**Issue by larshobiasen** [Azure/RDS-Templates#274]
Hi,

Has anyone found af solution for draining the servers (exept one) one hour before the script will shutdown some RDS servers - so we dont kick new users at off-peak hours

/Lars

**Comment by viswanadham-k** [comment]
Hi,
Apologies for the delay, we have started investigating on this issue, will update you with the changes ASAP.

**Comment by viswanadham-k** [comment]
Hi @larshobiasen 
Can you please access the below link and configure the latest version of WVD Scaling tool it is recommended by Microsoft. This version have your issue fix.

https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script

Let me know if you are still facing issues.

**Comment by ChristianMontoya** [comment]
As @viswanadham-k mentioned, please try the new script that uses logic apps and is fully described here in the public documentation: [Set up scaling script](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script).

Closing this out. Please create a new issue if scenario reproduces.
