### ISSUE TITLE
Update Existing WVD Hostpool existing host not deleted

### ISSUE THREAD

**Issue by Alle1291** [Azure/RDS-Templates#276]
Using the Update Existing Windows Virtual Desktop Hostpool temaplate, the deployment appears to be completed successfully in the Azure portal, but nothing actually happens to the host. 

I am running a host pool with a single host (Win 10 multi-session w/ Office from gallery). When this deployment is run, the existing host/nic/disk are not deleted; the existing host remains running, unchanged. 

It seems that the steps to delete the existing host are not working, but I am not sure what else to check to understand what is happening.

I am using a gallery image, and using service principal authentication.

**Comment by clittle1973** [comment]
I'm having the same issue with the template.  Hosts remain up and running, and no changes are made.  I am using CustomVHD version.  Thanks.

**Comment by clittle1973** [comment]
It appears it is only when I try to name the machines the exact same that this phenomenon occurs.  Script works great when I put session hosts with different prefix.

**Comment by viswanadham-k** [comment]
Hi Alle1291,
Reason: Service principal doesn't have access of azure subscription resources.
So you need to provide your azure subscription "Contributor" access to service principal (VM's running subscription) and try to re deploy again with update existing hostpool template.

@clittle1973  Thank you for your feedback..

**Comment by ChristianMontoya** [comment]
@clittle1973 : Yes, that's a requirement, that you use a unique rdshNamePrefix.

**Comment by ChristianMontoya** [comment]
@Alle1291 : Were you able to run this?

**Comment by lintFan** [comment]
Closing due to no response, feel free to re-open if needed.
