### ISSUE TITLE
PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: One or more errors occurred.

### ISSUE THREAD

**Issue by isehuetdk** [Azure/RDS-Templates#277]
We deploy personal host pool using an AD service account (not service principal), getting the below deployment issue when installing the DSC extension:

> "statusCode": "Conflict", 
> "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'dscextension'. Error message: \"DSC Configuration 'FirstSessionHost' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource failed to execute Set-TargetResource functionality with error message: One or more errors occurred. The SendConfigurationApply function did not succeed.\"." } ] } }

We are not deploying with the Marketplace UI, we are deploying using the ARM templates from the Github repo. We are using Username/Password and not Service Principal.

The Service Account does not have MFA enabled. 

We deleted all, provided the Service Account access to the Azure Resource Group and deployed from a PowerShell session with a Service Account context - did not resolve the issue.

The DSC extension is downloading all the artifacts to the machine successfully but cannot execute it. 
For troubleshooting reasons I tried to execute the script manually and it failed due to the ExecutionPolicy restriction. 
"Script-FirstRdshServer.ps1 cannot be loaded because running scripts is disabled on this system. "

When setting the Execution Policy to "Unrestricted", and redeploy the DSCExtension, the DSCConfigurationStatus is set to "Success", but the script still fails.

Digging more into the details, I can see in the DSC job logs that the RDInfra.RDPowershell module is loaded successfully, but as soon as that is done, the LCM ends with the error message **"PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: One or more errors occurred.**"

Debugging throught the Script-FirstRdshServer, it fails on line 102, Add-RdsAccount, "One or more errors occurred".

**Comment by isehuetdk** [comment]
@ChristianMontoya related to the WVD issue discussed earlier.

**Comment by msfreaks** [comment]
I'm getting this same error. Used the 1909 version of the image though..

**Comment by ChristianMontoya** [comment]
@isehuetdk , @msfreaks : Are you able to login to the Windows Virtual Desktop PowerShell manually with the Service Principal?

**Comment by isehuetdk** [comment]
Hi Christian,
We are not using Service Principal, we are using a Service Account (with MFA disabled). Checking the role of the Service Account (Get-RDSRoleAssignment), I am set as RDS Owner on both the Tenant level and the Session Host level. I can see that I'm not RDS Owner on the Tenant Group level. 

Just as a side note - the same error occurs as well when deploying the same through the Marketplace. We are just redeploying as we speak, I will keep you posted on the progress.

"code": "VMExtensionProvisioningError",
"message": "VM has reported a failure when processing extension 'dscextension'. Error message: \"DSC Configuration 'FirstSessionHost' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: One or more errors occurred.  The SendConfigurationApply function did not succeed.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "

**Comment by lintFan** [comment]
@isehuetdk  There were some changes made to the master branch of this repository on Jan 26, 2020 7:46 PM PT (in https://github.com/Azure/RDS-Templates/pull/308 ) that should improve the error messages around the this authentication in the case where it used to just say "One or more errors occurred." which is what your last message contains. These changes are not in the Azuure marketplace yet, so you will need to deploy from the this repository in order to get the improved error messages.

**Comment by isehuetdk** [comment]
Great, with the new solution the issue is resolved.
