### ISSUE TITLE
No results showing, task runs fine

### ISSUE THREAD

**Issue by EAanaya** [Azure/RDS-Templates#279]
We have configured the .JSON file as per the documentation, task as well and runs fine. However, we see no logs created nor VMs being scaled automatically.

**Comment by viswanadham-k** [comment]
Hi,
Apologies for the delay, we have started investigating on this issue, will update you with the changes ASAP.

**Comment by viswanadham-k** [comment]
Hi @EAanaya 
Can you please access the below link and configure the latest version of WVD Scaling tool it is recommended by Microsoft. 

https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script

Let us know if you are still facing any issues.

Thanks,

**Comment by ChristianMontoya** [comment]
As @viswanadham-k mentioned, please try the new script that uses logic apps and is fully described here in the public documentation: [Set up scaling script](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script).

Closing this out. Please create a new issue if scenario reproduces.
