### ISSUE TITLE
3-wvd-management-ux-WVD management tool deployment failed with error

### ISSUE THREAD

**Issue by jagdishbagul01** [Azure/RDS-Templates#286]
Deployment failed with below error:

{ "id": "/subscriptions//resourceGroups/vdi-rg-01/providers/Microsoft.Resources/deployments/Microsoft.Template/operations/71893879A1672D9F", "operationId": "71893879A1672D9F", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-12-08T12:25:51.9398126Z", "duration": "PT1M15.4403413S", "trackingId": "fc7140fe-46df-4487-802d-dd092998e519", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'." } }, "targetResource": { "id": "/subscriptions/ID/resourceGroups/vdi-rg-01/providers/Microsoft.Automation/automationAccounts/wvdsaas-autoAccount-r3p5dzft2jrvi/jobs/-56a7-8864-8d6e4c37e0e1", "resourceType": "Microsoft.Automation/automationAccounts/jobs", "resourceName": "wvdsaas-autoAccount-r3p5dzft2jrvi/-9281-56a7-8864-8d6e4c37e0e1" } }}
![Capture](https://user-images.githubusercontent.com/44702056/70389594-a3889b00-19e7-11ea-9e91-964975812052.JPG)

**Comment by Majormer** [comment]
Also seeing this issue, same spot.  I don't understand the conflict.

**Comment by viswanadham-k** [comment]
Hi,
Check if user is enabled with MFA then disable MFA and try to re deploy the management tool.

If still facing issues please access the below link for to trouble shoot.
https://docs.microsoft.com/en-us/azure/virtual-desktop/troubleshoot-management-tool

**Comment by ChristianMontoya** [comment]
@jagdishbagul01  , @Majormer : Are you both still having errors with this? Also, alternatively, we released documentation on how to deploy with PowerShell, if you primarily have admins who require MFA: https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershellhttps://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell

**Comment by Majormer** [comment]
@ChristianMontoya 

Yes.

In light of the many updates in the last couple months, I attempted to deploy again today with similar results.  All "real" users require MFA, but I created a Service Principal to work around this which does not have MFA.  I tried deploying with PowerShell today under the Service Principal, and it successfully deployed... but still did not provide a functioning web page.

Screenshot attached.

![WVDError](https://user-images.githubusercontent.com/7697997/73402721-853a6f80-42b3-11ea-9ee9-ac00eaebfafd.JPG)

**Comment by ChristianMontoya** [comment]
@Majormer : This is odd...usually this page happens if you run the ARM template, but then do not run the PowerShell script afterwards. Can you confirm that you ran the updateWvdMgmtUxApiUrl.ps1 ?

Otherwise, will need to defer to @viswanadham-k  to provide guidance.

**Comment by viswanadham-k** [comment]
Hi @Majormer 

Can you confirm that you ran the UpdateWvdMgmtUxApiUrl.ps1 script. 
If you ran the script please wait for 60 seconds, website will display the consent pop up then you need to authenticate the website.

 Please let me know if you are still facing issue.

Thanks,

**Comment by Majormer** [comment]
The UpdateWvdMgmtUxApiUrl.ps1 script is failing:

```
Get-AzRoleAssignment : Cannot find principal using the specified options
At C:\Repos\RDS-Templates\wvd-templates\wvd-management-ux\deploy\scripts\updateWvdMgmtUxApiUrl.ps1:75 char:19
+ $RoleAssignment = Get-AzRoleAssignment -SignInName $context.Account
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzRoleAssignment], KeyNotFoundException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand

Authenticated user should have the Owner/Contributor permissions
```

I have tried with the Service Principal that deployed literally everything else from PowerShell, and from an admin account that does happen to have MFA associated with it.  Got the error from both, but tried the Service Principal first.  I confirmed that the Service Principal is contributor to the subscription, so that appears to be right.  I can't figure out why it can't see the service principal with rights.

**Comment by viswanadham-k** [comment]
Hi @Majormer,

Please follow the below steps, to overcome the issue.
Step 1: Open the PowerShell in Administrator mode
Step 2: Execute the Login-AzAccount and it will ask the credentials provide the your azure admin credentials (MFA enabled User). Your admin credentials must be have subscription owner/contributor access.
Step 3: Then execute the "updateWvdMgmtUxApiUrl.ps1" PowerShell script.

Please let me know if you are still facing issue.

Thanks,

**Comment by ChristianMontoya** [comment]
@Majormer : Closing out for now. Please re-open if you need to.
