### ISSUE TITLE
NVSv3 as WVD host pool

### ISSUE THREAD

**Issue by genkiw** [Azure/RDS-Templates#289]
I would like to use NVSv3 Series VMs as WVD host pool.
Please add [Standard_NV12s_v3 / Standard_NV24s_v3 / Standard_NV48s_v3] to allowedSizes in createUiDefinition.json.

**Comment by lintFan** [comment]
@genkiw The createUiDefinition.json file is only used for the user interface shown when the create template is accessed from the Azure Marketplace. If you run the [Create template](https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool/) 
 yourself (for example by using the [New-AzResourceGroupDeployment ](https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azresourcegroupdeployment) command) you should be able to specify any VM size by specifying the rdshVmSize parameter.

@ChristianMontoya Do you see any problems with adding these new VM sizes to  createUiDefinition.json?

**Comment by ChristianMontoya** [comment]
@lintFan : We just also need to do our own testing to make sure it doesn't break. The createUi does some logic based on the SKU name, so we don't want to add it without testing.

**Comment by ChristianMontoya** [comment]
@genkiw : Can you upvote an item or create a new suggestion at our UserVoice forum: https://aka.ms/wvdfbk . Closing this item and marking as feature request.
