### ISSUE TITLE
Details about SessionThresholdPerCPU value in the Autoscaling script

### ISSUE THREAD

**Issue by fchambon** [Azure/RDS-Templates#290]
Hi,

It seems that the script takes into account the MaxSessionLimit value set at the load balancer mode level when checking the session host available capacity. For example, if I set the following values using a D2_v3 (so 2 vCPU):

- LoadBalancer Moder: DepthFirst
- MaxSessionLimit: 2
- SessionThresholdPerCPU: 1

When 2 users are logged in, the script should trigger the "start VM action" but it does not. Can you provide additional details about the "math" behind the scene with the SessionThreshHoldPerCPU value?

**Comment by viswanadham-k** [comment]
Hi,
Apologies for the delay, we have started investigating on this issue, will update you with the changes ASAP.

**Comment by viswanadham-k** [comment]
Hi @fchambon 
Can you please access the below link and configure the latest version of WVD Scaling tool it is recommended by Microsoft. This version have your issue fix.
https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script

Let me know if you are still facing issues.

Thanks,

**Comment by ChristianMontoya** [comment]
As @viswanadham-k mentioned, please try the new script that uses logic apps and is fully described here in the public documentation: [Set up scaling script](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script).

Closing this out. Please create a new issue if scenario reproduces.
