### ISSUE TITLE
Use Create and provision WVD host pool/mainTemplate.json to create wvd host pool.

### ISSUE THREAD

**Issue by lijun1234** [Azure/RDS-Templates#292]
The markdown explains which parameters can be ignored depend of the value of parameter Gallery.

Just wonder if there is a way to grey out "Vm Image Vhd Uri", "Rdsh Custom Image Source Name" and son and just leave "Rdsh Gallery Image SKU" valid when "Gallery" parameter is selected for "Rdsh Image Source"  value? 

Or didn't show any parameters related to VM image in the beginning.  Dynamically show the needed parameters according to the selection of "Rdsh Image Source". In the example above, only show "Rdsh Gallery Image SKU" if Gallery is selected for "Rdsh Image Source" .

Now sure if it is even doable or not. Hope someone can give an answer. 

Thank you.

**Comment by ChristianMontoya** [comment]
@lijun1234 : Unfortunately, when running ARM templates, there's no way to grey them out based on other options you select. I agree, it would be very useful. However, our Azure Marketplace offering does this, if you would like to deploy that way: https://docs.microsoft.com/en-us/azure/virtual-desktop/create-host-pools-azure-marketplace

**Comment by ChristianMontoya** [comment]
Closing out, since there's nothing we can do, though it is a great suggestion.
