### ISSUE TITLE
 basicScale.ps1 hanging when starting VMs

### ISSUE THREAD

**Issue by clittle1973** [Azure/RDS-Templates#295]
The script hangs when Starting VMs in the following lines using the switch -Id with variable $RoleInstance.ID : 778, 840, 1170

I changed the switch to -ResourceGroupName with variable $VmInfo.ResourceGroupName and the issue resolved. 

Thanks for all your work on WVD!

**Comment by viswanadham-k** [comment]
Hi,
We have started investigating on this issue, will update you with the changes ASAP.

**Comment by viswanadham-k** [comment]
Hi @clittle1973 
Can you please access the below link and configure the latest version of WVD Scaling tool it is recommended by Microsoft. This version have your issue fix.
https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script

Let me know if you are still facing issues.

Thanks,

**Comment by ChristianMontoya** [comment]
As @viswanadham-k mentioned, please try the new script that uses logic apps and is fully described here in the public documentation: [Set up scaling script](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script).

Closing this out. Please create a new issue if scenario reproduces.
