### ISSUE TITLE
Error when deployment the Mgt tool

### ISSUE THREAD

**Issue by mic1312** [Azure/RDS-Templates#296]
Hi,

We've tried multiple deployments.
User has subscription owner, WVD owner and excluded from MFA policy but errors remains: 

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    }
  ]
}

**Comment by viswanadham-k** [comment]
Hi,
Thank you for deploying the management tool, reason of this error: azure power shell cmdlets unable to authenticate azure with your user credentials. So can you please execute the below power shell script in your local machine to know about failure. Before executing PowerShell script ensure your local machine is installed AzureRm, AzureAD Modules if not please read and find the description of the PowerShell Script.

<#
.Description
A Sample PowerShell script to check the azure authentication with PowerShell automation.

Run this PowerShell Script in Administrator mode.
This script depends on 2 powershell modules: AzureRM and AzureAD to get them execute 2 following commands.
Use "-AllowClobber" parameter if you have more than one version of PS modules installed
PS C:>Install-Module AzureRM -AllowClobber
PS C:>Install-Module AzureAD -AllowClobber

.PARAMETER azureAdminCredentials
Required
Provide credentials which you are provided to ManagementUX template Deployment.

.PARAMETER SubscriptionID
Required
Provide SubscriptionID of where you are deployed ManagementUX Application.

#>
Param(
[Parameter(mandatory = $true)]
[PSCredential]$AzureAdminCredentials,
[Parameter(mandatory = $true)]
[string]$SubscriptionId
)

#Authenticating to azure
Add-AzureRmAccount -SubscriptionId $SubscriptionId -Credential $AzureAdminCredentials
Get-AzureRmWebApp

#Authenticating to Azure AD
Connect-AzureAD -Credential $AzureAdminCredentials
Get-AzureADServicePrincipal

Solution:
Create a User in your azure tenant and provide azure subscription "Contributor" access to him. Then again execute this powershell script. If successfully executed then deploy the management ux with this particular user.

**Comment by mic1312** [comment]
Thanks for the information. 
Indeed this morning we have tested with a new account with Contributor permissions and it worked.
It seems we had also a MFA Conditional Policy still active.

It works now so we haven't tested your script
