### ISSUE TITLE
4-WVD-scaling-script Cannot validate argument on parameter

### ISSUE THREAD

**Issue by Mr-Pepper** [Azure/RDS-Templates#298]
VM's will not shut down

1/7/2020 9:30:01 PM - [Info] Failed to stop Azure VM: EUS2-WVD-APP-0 with error: Cannot validate argument on parameter 'ResourceGroupName'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again..exception.message

**Comment by viswanadham-k** [comment]
Hi,
We have started investigating on this issue, will update you with the changes ASAP.

**Comment by Mr-Pepper** [comment]
To note; I am using the script from here https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/wvd-scaling-script as it allows the use of a Key Vault.

**Comment by JoostJansenMot10** [comment]
Can you verify the MSI (managed service identity) from the scaler computer account has the correct (virtual machine contributor) permissions in the resourcegroup of the VM EUS2-WVD-APP-0?

**Comment by Mr-Pepper** [comment]
Access control of the resource group was missing the scaler service principal as VMC Role. Must have missed a step somewhere or wasn't documented.
