### ISSUE TITLE
WVD Web UX Missing Host Pool

### ISSUE THREAD

**Issue by chrisg602** [Azure/RDS-Templates#301]
I have a second Host Pool configured as Persistent.  I used WVD Web UX to create the host pool but after creation it never appeared.  I see the pool when using powershell commands.  I can interact with it and add session hosts but it never shows up in the UX.  Is there a setting or permission I am missing that allows the UX to see the host pool?

**Comment by viswanadham-k** [comment]
Hi @chrisg602 
Thank you for validating the management ux tool. I hope if you are able get the hostpools through powershell, management ux tool also will display the same hostpools.

Thanks,

**Comment by chrisg602** [comment]
Correct.  I can manage all of the hostpools using Powershell.  The issue is that the UX is not displaying all of them.  only 1.  How do I get it to display the others?

**Comment by viswanadham-k** [comment]
HI @chrisg602 
I hope it is wvd role assignment issue. Might be you have given role assignment at hostpool level to your login user which is listed hostpool. 
Can you give "Contributor" role assignment at tenant level to your login user. Then it will display the all hostpools in management ux tool.

Please let me know if you are still facing issue.

Thanks,

**Comment by ChristianMontoya** [comment]
@chrisg602 : Closing this out for the time being. If you need to re-open, please do or tag me.
