### ISSUE TITLE
Deploy App from path - No start menu applications could be found in host pool that match alias

### ISSUE THREAD

**Issue by mic1312** [Azure/RDS-Templates#302]
Hello,

We encounter a new issue when trying to publish a remoteapp from path (not from start menu) :

No start menu applications could be found in host pool that match alias

The remoteapp was successfully published through Powershell

**Comment by mic1312** [comment]
Do you have news on this problem?

**Comment by ChristianMontoya** [comment]
@mic1312 : Are you attempting to publish the "RemoteApp from file path" through the PowerShell? Or through the management UX?

**Comment by mic1312** [comment]
We have the problem when we publish through Management UX
When we use Powershell, it works well

**Comment by ChristianMontoya** [comment]
@viswanadham-k: Can you please take a look?

**Comment by mic1312** [comment]
Here is the printscreen : 
![WVD-RemoteApps](https://user-images.githubusercontent.com/50583016/74219359-e8150900-4cac-11ea-8fea-b7650d16b558.png)

**Comment by viswanadham-k** [comment]
Sure @ChristianMontoya 

Hi @mic1312 
Team is working on this issue fix, will update you soon.

Thanks,

**Comment by viswanadham-k** [comment]
Hi @mic1312 
We have fixed issue and pushed changes to repository. Please update your management ux tool and validate the changes then let us know your feedback. 
I hope you got a notification to update management tool, click on notification **update** link and follow the steps to update the management tool.

If you are not get a notification, access below link and follow the steps to update your management tool.
https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/wvd-management-ux/deploy#update-msft-wvd-saas-ux-environment

Let us know if you are facing any issue.

Thanks,

**Comment by mic1312** [comment]
Hi,

thanks for the information, we will try it when it's possible because we have another problem with the management UX (managed in another ticket)

Regards

**Comment by ChristianMontoya** [comment]
Fixed by #347 .

Closing.
