### ISSUE TITLE
Variables declared twice in the createazurelogicapp.ps1 file

### ISSUE THREAD

**Issue by comnam90** [Azure/RDS-Templates#303]
The variables for `$RDBrokerURL` and `$ScriptRepoLocation` are declared twice in the createazurelogicapp.ps1 file in the template for WVD scaling.

Once at the beginning of the script here: https://github.com/Azure/RDS-Templates/blob/7c8443c0ab74f48292bb2ae71356241d0f4799ce/wvd-templates/wvd-scaling-script/wvdscaling-automation/createazurelogicapp.ps1#L151-L157
And again further down here: https://github.com/Azure/RDS-Templates/blob/7c8443c0ab74f48292bb2ae71356241d0f4799ce/wvd-templates/wvd-scaling-script/wvdscaling-automation/createazurelogicapp.ps1#L202-L208

**Comment by viswanadham-k** [comment]
Hi,
Thank you for validating the script, we will remove the duplicate variables and update changes.

**Comment by viswanadham-k** [comment]
Hi
Issue has been resolved could you please validate the script and close the issue.
https://github.com/Azure/RDS-Templates/blob/ptg-wvdautoscaling-automation/wvd-templates/wvd-scaling-script/wvdscaling-automation/createazurelogicapp.ps1

**Comment by ChristianMontoya** [comment]
@comnam90 : Closing the issue. Please re-open if it wasn't resolved.
