### ISSUE TITLE
3-wvd-management-ux no session host are displayed in website

### ISSUE THREAD

**Issue by brynsp** [Azure/RDS-Templates#306]
400 virtual machines deployed, agent installed, registered with key generated in wvd-management-ux website

`Get-RdsSessionHost` returns full list of servers

_however_

The web UI does not show any of the hosts for this particular host pool.

There isn't much to help me diagnose this issue from what I can determine.

**Comment by nshores** [comment]
Same issue here.

**Comment by brynen** [comment]
Same issue here.

**Comment by viswanadham-k** [comment]
Hi All,
Please follow the below steps to overcome the issue
Step1:
It seems management ux tool login user doesn't have subscription contributor access, so provide subscription contributor access to user then session hosts will be displayed.
Step2:
Check if the session hosts(Azure VMs) are existed in the same subscription which you are deployed management ux tool.

If you are still facing issues please let me know.

**Comment by nshores** [comment]
I can confirm the session hosts are in the same subscription. What's a easy way to confirm the permissions for the first step?

**Comment by viswanadham-k** [comment]
Hi,
Please go through the below link and follow the steps
https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal#add-a-role-assignment

let me know if you are still facing issues.

**Comment by nshores** [comment]
I can confirm the account used has the "owner" role on the root level of the subscription - should have all permissions needed.

**Comment by brynsp** [comment]
The management app service principal is granted the contributor role for the entire subscription.

The webapps (2) and app service plan (1) are in different resource groups, but in the same subscription as the virtual machine resources for the session hosts.

Still, I cannot enumerate them in the webUI, but `Get-RdsSessionHost` returns the complete list of machines

**Comment by viswanadham-k** [comment]
Hi @nshores and @brynsp,
 
Please let me know your availability time today 01-17-2020 between 7:00 PM-10:30 PM IST. Kindly ping me in Microsoft Teams: Viswanadham.kudapu@peopletech.com then will connect and assist you to resolve the issue.

Thanks & Regards,
Viswanadham K

**Comment by brynen** [comment]
Found that a pending reboot on the hosts was my problem. A quick reboot fixed my issue. No indication anywhere on this issue.

**Comment by nshores** [comment]
@viswanadham-k - I'm not able to reach you in teams.

**Comment by viswanadham-k** [comment]
Hi @nshores 

Please let me know your availability time today 01-21-2020 between 7:00 PM-10:30 PM IST and share your mailing address with us then we will send the meeting invitation.

Thanks,

**Comment by nshores** [comment]
I'm available. nick.shores@executech.com

**Comment by viswanadham-k** [comment]
> Found that a pending reboot on the hosts was my problem. A quick reboot fixed my issue. No indication anywhere on this issue.

Thank you @brynsp

**Comment by nshores** [comment]
@viswanadham-k  - I found the host pool machine. It is part of a scale set, that's why we were not seeing it before. Are hosts in scale sets supported?

**Comment by nshores** [comment]
#323 

I've opened a new issue here.

**Comment by ChristianMontoya** [comment]
@nshores , @viswanadham-k : Closing this thread and continuing the debugging of Scale Sets in the linked issue #323 .
