### ISSUE TITLE
Unable to deploy the management tool

### ISSUE THREAD

**Issue by sarahpotrick2573** [Azure/RDS-Templates#307]
Hello. I have been trying to deploy this template from a very long time but i am unable to do so. Its stating that Job id already exists. when i tried troubleshooting it is asking me to give a unique application name, i tried changing the name also but still showing the same error.
<img width="521" alt="web error" src="https://user-images.githubusercontent.com/59913958/72423206-e0e00580-37a9-11ea-9fee-b189de69eeac.png">

**Comment by viswanadham-k** [comment]
Hi,
Please run the deployment again, but use a new name as the Application Name. This is used for both the web app and the Azure AD registration, so it depends on a unique name.

If you are facing issue please let me know or ping me in teams (Viswanadham.kudapu@peopletech.com) then we will connect and assist you to resolve the issue..

**Comment by msvt37** [comment]
Running into the same issue deploying this tool.  
wvdsaas-autoAccount-7qhbfqm "Status" is listed as Conflict

**Comment by viswanadham-k** [comment]
Hi @msvt37 
I hope you are followed all steps which is documented (https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui) but failing deployment. Can you follow the troubleshooting steps which is documented by Microsoft "https://docs.microsoft.com/en-us/azure/virtual-desktop/troubleshoot-management-tool". 

If you are still facing issue after troubleshooting, please find below and follow the alternative way to deploy the Management UX tool through PowerShell.

Microsoft released documentation on how to deploy with PowerShell: https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell

Let me know if you are still facing issues.

Thanks,

**Comment by ChristianMontoya** [comment]
Closing for now. Please re-open if you have additional questions.
