### ISSUE TITLE
Terraform templates containing wrong path to Configuration.zip

### ISSUE THREAD

**Issue by TriXje** [Azure/RDS-Templates#312]
Old path on row 64 in variables.tf (at https://github.com/Azure/RDS-Templates/tree/master/wvd-sh/terraform-azurerm-windowsvirtualdeskto...

Old path:

https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool

New path:

https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates

**Comment by nakranimohit0** [comment]
@TriXje Thank you for raising this issue. We are working on fixing it here and few other places.
