### ISSUE TITLE
Unable to deploy using Service principal

### ISSUE THREAD

**Issue by kajencik** [Azure/RDS-Templates#313]
I'm trying to deploy the WVD management App into Azure AD tenant with enable MFA, so I cannot use the user and password as mentioned in the documentation:
https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui

Is it possible to deploy the application only when the service principal used has contributor permission on the resource group only,  but RDS owner permissions?

I have used the ARM template from portal to deploy the management app, with the service principal option set to true and provided the SP credentials.

I made sure the service principal/App registration has the needed API permissions and the redirect URL, I have also updated the API app reference using the provided powershell - updateWvdMgmtUxApiUrl.ps1 - however the app still seems not authenticating.

Is the deployment using service principal supported using the ARM template? Or I need to follow the powershell guide in the portal? - https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell

**Comment by jstabl** [comment]
I was able to get deployments working with ARM templates and SPN but the error comes from using old RDSPowershellModule. You need to update the modules found in DeployAgent\PowerShellModules to the latest RDS powershell modules 
 found here. https://www.powershellgallery.com/packages/Microsoft.RDInfra.RDPowershell/1.0.1534.2001

Download the nuget file and extract then replace files in the PowerShellModules directory and then rezip the configuration.zip.

**Comment by kajencik** [comment]
For me, there is no error as such, I think I have all the configuration in place as described in the powershell guide, but when the web app loads, it is not even trying to authenticate, like when the Azure AD app does not have the admin permissions granted.

Overall, I would like to also understand how the management app works, rather than just redeploying the solution again.

**Comment by kajencik** [comment]
So it turns out the management web application started to work after all, maybe I just did not wait long enough also for the API part to load.

It would be nice to be able to see some progress or an error when the connection to Azure/WVD service does not initialize.

I will probably try one more deployment from scratch to make sure it works.

**Comment by viswanadham-k** [comment]
Hi @kajencik,

Thank you for deploying the management tool using Service Principal. I hope you have deployed successfully but authentication is not happen. 
I have investigated and please check below reasons.

Reason:1:- After successful deployment, initial application loading will take some time (around 1 to 2 minute) then you will get consent and authentication pop-ups. So please check it once.
Reason:2:- Did you set the redirect URI? please follow the document link to set the redirect uri.
https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell#set-the-redirect-uri

Please let me know if you are still facing issue.

Thanks,

**Comment by kajencik** [comment]
Hello, thanks for the suggestions, I did retry the deployment using service principal and everything worked this time, seems like I just needed to wait a bit longer.
