### ISSUE TITLE
4-WVD-scaling-script Add peak days

### ISSUE THREAD

**Issue by JoostJansenMot10** [Azure/RDS-Templates#314]
Hi, 

I'm using the scaling script to scale the servers on peak hours. I've added a feature that also verifies the peak days next to the peak hours so it will scale down in the weekends as well. 

I put the scripts in the attachments

[basicScale-MSI.zip](https://github.com/Azure/RDS-Templates/files/4086171/basicScale-MSI.zip)

**Comment by viswanadham-k** [comment]
Hi @JoostJansenMot10,

Thank you for validating the script. I hope peakdays parameter is not required. Actually script will keep off-peak days minimum number of RDSH VMs(MinimumNoOfRDSH parameter) in running state. Reason in off-peak days some of the users will be connected.

Thanks,

**Comment by JoostJansenMot10** [comment]
Hi @viswanadham-k 

Peak day is a required parameter. When a day is not specified in the peak day parameter it will use the MinimumNoOfRDSH parameter to run a minimum of RDSH hosts for off-peak days. For example: peakday = Monday. This means that all the other days are off-peak and the script will run the MinimumNoOfRDSH.

**Comment by ChristianMontoya** [comment]
Adding @RoopChevuri to see if we would like to take changes requested here.

**Comment by jaycartel** [comment]
I hope that there is an optional Peakday added to the script at somepoint as this would be beneficial for the host pools that do not need to be running on weekends. An additional feature to be added would be for MinimumNoOfRDSH on OffPeak days that allows you to have 0 session hosts running where required.

**Comment by nakranimohit0** [comment]
Closing this out as a duplicate to #420
