### ISSUE TITLE
Microsoft.RDInfra.RDPowershell.dll module from /DSC/DeployAgent.zip does not work

### ISSUE THREAD

**Issue by Pidgegeddon** [Azure/RDS-Templates#315]
Hi!

The arm-template downloads multiple scripts and the Microsoft.RDInfra.RDPowershell module.
The scripts that automatically registers and sets up WVD from the host then imports the module directly from C:\DeployAgent\PowershellModules\Microsoft.RDInfra.RDPowershell.dll.
This version seems to break several cmdlets used later in the script.

As an example in RDS-Templates/wvd-templates/DSC/Script-AdditionalRdshServers.ps1 on 
line 113 `Get-RdsTenant -Name "$TenantName"` will always fail with error `Get-RdsTenant : User is not authorized to query the management service.`

The module version that the scripts uses is: 1.0.306.0
Latest version from PowerShell gallery is: 1.0.1534.2001

Testing with latest version from PowerShell gallery showed no errors running same command with same credentials.

**Comment by ChristianMontoya** [comment]
Adding @nakranimohit0 here as well, as he may be aware.

**Comment by nakranimohit0** [comment]
@Pidgegeddon 
I'm not able to reproduce this. Can you dump the parameters you are using to run this template. You can mask any private info.

**Comment by Pidgegeddon** [comment]
@nakranimohit0 
Reproducing steps I took:

### Sign in steps used both times with same account  
`$tenantId = "<TenantId>"`
`$AppId = "<AppId>"`
`$AppSecret = "<Secret>"`
`$creds = New-Object System.Management.Automation.PSCredential($AppId, (ConvertTo-SecureString $AppSecret -AsPlainText -Force))`
`Add-RdsAccount -DeploymentUrl "https://rdbroker.wvd.microsoft.com" -ServicePrincipal -TenantId $tenantId -Credential $creds `

## Local module that works
Locally I have a version of Microsoft.RDInfra.RDPowershell from the PS gallery
![image](https://user-images.githubusercontent.com/31764717/72986166-e19b1c00-3de7-11ea-899e-0236b55cb24a.png)
Sign in with steps above and then running `Get-RdsTenant`. Works both with and without `-Name` parameter.
![image](https://user-images.githubusercontent.com/31764717/72988237-2cb72e00-3dec-11ea-859e-916d9d268fc4.png)

## Module from RDS-Templates/wvd-templates/DSC/DeployAgent.zip that does not work
- Downloaded DeployAgent.zip from above path
- Extracted files
- Imported Module
![image](https://user-images.githubusercontent.com/31764717/72987916-9e42ac80-3deb-11ea-84ef-8ac6f2582d21.png)
- Same signin and same commands:
![image](https://user-images.githubusercontent.com/31764717/72988349-5ec89000-3dec-11ea-9525-be52a7ab6bc1.png)
![image](https://user-images.githubusercontent.com/31764717/72988473-9b948700-3dec-11ea-9350-9ff630850251.png)

## Sidenote
This have never been an issue in this tenant before.
Tried in another test tenant where I could not replicate this issue.

**Comment by nakranimohit0** [comment]
@Pidgegeddon  Still unable to repro it. One thing to double check is to make sure the RDS context is set with the correct tenant group name.
For example, for my test credentials, I get the err `User is not authorized to ...` the first time I run `get-rdstenant` after `add-rdsaccount`. However this is because by default the tenant group name is `Default Tenant Group`. Since my test tenant is in diff tenant group, I ran the `Set-RdsContext -TenantGroupName $tenant_group`. Then `get-rdstenant` runs successful.

This is true for modules from both sources (gallery and deployagent)
Since you were not able to repro this issue on another test tenant, maybe try comparing configurations/details for both tenants ?

Also are you able to repro with any other versions from gallery ? https://www.powershellgallery.com/packages/Microsoft.RDInfra.RDPowershell/

@ChristianMontoya  Do we have any documentation on what this error is about: `Get-RdsTenant : WVD_50002:  not found`

**Comment by Pidgegeddon** [comment]
@nakranimohit0 
`Set-RdsContext -TenantGroupName $tenant_group` does not work in the module with errors.
![image](https://user-images.githubusercontent.com/31764717/73053213-6be68d00-3e87-11ea-9878-472c5c7b7c0a.png)
Same line works works on local module
![image](https://user-images.githubusercontent.com/31764717/73053560-57ef5b00-3e88-11ea-9f22-4cd960cf1bc4.png)
Using `Get-RdsTenantGroup` gave the same `WVD_50002: not found`

Noticed another fault when checking for differences in working tenant and tenant with errors. Module with error:
![image](https://user-images.githubusercontent.com/31764717/73058527-1f557e80-3e94-11ea-80ce-2a25fc13608b.png)
Local module:
![image](https://user-images.githubusercontent.com/31764717/73058680-63e11a00-3e94-11ea-8db4-04e729a43ecb.png)
The tenant that works did not have the same issue.

I have tried to compare the two tenants but have so far not found any differences. Both service accounts are RDS Owner. There is nothing else I could find that should affect this kind of access. If you have a theory of what could affect this I can check specific settings.

Other versions:
 - 1.0.1.7 - Got an error trying to download. skipped check
 - 1.0.1.11 - Same errors as with 1.0.306
 - 1.0.833 - Same errors
 - 1.0.1288.1 - No errors
 - 1.0.1534.2001 - No errors
The `WVD_50002` appeared in both older versions with errors

**Comment by ChristianMontoya** [comment]
@nakranimohit0  @Pidgegeddon : I have not seen this WVD_50002 error before. As a side note, we are planning on updating the PowerShell version in the DSC module which maybe should help.

If we update it, are you able to grab the bits from that one?

**Comment by Pidgegeddon** [comment]
@nakranimohit0 @ChristianMontoya Script works now with updated module. Thank you for your help.
