### ISSUE TITLE
Update Existing Hostpool - Not deleting previous VM's

### ISSUE THREAD

**Issue by Misterjohnson87** [Azure/RDS-Templates#316]
Good Afternoon,

When running the ARM template to update an existing hostpool the process completes fine but unfortunately any previous VM's are not deleted. I cannot see any errors for this.

I have confirmed the Service Principal has the contributor access to our subscription when the WVD Tenant and Hostpool are.

We are also doing this as part of an Azure release using the "Azure resource group deployment" task. With the "Action" option set to: "Create or update resource group" and Deployment mode set to "Complete"

Any help would be appreciated 

Many Thanks

**Comment by nakranimohit0** [comment]
@Misterjohnson87 
Is this about WVD ARM templates using https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Update%20existing%20WVD%20host%20pool ?

**Comment by Misterjohnson87** [comment]
That's correct. Thanks

**Comment by nakranimohit0** [comment]
@Misterjohnson87 
have you tried troubleshooting using this guide: https://docs.microsoft.com/en-us/azure/virtual-desktop/troubleshoot-vm-configuration ?
Can you check the log file C:\Windows\Temp\ScriptLog.log inside the 0th VM ending with "prefix-0" ?

**Comment by Misterjohnson87** [comment]
The last line of the log file is MSFT_ScriptResource:137 - Old session host servers (if any) in host pool xxxx then nothing else.

**Comment by nakranimohit0** [comment]
@Misterjohnson87 
That indicates that the host pool doesn't contain any old VMs meaning that old VMs (if any) were successfully removed from the host pool and were either deleted/deallocated. What action are you performing on the old VMs ? https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/Update%20existing%20WVD%20host%20pool/mainTemplate.json#L234

Also please note that action parameter is case sensitive
Do you see any logs that say "Successfully removed VM from Azure" or "VM has been stopped" ?
Are you sure the old VM name is different from the new VM name specified by the update template ?
Can you also specify what was the state of the host pool before running update template and after ?

**Comment by Misterjohnson87** [comment]
We are using the delete action on old machines.
When using Azure pipelines the parameter is selected from a drop down so the case is correct. 

I cannot see any logs to indicate that a vm has been stopped or removed. 

We are using the same vm host name on the "replacement" machines as the old existing vms 

Thanks

**Comment by nakranimohit0** [comment]
@Misterjohnson87 
For update template you have to use a different VM host name. Running it with same name will do nothing. The script identifies old VMs by filtering the list of registered session hosts whose host name is not equal to host name specified in the update template.

**Comment by Misterjohnson87** [comment]
Ah ok thanks. 

Will there be any way to keep the same host names in the future? Having multiple hostnames joined to the domain is going to end up making a mess in active directory

We were hoping that we could keep the same hostnames and just the vms would recreate themselves everytime we have a new image release.

Thanks

**Comment by nakranimohit0** [comment]
@ChristianMontoya might be able to answer that.

**Comment by ChristianMontoya** [comment]
@Misterjohnson87 : Not sure, since there would have to be multiple, larger logic changes to support this. A couple of questions...if we were able to re-use the VM name...:

1. Would you be okay with down-time, if we have to delete all of the VMs first, then create the new ones?
2. If we delete and replace one-by-one, how much time would be acceptable per VM?
3. Would you also expect an option to **not delete** in case you want to test the image in the host pool first?

**Comment by Misterjohnson87** [comment]
@ChristianMontoya - Thanks for your response. Let me check with the team internally here on what would be expected by them and I'll let you know.

Thanks

**Comment by jstabl** [comment]
@ChristianMontoya - Adding my option to your question because I have the same thought that vm names should be allowed to be the same. 

1. Yes, I think this would be a maintenance window operation. Or better yet have two host pools and while one is down for updating users can use the other pool.

2. If delete is the option then I would go ahead and delete and remove from the domain without a time delay

3. yes, I think there should be a deallocate or delete option just in case

**Comment by jstabl** [comment]
I believe the logic in the Test script is wrong.  Below is what currently exist in the repo. Shouldn't the if statement return true if there are old session hosts?

if ($OldSessionHosts) {
    Write-Log -Error "Old Session Hosts exist in hostpool $HostPoolName"
    return $false
}

return $true

**Comment by ChristianMontoya** [comment]
@jstabl : No, the logic should be left as-is, since the operation only **truly** completed once we know that all of the previous session hosts have been removed.

**Comment by ChristianMontoya** [comment]
Closing this for now. Adding tags to mark feature feedback.
