### ISSUE TITLE
Terraform template question

### ISSUE THREAD

**Issue by TriXje** [Azure/RDS-Templates#318]
Have spent a lot of time on the Terraform template which is almost complete.
One question, in the variables.tf there are the following entries:

variable "tenant_app_id" {
  description = "ID of the tenant app"
  default=""
}
variable "tenant_app_password" {
  description = "Password of the tenant app"
default=""
}

tenant app ID should be the WVD application ID, is that correct?
The tenant app pw, where do I find this? Can't seem to find anything in other procedures which mentions the app password. Is this related to the service principal account?

Thank you in advance!

Br,

**Comment by Misterjohnson87** [comment]
It would be the app ID and password of the service principal you have created for WVD and given it RDS Owner permissions. This here will help you out:

https://docs.microsoft.com/en-us/azure/virtual-desktop/create-service-principal-role-powershell

**Comment by ChristianMontoya** [comment]
@TriXje : Confirming what @Misterjohnson87 suggested. I'm going to close this, but feel free to re-open.
