### ISSUE TITLE
Update existing Hostpool with Service Principal failing

### ISSUE THREAD

**Issue by robinhobo** [Azure/RDS-Templates#321]
When running this script to update an existing WVD hostpool and use Service Principal, it's failing. If I provision a new WVD Hostpool, and also use the same Service Principal it goes without any problems. 

Any help is appreciated, thanks!

**RAW Error:**

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'dscextension'. Error message: \\\"DSC Configuration 'RegisterSessionHostAndCleanup' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant.  The SendConfigurationApply function did not succeed.\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"
    }
  ]
}

**Status Message (on dscextension) **

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "VMExtensionProvisioningError",
                "message": "VM has reported a failure when processing extension 'dscextension'. Error message: \"DSC Configuration 'RegisterSessionHostAndCleanup' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant.  The SendConfigurationApply function did not succeed.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "
            }
        ]
    }
}

**Comment by robinhobo** [comment]
#2-Update-existing-WVD-host-pool

**Comment by robinhobo** [comment]
Don't see an option to add a label to this issue..

**Comment by jstabl** [comment]
I was able to get deployments working with ARM templates and SPN but the error comes from using old RDSPowershellModule. You need to update the modules found in DeployAgent\PowerShellModules to the latest RDS powershell modules
found here. https://www.powershellgallery.com/packages/Microsoft.RDInfra.RDPowershell/1.0.1534.2001

Download the nuget file and extract then replace files in the PowerShellModules directory and then rezip the configuration.zip.

**Comment by nakranimohit0** [comment]
Seems similar to the issue: #238

**Comment by lintFan** [comment]
@robinhobo There were some changes made to the master branch of this repository on Jan 26, 2020 7:46 PM PT (in #308 ) which updates the version of the [WVD Powershell](https://docs.microsoft.com/en-us/powershell/windows-virtual-desktop/overview) module it uses to the latest version 1.0.1534.2001 which has some fixes around service principles and also adds support for a standard single-tenant service principal, so it may be worth trying the deployment again. You will need to deploy from this repository in order to use the ARM Template with these changes because they aren't in the Azure marketplace yet.

**Comment by Digiroka** [comment]
same issue as mine, been logged a couple of months...
https://github.com/Azure/RDS-Templates/issues/259

**Comment by robinhobo** [comment]
@lintFan Thanks for your replay, just did a new test but unfortunate, the problem still exist.

**Comment by alaurie** [comment]
Still having this issue, tried with Service Principal.

**Comment by nakranimohit0** [comment]
@robinhobo  can you please share the script log located in the VM @ C:\Windows\Temp\ScriptLog.log ?
You can mask/clear any sensitive info from the log file, but please share the log for the first VM-0 created by the [create template](https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool) and the last NEW-VM-n created by the [update template](https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Update%20existing%20WVD%20host%20pool) ?

Also please share the parameters used for both templates create & update.

**Comment by robinhobo** [comment]
Hi @nakranimohit0,

Yes of course, I have created a new test host pool (with the create template) and updated the host pool with 4 new session host servers via the "update template". Attached are two zip files with the logs and some screenshots.

Please let me know if you need anything else. Many thanks in advance!


[Update-Logs.zip](https://github.com/Azure/RDS-Templates/files/4354599/Update-Logs.zip)
[Create-Logs.zip](https://github.com/Azure/RDS-Templates/files/4354600/Create-Logs.zip)

**Comment by nakranimohit0** [comment]
@robinhobo 

Thank you sharing the information, just by looking at the screenshots, I can pin point the issue
Please see my comments from this issue thread. https://github.com/Azure/RDS-Templates/issues/223#issuecomment-601153150

**Comment by nakranimohit0** [comment]
Thank you sharing the information.

Something doesn't seem consistent between the screenshots and logs. 'Rdsh Name Prefix' param is same for both create and update templates. Please see my comments from this issue thread: https://github.com/Azure/RDS-Templates/issues/223#issuecomment-601153150 as well as this one https://github.com/Azure/RDS-Templates/issues/223#issuecomment-601165379

But the VM names are created with a different prefix 'WVD-TEST2'. Please re run the tests on a completely clean resource group

**Comment by nakranimohit0** [comment]
@robinhobo 
I think you may have changed the 'Rdsh Name Prefix' after you took the screenshot.

Anyways, after looking at the logs, I think its failing at the line https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/DSC/Script-CleanupOldRdshSessionHosts.ps1#L126
I think this is related to not having the right permission to authenticate with Azure resource manager to be able to delete/deallocate old VMs. This is unrelated to WVD authentication.

Can you try to run the following command in powershell with the same credentials & AAD tenant ID used for WVD ? It will probably fail as you might need to give this service principle appropriate access to Azure Resource manager account. @ChristianMontoya may be able to help here.

Add-AzureRmAccount -Credential $TenantAdminCredentials -ServicePrincipal -TenantId $AadTenantId

**Comment by nakranimohit0** [comment]
@robinhobo 

This may also help: https://stackoverflow.com/questions/40498446/azure-invalid-accesstoken which refers to https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#assign-application-to-role

**Comment by robinhobo** [comment]
@nakranimohit0 

Will run the update template again, but with a new Resource Group for the new VM's.
The Service Principal is created with the following scripts (under account with WVD Tenant Owner rights)

> Install-Module AzureAD
> Import-Module AzureAD
> $aadContext = Connect-AzureAD
> $svcPrincipal = New-AzureADApplication -AvailableToOtherTenants $true -DisplayName "Windows Virtual Desktop Svc Principal"
> $svcPrincipalCreds = New-AzureADApplicationPasswordCredential -ObjectId $svcPrincipal.ObjectId
> 
> $svcPrincipal.AppId
> $svcPrincipalCreds.Value
> 
> Add-RdsAccount -DeploymentUrl "https://rdbroker.wvd.microsoft.com"
> $myTenantName = "hobo.cloud"
> 
> New-RdsRoleAssignment -RoleDefinitionName "RDS Owner" -ApplicationId $svcPrincipal.AppId -TenantName $myTenantName

I will run you command and come back with the outcome.

Thanks!

**Comment by nakranimohit0** [comment]
@robinhobo 

Again, I don't think there is any issue with service principle with WVD, but rather an issue with service principle with Azure RM account. This may also help: https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-authenticate-service-principal-powershell#create-service-principal-with-certificate-from-certificate-authority

**Comment by robinhobo** [comment]
Thanks @nakranimohit0, @ChristianMontoya and the rest of the team for your support! I have created a step-by-step blog for the solution : https://www.robinhobo.com/how-to-create-an-azure-service-principal-for-use-with-windows-virtual-desktop-and-azure-arm-templates-like-the-arm-template-to-update-an-existing-windows-virtual-desktop-hostpool/

**Comment by nakranimohit0** [comment]
The resolution is to assign the service principal with a "Contributor" role to the Azure subscription
