### ISSUE TITLE
Script-FirstRdshServer.ps1 - Hostpool name is not present in ScriptLog file

### ISSUE THREAD

**Issue by ManuPerezSan** [Azure/RDS-Templates#322]
Hi all,

I found that logfile is not saving host pool name. It may seem silly thing but it's important to see in the tacking process.

![image](https://user-images.githubusercontent.com/23212171/72990029-b7e5f300-3def-11ea-8fb7-8d2538cb4a4a.png)

Line 167 show be:
$HName = $HostPool.HostPoolName | Out-String -Stream
HostPoolName or other attribute

Instead of:
$HName = $HostPool.Name | Out-String -Stream

Regards

**Comment by nakranimohit0** [comment]
@ManuPerezSan  Thanks for catching this
