### ISSUE TITLE
Problems template MSFT-WVD-SAAS-UX Environment

### ISSUE THREAD

**Issue by camilo271** [Azure/RDS-Templates#325]
Good day,

We are using the implementation of MSFT-WVD-SAAS-UX Environment to configure the administration interface for the azure Windows virtual desktop service, but we have been experiencing problems when deploying resources generating problems when authenticating in the service of wvd, we already validate with Microsoft if this may be a problem with the platform, but it is evident that it performs the deployment but suggests verifying with the development if there is no problem with the code of this template.

https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/wvd-management-ux/deploy

I appreciate your help,

Cordially Camilo s.

**Comment by viswanadham-k** [comment]
Hi @camilo271 
Thank you for trying to deploy management UX tool, i hope you are facing issue with template deployment. Please follow the below steps to troubleshoot the issue.

Step 1:
Follow the below link for to troubleshoot the Management UX tool issues.
https://docs.microsoft.com/en-us/azure/virtual-desktop/troubleshoot-management-tool

Step 2:
Azure power shell cmdlets unable to authenticate azure with your user credentials. So can you please execute the below power shell script in your local machine to know about failure. Before executing PowerShell script ensure your local machine is installed Az, AzureAD Modules if not please read and find the description of the PowerShell Script.

<#
.Description
A Sample PowerShell script to check the azure authentication with PowerShell automation.

Run this PowerShell Script in Administrator mode.
This script depends on 2 powershell modules: Az and AzureAD to get them execute 2 following commands.
Use "-AllowClobber" parameter if you have more than one version of PS modules installed
PS C:>Install-Module Az -AllowClobber
PS C:>Install-Module AzureAD -AllowClobber

.PARAMETER azureAdminCredentials
Required
Provide credentials which you are provided to ManagementUX template Deployment.

.PARAMETER SubscriptionID
Required
Provide SubscriptionID of where you are deployed ManagementUX Application.

#>
Param(
[Parameter(mandatory = $true)]
[PSCredential]$AzureAdminCredentials,
[Parameter(mandatory = $true)]
[string]$SubscriptionId
)

#Authenticating to azure
Add-AzAccount -SubscriptionId $SubscriptionId -Credential $AzureAdminCredentials
Get-AzWebApp

#Authenticating to Azure AD
Connect-AzureAD -Credential $AzureAdminCredentials
Get-AzureADServicePrincipal

Solution:
Script execution time if you get authentication error then create a user in your azure active directory and provide azure subscription "Contributor" access to him. Then again execute this powershell script. If successfully executed then deploy the management ux with this particular user.

Thanks,

**Comment by camilo271** [comment]
Good day Github support.


We already validate the issues sent in the mail queue, but we see that the main problem is that we who internally police us to have MFA in all accounts of our organization, so I would like to know if there is any possibility of implementing this interface using accounts with active MFA.

I remain attentive to any comment,

Cordially,

[cid:image009.jpg@01D48E24.58314DA0][cid:image003.png@01D28CE5.454C8D90]
Camilo Andres Sanchez Gomez
Consultor Junior-SharePoint & Cloud
3123918760 –(57)(1) 744 29 67 Ext: 139
camilos@bextsa.com<mailto:camilos@bextsa.com>
www.bext.com.co<http://www.bext.com.co/>
Calle 56 # 7-85 Of. 302
Bogotá, Colombia.

**Comment by viswanadham-k** [comment]
Hi @camilo271 
Please follow the below approach, can able to deploy the management tool with MFA enabled user.
Microsoft released documentation on how to deploy with PowerShell, if you primarily have admins who require MFA: https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell

Let me know if you are still facing issues.

Thanks,

**Comment by camilo271** [comment]
Good Day support Github,

I did all the steps described in the documentation but it generates the following problem at the code level, I don't know what else it could be. I appreciate your help.

[cid:image001.png@01D5D775.7BA209A0]

Cordially,

[cid:image009.jpg@01D48E24.58314DA0][cid:image003.png@01D28CE5.454C8D90]
Camilo Andres Sanchez Gomez
Consultor Junior-SharePoint & Cloud
3123918760 –(57)(1) 744 29 67 Ext: 139
camilos@bextsa.com<mailto:camilos@bextsa.com>
www.bext.com.co<http://www.bext.com.co/>
Calle 56 # 7-85 Of. 302
Bogotá, Colombia.

**Comment by viswanadham-k** [comment]
Hi @camilo271 
I am sorry, unable to see your attached screenshot for your reference please find the below screenshot

![image](https://user-images.githubusercontent.com/54656839/73549825-6382e900-4469-11ea-9362-ade8d05a62a0.png)


Can you please drag and drop the your screenshot or copy and paste the screenshot in github comment section.

Thanks,

**Comment by ChristianMontoya** [comment]
@camilo271 : Closing this for now, but please re-open if you still need assistance getting this deployed.
