### ISSUE TITLE
3-wvd-management-ux / No Hosts displayed

### ISSUE THREAD

**Issue by maleroyfr** [Azure/RDS-Templates#326]
Hello,

Deployed the solution from Azure Marketplace for 300 users, (custom image syspreped)
I can list the hosts in Posh and users connect to VM but I can't see any the hosts the management ux.
Please advise, thank you,

Mathieu

**Comment by nshores** [comment]
Are you using scale sets? See --

#323

**Comment by maleroyfr** [comment]
No...

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by viswanadham-k** [comment]
Hi @maleroyfr ,
I hope your session host name and Azure VM name is miss matched, so hosts are not displayed in management ux tool. Please check and rename the the session host name with Azure VM name for your reference find the below example.
Example : 
SessionHost Name: Rdsh-01.contosowvd.com
AzureVM Name: Rdsh-01

Thanks,

**Comment by maleroyfr** [comment]
![image](https://user-images.githubusercontent.com/44583334/73251159-b3875480-41b8-11ea-949c-d07d46bc62d8.png)

**Comment by viswanadham-k** [comment]
Hi @maleroyfr 
Can you please execute a below powershell script in your environment and share with us output of the script.
<#
.Description
A Sample PowerShell script to list the session hosts of hostpool
Run this PowerShell Script in Administrator mode.
This script depends on "Microsoft.RDInfra.RDPowershell" to get them execute following command.
Use "-AllowClobber" parameter if you have more than one version of PS modules installed
PS C:>Install-Module "Microsoft.RDInfra.RDPowershell" -AllowClobber
#>
$TenantName = "Provide your WVD Tenant Name"
$HostpoolName = "Provide your Hostpool Name"
Add-RDSAccount -DeploymentURL "https://rdbroker.wvd.microsoft.com"
Get-RDSSessionHost -TenantName $TenantName -Hostpoolname $HostpoolName

**Comment by maleroyfr** [comment]
![image](https://user-images.githubusercontent.com/44583334/73253112-2d6d0d00-41bc-11ea-83ec-eb351d0af12a.png)

**Comment by viswanadham-k** [comment]
Thank you @maleroyfr 
I hope your AzureVM's are sitting in one subscription and management ux tool deployed in another subscription. So please check your azure subscription. Both should be in the same subscription then only it will display the sessionhosts in management ux tool.

**Comment by maleroyfr** [comment]
Hello, everything is in the same RG & same subscription, user logged in UX is RDS OWNER & contributor

**Comment by viswanadham-k** [comment]
Hi @maleroyfr,
Can we have a short call to discuss and resolve the issue. Please let me know your availability time today in between 4:30 PM to 7:00 PM IST and share with us your mailing address then i will send out the meeting invitation.

Thanks,

**Comment by maleroyfr** [comment]
Feel free to reach me on Teams mathieu.leroy AT infeeny DOT com

**Comment by vinceHH** [comment]
> Hi @maleroyfr ,
> I hope your session host name and Azure VM name is miss matched, so hosts are not displayed in management ux tool. Please check and rename the session host name with Azure VM name for your reference find the below example.
> Example :
> SessionHost Name: Rdsh-01.contosowvd.com
> AzureVM Name: Rdsh-01
> 
> Thanks,

I have the same issue and for me, it's related to your comment, session host name and Azure VM name is missmatched.
I do not have the possibility to rename the session host name (due to internal namming convention). In the other hand, when I deploy a new VM within the portal (provision a new host pool) the portal force the use of suffix ... so, I have to rename the session host name after deployment.
it's a shame to have this constraint to have the same name for the session host name and the VM name ?? 

regards

**Comment by ChristianMontoya** [comment]
@vinceHH : I'll mark this as a bug that we track to see if we will make changes. Otherwise, closing now.
