### ISSUE TITLE
Deployment fails in azure

### ISSUE THREAD

**Issue by mycoward** [Azure/RDS-Templates#327]
After entering all info the deployment fails with this error

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n }\r\n}"}]}

![MicrosoftTeams-image](https://user-images.githubusercontent.com/49570259/73184289-32fa2280-40ea-11ea-9a5c-e9f8a8e9842a.png)

**Comment by viswanadham-k** [comment]
Hi @mycoward 

Thank you for deploying the management tool, 
Please find the below steps to overcome the issue.

Step 1:
Follow below link for to troubleshoot the Management UX tool.
https://docs.microsoft.com/en-us/azure/virtual-desktop/troubleshoot-management-tool

Step 2:
Azure power shell cmdlets unable to authenticate azure with your user credentials. So can you please execute the below power shell script in your local machine to know about failure. Before executing PowerShell script ensure your local machine is installed Az, AzureAD Modules if not please read and find the description of the PowerShell Script.

<#
.Description
A Sample PowerShell script to check the azure authentication with PowerShell automation.

Run this PowerShell Script in Administrator mode.
This script depends on 2 powershell modules: Az and AzureAD to get them execute 2 following commands.
Use "-AllowClobber" parameter if you have more than one version of PS modules installed
PS C:>Install-Module Az -AllowClobber
PS C:>Install-Module AzureAD -AllowClobber

.PARAMETER azureAdminCredentials
Required
Provide credentials which you are provided to ManagementUX template Deployment.

.PARAMETER SubscriptionID
Required
Provide SubscriptionID of where you are deployed ManagementUX Application.

#>
Param(
[Parameter(mandatory = $true)]
[PSCredential]$AzureAdminCredentials,
[Parameter(mandatory = $true)]
[string]$SubscriptionId
)

#Authenticating to azure
Add-AzAccount -SubscriptionId $SubscriptionId -Credential $AzureAdminCredentials
Get-AzWebApp

#Authenticating to Azure AD
Connect-AzureAD -Credential $AzureAdminCredentials
Get-AzureADServicePrincipal

Solution:
Create a User in your azure tenant and provide azure subscription "Contributor" access to him. Then again execute this powershell script. If successfully executed then deploy the management ux with this particular user.

**Comment by mycoward** [comment]
Try the solution create completely new user and provided access required.  I have also run the above script and no errors reported.

Rerunning the deployment still fails.

**Comment by mycoward** [comment]
seems to fail on this step.
/subscriptions/4a513783-c113-43da-8828-995b4b86d217/resourceGroups/rcm-aze-g-rg-vm/providers/Microsoft.Resources/deployments/Microsoft.Template/operations/51FEF34520C08B0C

**Comment by viswanadham-k** [comment]
Hi @mycoward 
Thank for executing the script and you have created a user and given contributor access. But rerunning deployment still fails. I hope you are followed all steps which is documented(https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui) but failing deployment. 

Please find below and follow the alternative way to deploy the Management UX tool through PowerShell.

Microsoft released documentation on how to deploy with PowerShell: https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell

Let me know if you are still facing issues.

Thanks,

**Comment by ChristianMontoya** [comment]
@mycoward : Are you able to deploy through the PowerShell method that @viswanadham-k  linked? 

https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell

**Comment by ChristianMontoya** [comment]
Closing for now. Please re-open if you have additional questions.

**Comment by palphonso** [comment]
I have the same issue. Unable to deploy using the Azure Resource Manager.
