### ISSUE TITLE
Update existing WVD host pool mainTemplate.json - Error invalid json

### ISSUE THREAD

**Issue by ManuPerezSan** [Azure/RDS-Templates#330]
When try to parse json content from "https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/Update%20existing%20WVD%20host%20pool/mainTemplate.json", you receive an error of format.
![image](https://user-images.githubusercontent.com/23212171/73259312-cd7c6380-41c7-11ea-9dc5-911a7f75b2fc.png)

But if you use "https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool/mainTemplate.json" to create host pool it's runs well.

![image](https://user-images.githubusercontent.com/23212171/73259418-13d1c280-41c8-11ea-8cf2-958eed2c458f.png)

I see that this file was updated yesterday with this commit https://github.com/Azure/RDS-Templates/commit/1a52f771a7721108aa2cab7da86686350ad3cf8e.  Is it an error of mine or a file format problem?

Regards ;)

**Comment by nakranimohit0** [comment]
@ManuPerezSan 
Thank you for raising this issue. It was a file format that was causing this

**Comment by nakranimohit0** [comment]
It appears that `Invoke-WebRequest` may be adding few extra encoding bytes before the raw content which would duplicate with the bytes that the raw content already has
