### ISSUE TITLE
Cannot update the management app

### ISSUE THREAD

**Issue by Vinisz** [Azure/RDS-Templates#331]
When trying to update the management app, I get the error:

The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quot
ation marks ("&") to pass it as part of a string

in Powershell

**Comment by viswanadham-k** [comment]
Hi @Vinisz 
I am unable to trace your issue, can you please elaborate and share screenshot.

Thanks,

**Comment by Vinisz** [comment]
![image](https://user-images.githubusercontent.com/49644964/73452130-83cb7e80-4369-11ea-9bc0-392a85361594.png)

**Comment by Vinisz** [comment]
![image](https://user-images.githubusercontent.com/49644964/73452250-c8efb080-4369-11ea-8ccb-b530e22db1dd.png)

Here you go

**Comment by viswanadham-k** [comment]
Hi @Vinisz 

Can you please open the PowerShell Console with administrator mode and run the below cmdlets.

Set-location "C:\Users\Szabang_V\Downloads"

.\updateWvdMgmtUxApiUrl.ps1 -AppName "Provide name of the App"  -SubscriptionID "Provide your subscription id"

Please let me know if you are still facing issue.

Thanks,
