### ISSUE TITLE
wvd-templates/nestedtemplates is missing from master

### ISSUE THREAD

**Issue by Monual** [Azure/RDS-Templates#338]
WVD Host Pool deploys were working consistently up until yesterday afternoon, when they started failing with:

New-AzResourceGroupDeployment : 8:16:55 AM - Error: Code=InvalidContentLink; Message=Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/nestedtemplates/managedDisks-customimagevm.json'

That URL does appear to be not accessible.  Did the pathing change?

**Comment by Monual** [comment]
wvd-templates/nestedtemplates appears to have vanished in the latest commit.

**Comment by Monual** [comment]
Never mind.  Turns out I only needed get the latest Maintemplate.json file from master and it all started working.  My fault for not cloning the repo locally and using that as the source for _artifactslocation.

Leaving this here so others can learn from my error.

**Comment by nakranimohit0** [comment]
@ChristianMontoya I think we need to restore the nested templates for backwards compatibility especially for Marketplace (just like we ran into firstsessionhost, additionalsesssionhost issue)

**Comment by ChristianMontoya** [comment]
@nakranimohit0 : Yes, agreed.
