### ISSUE TITLE
WVD scaling script 

### ISSUE THREAD

**Issue by rameshgoudch** [Azure/RDS-Templates#340]
Hi Team,

We are working WVD scaling script for Scale up and sclae down found below issues.

•	I have change the Session value to 0 on JSON Script, but its not powered off.
•	When I keep other value, its going for force shut downs active sessions.
•	Stored Credential’s is not working when scaler vm Reboots.
•	Unable to call the stored credentials from variable $Keypath.

Please help us here, Thanks

**Comment by viswanadham-k** [comment]
Hi @rameshgoudch 
Can you please access the below link and configure the latest version of WVD Scaling tool.
https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script

Let me know if you are still facing issues.

Thanks,

**Comment by ChristianMontoya** [comment]
As @viswanadham-k mentioned, please try the new script that uses logic apps and is fully described here in the public documentation: [Set up scaling script](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script).

Closing this out. Please create a new issue if scenario reproduces.
