### ISSUE TITLE
Creating new host pool doesn't create host pool

### ISSUE THREAD

**Issue by ManuPerezSan** [Azure/RDS-Templates#342]
Hi all,

I'm playing with template management process (create template, edit and create new host pool with new changes). My issue is that "Create and provision WVD host pool" create host pool but doesn't add session host to it. No errors are displayed.

My step by step:

- Create new host pool (like a template) from gallery (Win10 multiuser+ O365)
- Shutdown VM (deallocated)
- Create a snapshot
- Start VM
- Launch sysprep OOBE + Generalize + Shutdown
- Create Image from VM (I tried to create image from managed disk too)
- Create a new host pool with this image

Virtual Machine appears in the view (Azure portal) but nothing is created in WVD.

[deployment.json.txt](https://github.com/Azure/RDS-Templates/files/4166395/deployment.json.txt)
![provisioning host pool](https://user-images.githubusercontent.com/23212171/73958096-4b92e580-48ff-11ea-8214-e1cd9e18c805.PNG)
![WVD host pools](https://user-images.githubusercontent.com/23212171/73958218-809f3800-48ff-11ea-9b95-a88e38067106.PNG)

**Comment by ManuPerezSan** [comment]
Hi,

More information. After deployment with New-AzResourceGroupDeployment I see that new sessionhost is added to host pool where template (deploy from gallery + sysprep) were member.

I provisioned new host pool from Image in Azure Portal, new VM is created but new host pool doesn't exist.

Could it be that sysprep is not removing all references or is it a problem with provisioning new host pool process?

**Comment by ChristianMontoya** [comment]
@ManuPerezSan : The issue here is likely that when you created an image from the previous WVD session host, it has WVD Agent information stored from the previous host pool. Instead, can you just created just a VM with your desired image (not the WVD Provision a Host Pool Azure Marketplace flow)? Then can you try creating a host pool from it?

**Comment by ManuPerezSan** [comment]
Hi @ChristianMontoya,
Is that scenario not supported? I mean, if I want to start from scratch in WVD and I would like to use one of existing Gallery templates. Can I do it? I would like to use this first VM to use it like template and later deploy new host pool with more VMs. Is it possible? If not, what is the proper procedure?
Regards,

**Comment by ChristianMontoya** [comment]
Hi @ManuPerezSan ,

Cloning an existing WVD session host to create additional session hosts is not supported. There are two primary ways to expand the host pool:

1. If you **did not** change the VM image that are session hosts, then you can essentially re-run the original template, but then just change the number of session host VMs, so that it will expand the host pool.
2. If you **did** change the VM image for the session hosts, then the recommendation would be to run the **Update** template to create a new set of VMs based on the updated image.

**Comment by ManuPerezSan** [comment]
Hi @ChristianMontoya,
Thanks for your comments 👍 

First VM I created and what i'm using as template was a Gallery option. As you commented before, it is a no supported scenario.
On the other hand, I tried with other VM from Azure, I mean:
•	Create new VM Win2016 from Azure Portal (No WVD)
•	Join Domain
•	Stop VM + Create snapshot (First snaptshot)
•	Start VM + Sysprep (OOBE – Generalize)
•	Capture Image from [Managed disk](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/capture-image-resource)
•	Run ‘Windows Virtual Desktop – Provision a host pool (Image source: Managed Image)
Sometimes I receive WinRM errors and others DSC Extension error.

I understand that it is correct step by step. What I am doing wrong?

**WinRM error:**
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'dscextension'. Error message: \\\"DSC Configuration 'FirstSessionHost' completed with error(s). Following are the first few: The WS-Management service cannot process the request. The WMI service or the WMI provider returned an unknown error: HRESULT 0x80041033 \\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot \"\r\n }\r\n ]\r\n }\r\n}"}]}

Log file shows this message:
VERBOSE: [2020-02-13 11:13:33Z] [ERROR] The WS-Management service cannot 
process the request. The WMI service or the WMI provider returned an unknown 
error: HRESULT 0x80041033 

**DSC Error:**
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'dscextension'. Error message: \\\"The DSC Extension failed to execute: The background process reported an error with the following message: ..\\r\\nMore information about the failure can be found in the logs located under 'C:\\\\WindowsAzure\\\\Logs\\\\Plugins\\\\Microsoft.Powershell.DSC\\\\2.80.0.0' on the VM.\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot \"\r\n }\r\n ]\r\n }\r\n}"}]}

I check log file and shows error in specific line in psm1 file 😨

**Comment by ChristianMontoya** [comment]
@ManuPerezSan : Hmm... I'm not exactly sure on this one. There should be some way to make sure that WinRM works, although I'm not an expert. Are you able to test with just the Windows 10 Enterprise multi-session image instead of Windows Server 2016?

**Comment by ManuPerezSan** [comment]
Hi @ChristianMontoya,
This kind of SKU is not available in Azure (only in WVD).
![image](https://user-images.githubusercontent.com/23212171/74523109-cd48cb80-4f1c-11ea-8281-aba6158780b7.png)

**Comment by ManuPerezSan** [comment]
Hi again,
I created a Windows 10 Multi-user with O365 from Azure Portal with name Win10O365 (consider as template)
- I installed anything (no changes). I don't installed WVDAgent and bootloader.
- Snapshot
- Sysprep
- Capture image
- Provision a new host pool. Creating 2 instances (RdshNumberOfInstances=2)

After deployment finished I have 3 VMs but host pool only has Win10O365
![image](https://user-images.githubusercontent.com/23212171/74590367-06ad3400-500e-11ea-9fb4-432e3e881bbe.png)

![image](https://user-images.githubusercontent.com/23212171/74590375-14fb5000-500e-11ea-8578-c33b9be81e7d.png)

Is there official step-by-step guide to create Golden images and create/upgrade host pools?

**Comment by Digiroka** [comment]
Are you sure you did not create a separate hostpool? the screenshot is only showing host for a single pool. You can check the current environment very quickly via powershell:

1) Open powershell, run the below command, log into the WVD platform with an admin account
**Add-RdsAccount -DeploymentUrl "https://rdbroker.wvd.microsoft.com"**

2) Run this command to get a list of active WVD pools:
**Get-RdsHostPool -TenantName <Your Tenant Name>**

3) Make a note of all the **HostPoolName** values returned

4) For each hostpool, run the below command to get a list of the session hosts in it:
**Get-RdsSessionHost -TenantName <Your Tenant Name> -HostPoolName <Your Hostpool name>**

This will give you a complete view of what WVD can see in your tenant. for each session host check the below values. they should look like this:

**Status             : Available
UpdateState  : Succeeded**

**Comment by ManuPerezSan** [comment]
Hi @Digiroka,

I created a Support case and after some tests, we found that selected OS is not compatible.

**Not compatible:**
1. Login in Azure Portal
2. Go to 'Virtual Machines'
3. Add and select Windows 10 in combo

**Compatible**
1. Login in Azure Portal
2. Create a resource
3. Search 'Microsoft Windows 10'

Regards,

**Comment by ChristianMontoya** [comment]
@ManuPerezSan : I'll see where we can make this more clear in our documentation, but thank you for the follow-up. I will close out this comment, but please re-open or respond if there are anymore questions on this topic.

**Comment by stefan923456** [comment]
I had the same issue as described by ManuPerezSan. I created a sysprepped VHD of a working WVD machine as our source. Our client has this really old legacy app which only the supplier is allowed to install, so creating a golden image building street is not really possible anymore.
 
After deploying new machines to a new HOSTPOOL they registered in the current HOSTPOOL and not all of them, it also was not working stable.
 
So I fixed the current situation like this:
•	Use New-RDSHostpool to create a new empty hostpool.
•	RDP with Admin rights into every WVD machine that is in the wrong hostpool, uninstall all the Remote Desktop Services software like in this picture.
![image](https://user-images.githubusercontent.com/42831440/85396915-e7da2380-b552-11ea-8414-f7d83cd6d8eb.png)
•	Reboot the machine.
•	Grab the RDS Registion Info with powershell with the commands on the website on this (link) 
•	RDP back with Admin rights and install these two agents according to this website. (link) 
o	First install Microsoft.RDInfra.RDAgent.Installer-x64-1.0.1932.4800.msi you need to paste the registration token in this installer
o	Second install Microsoft.RDInfra.RDAgentBootLoader.Installer-x64.msi
•	If you check after about 10 seconds with this command: Get-RdsSessionHost -TenantName tenantname -HostPoolName "Windows 10 WVD" you will see the RDS Host attached. I recommend rebooting after this.
•	This fixed the problem at our end!
