### ISSUE TITLE
Update-existing-WVD-host-pool fails to remove availability set

### ISSUE THREAD

**Issue by GrahamHassall** [Azure/RDS-Templates#343]
Hi,
I have been testing the updated deploy and update WVD hostpool templates. Great that they are now single templates rather than using nested templates. 

I have run across some issues with the "Script-CleanupOldRdshSessionHost.ps1! DSC script while doing an update of an existing hostpool. For me, the script successfully creates the new hosts, removes the previously deployed hosts and their associated resources, but it fails to remove the availability set for those removed hosts. No errors are reported and the template deploys "successfully"

The code in the script currently identifies any availability sets in the resource group and does a check to see if there are any VirtualMachineReferences connected to those availability sets. The problem appears to be that at the point that the check is made, there are 2 availability sets in the resource group (the old one and the new one), so when it does it's check to see if the availability set is empty ("if ($avset.VirtualMachinesReferences.Id -eq $null)"), this check returns false as it sees the newly deployed hosts connected to the new availability set and therefore does not run the remove availability set command. I think you may have to loop through the discovered availability sets to do this check for connected hosts

The script also does not currently clear up computer accounts in active directory or DNS records if the VM running the DSC script is a client OS (looks like the code only runs if the OS is identified as a server ("if ($rdshIsServer)"). Are there any plans to extend this functionality so that it can run this part of the cleanup on client OSes. After all they have AD accounts and DNS records that need to be cleaned up as well?

Finally, I'm not sure about the timing of when the old hosts are being put into drain mode. At the moment this seems to be happening right before the host is deleted. It would make more sense to me if all the old hosts are put into drain mode right at the start of this script, before it does anything else with the hosts that are to be removed. Setting drain mode right before deleting the host seems a little redundant.

**Comment by ChristianMontoya** [comment]
@GrahamHassall : All great suggestions! We'll take these into consideration and prioritize them with the rest of the work we have.

**Comment by nakranimohit0** [comment]
Created a feature request internally. Closing this out for now.
