### ISSUE TITLE
Scaling Logic App - Appended Countdown message

### ISSUE THREAD

**Issue by Digiroka** [Azure/RDS-Templates#345]
Hi - When setting a logoff message for users, it is always suffixed with 'you will logged off in xxx seconds'.

Firstly, this message is missing the word 'be'.
Secondly, is there any way to amend or remove it? 

![image](https://user-images.githubusercontent.com/26280877/74414446-5edf0d00-4e39-11ea-9132-90dabaa38605.png)

Thanks

**Comment by viswanadham-k** [comment]
Hi @Digiroka 
Thank you for giving feedback. Please find below inline answers.

Firstly, this message is missing the word 'be'.
**Sure we will align and push the changes to github.**

Secondly, is there any way to amend or remove it?
**We are working on this change, we will push these changes to github. Once it's done will inform you then execute this "createazureautomationaccount.ps1" powershell script. Once executed script then it will automatically reflect new changes.**

Thanks,

**Comment by Digiroka** [comment]
Thank you for updating the message in the new version.
If anybody else wants to edit or remove the appended message, this can be done by editing the runbook and searching for **$LogOffMessageTitle** -MessageBody "$($LogOffMessageBody)**

**Comment by ChristianMontoya** [comment]
This has now been merged. Closing out.
