### ISSUE TITLE
off-peak hours scaling down issue

### ISSUE THREAD

**Issue by Sawal72** [Azure/RDS-Templates#346]
When during off-peaks hours more users are working, an extra sessionhost will be started. When later in the off-peaks hours all the users are gone/logoff, all the sessionhost will be shutdown. Even when you start manually a sessionhost, these will be shutdown are the next run of the runbook.

Is seems the problem is a wrong value for OffPeakUsage-MinimumNoOfRDSH will be set. When all users are logoff, OffPeakUsage-MinimumNoOfRDSH will be 0.
![image](https://user-images.githubusercontent.com/22495447/74438170-d88eef00-4e69-11ea-8b45-1257ec5f6608.png)
After the next runbook run, all the sessionhost will be shutdown.

When i change the value of OffPeakUsage-MinimumNoOfRDSH back to 1, the sessionhost will keep running in off-peak hours.

**Comment by viswanadham-k** [comment]
Hi @Sawal72 
Thank you for raising this issue. We are working on to investigate and fix your issue, will update you soon.

Thanks,
