### ISSUE TITLE
Template MSFT-WVD-SAAS-UX deployed in a different AAD

### ISSUE THREAD

**Issue by Fsodano79** [Azure/RDS-Templates#348]
Hi,

I have the WVD host pool hosted in a subscription connected to a different AAD compared to the WVD tenant. this seems to be supported and the WVD service is working great. Now I would like to deploy the UX. 

So WVD host pool with an Azure Subscription connect to AAD X
users and WVD Tenant connect to AAD Y

Is possible to deploy the UX in the subscription connected to AAD X (where the host pool is)?

Thanks,

Francesco

**Comment by viswanadham-k** [comment]
Hi @Fsodano79 
As per my understanding "**WVD General Available**" functionality is One AAD can have one tenant and hostpool should be exist under tenant. You can able to deploy the management ux tool where session hosts are existed and AADDomainService configured **subscription**.

Thanks,

**Comment by Fsodano79** [comment]
My situation is a bit different.

- I have my Azure subscription attached to AAD X.
- I created a Domain Controller in IaaS and with Azure AD Connect I'm syncing it to an Azure AD where I have my Office365 demo users. this Azure AD is Y and is different from X.
- My WVD tenant is attached to Azure AD X.
- My Hostpool is hosted in Azure subscription attached to Azure AD Y.

Everything is working but I'm not able to deploy the UX.

I'm using the Global Admin account from Azure AD Y (where the WVD tenant is) and this user has also (as guest) contribution role on the resource group where the UX should be deployed.

Is there something I'm missing?

Thanks,

Francesco

**Comment by viswanadham-k** [comment]
Hi @Fsodano79 

User must be in same AAD and he has global admin and subscription contributor then only you can able deploy the management tool with out any issue. 
To deploy the management tool please find below links and follow the document steps.

https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui
(or)
https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell


Thanks,

**Comment by ChristianMontoya** [comment]
@Fsodano79 : Just to confirm, you will need to deploy this management UX in an Azure Subscription tied to the WVD users (and WVD tenant). In your case, this means you will need an Azure Subscription tied to Azure AD X, and deploy the management UX there.

Closing out this issue, but please re-open if you have any more questions.
