### ISSUE TITLE
Deploy the Template fails Nic. Don´t know why. Location euwest

### ISSUE THREAD

**Issue by Vvand-jkra** [Azure/RDS-Templates#349]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidResourceReference\",\r\n \"message\": \"Resource /subscriptions/6b6245dd-d7ad-424f-8d63-93cb334451e3/resourceGroups/WVD/providers/Microsoft.Network/virtualNetworks/WVD-net/subnets/default referenced by resource /subscriptions/6b6245dd-d7ad-424f-8d63-93cb334451e3/resourceGroups/WVD/providers/Microsoft.Network/networkInterfaces/wvd-w10-1-nic was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.\",\r\n \"details\": []\r\n }\r\n}"}

**Comment by Digiroka** [comment]
This message is telling you that the NIC does not exist.
The NIC is one of the first resources to be created as part of the deployment process - so do you have a NIC named "wvd-w10-1-nic" in your target resource group? If not, I would assume a permissions issue. Do you have rights to create the required resources in the target RG?

**Comment by Vvand-jkra** [comment]
Yes i understand the message but the template i am using should create them or am i wrong ?. I am logged in as global admin in portal.azure.com and should be able to create everything. 

https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FRDS-Templates%2Fmaster%2Fwvd-templates%2FCreate%20and%20provision%20WVD%20host%20pool%2FmainTemplate.json

**Comment by Digiroka** [comment]
Yes, the template should create the NIC resources first. I'm assuming that it hasn't been created?
If not, 

(1) does the vnet exist? 
(2) Is the vnet in the same region as the WVD VM / NIC resource?
(3) Does the WVD subnet exist?

**Comment by Vvand-jkra** [comment]
No, thats the failure point on deploying.

(1) does the target vnet exist? -> exists as you can see on the image
(2) Is the target vnet in the same region as the WVD VM / NIC resource? ->everything same region
(3) Does the target WVD subnet exist? -> subnet exists

![image](https://user-images.githubusercontent.com/61143345/74655193-413cdb00-518c-11ea-8683-9eb429218c89.png)
![image](https://user-images.githubusercontent.com/61143345/74655382-8c56ee00-518c-11ea-992d-893f3daa4ed7.png)

**Comment by Digiroka** [comment]
It would be worth creating a dedicated 'WVD' subnet. Also I would delete the orphaned WVD resources 3x Availability sets), as these wont get cleaned up otherwise. Interesting to note that these are getting created, so there must be a conflict with the NIC creation task.
What are you using the 'public ip address' resources for?

**Comment by Vvand-jkra** [comment]
The public ip adress is used with the virtual network gateway. 
I deleted the availability sets and retried with a subnet but still same error.


Here is also the manual i am following.
https://securityboulevard.com/2019/11/windows-virtual-desktop-the-best-step-by-step-walkthrough/

**Comment by Digiroka** [comment]
you also have a 'wvdipaddress' - is it required?
The guidance in that article is pretty comprehensive, but this step should not be hard.
Can you try creating the NIC object manually, and see if this is possible?

**Comment by Vvand-jkra** [comment]
Even if i create the nic´s manually it is no possible for the deployment to find them.

![image](https://user-images.githubusercontent.com/61143345/74660577-a85f8d00-5196-11ea-8c81-eaad3bed5d5d.png)
![image](https://user-images.githubusercontent.com/61143345/74660627-c5945b80-5196-11ea-93c8-c45f217eb6ff.png)

**Comment by Digiroka** [comment]
The template will not use pre-created NICs. It will fail of the named resource already exists.  
I asked you to create the nic manually to ensure there were no other issues with creating nics.
It looks like you were able to create them manually with no issues.
Is this correct? Please delete the manually created nics if so. 

Are you using the marketplace, or are you deploying from the github template below?
https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool

**Comment by Vvand-jkra** [comment]
Yes it is correct. 
I use the template from github but it is also not possible to create over the marketplace.

**Comment by Digiroka** [comment]
Ok, are you seeing any other errors under the deployments tab of the target resource group? 
Can you post the full error from the failed deployment (Summary and raw).
Do you have multiple subscriptions?

**Comment by Vvand-jkra** [comment]
![image](https://user-images.githubusercontent.com/61143345/74663216-a3510c80-519b-11ea-83fe-4020ca394c11.png)

![image](https://user-images.githubusercontent.com/61143345/74663154-8d434c00-519b-11ea-8ed9-2084c731817d.png)

RAW:
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidResourceReference\",\r\n    \"message\": \"Resource /subscriptions/6b6245dd-d7ad-424f-8d63-93cb334451e3/resourceGroups/WVD/providers/Microsoft.Network/virtualNetworks/WVD-net/subnets/default referenced by resource /subscriptions/6b6245dd-d7ad-424f-8d63-93cb334451e3/resourceGroups/WVD/providers/Microsoft.Network/networkInterfaces/wvd-win10-1-nic was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.\",\r\n    \"details\": []\r\n  }\r\n}"
    },
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidResourceReference\",\r\n    \"message\": \"Resource /subscriptions/6b6245dd-d7ad-424f-8d63-93cb334451e3/resourceGroups/WVD/providers/Microsoft.Network/virtualNetworks/WVD-net/subnets/default referenced by resource /subscriptions/6b6245dd-d7ad-424f-8d63-93cb334451e3/resourceGroups/WVD/providers/Microsoft.Network/networkInterfaces/wvd-win10-0-nic was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.\",\r\n    \"details\": []\r\n  }\r\n}"
    }
  ]
}

**Comment by Digiroka** [comment]
Ok, I would suggent reviewing the below blog regarding prereqs to ensure all steps have been completed as recommended:
https://cloudblogs.microsoft.com/industry-blog/en-gb/cross-industry/2019/09/19/windows-virtual-desktop-pre-requisites-everything-in-the-right-place-to-enable-you-to-deploy-without-errors/

**Comment by wahidsaleemi** [comment]
Are you sure the subnet exists? Specifically, the error says there should be a virtual network called "WVD-net" (I only see WVD-vnet) and a subnet in there called "default" - the problem isn't with the NIC.

**Comment by Vvand-jkra** [comment]
> Are you sure the subnet exists? Specifically, the error says there should be a virtual network called "WVD-net" (I only see WVD-vnet) and a subnet in there called "default" - the problem isn't with the NIC.

Thank you soo much. It was a stupid typo....
After correcting this, everything went well.

**Comment by Digiroka** [comment]
@wahidsaleemi - well spotted!

**Comment by AbhijeetDhoke-1** [comment]
non of solution helping me 

        "responseBody": "{\"error\":{\"code\":\"InvalidResourceReference\",\"message\":\"Resource /subscriptions/e772571a-b0c5-4791-9c58-XXXXX/resourceGroups/RG-HC-EastUS/providers/Microsoft.Network/virtualNetworks/Spoke-HC-US-1/subnets/PrivateLink-USEast-1' referenced by resource /subscriptions/e772571a-b0c5-4791-9c58-XXXXXX/resourceGroups/RG-J-Prod-East-PROD/providers/Microsoft.Network/privateEndpoints/stvmapp02p-ep was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.\",\"details\":[]}}",

Both the subscription is same (Vnet and actual RG) 
subnet and vnet is present
No typo checked.

**Comment by bradyuen** [comment]
I got an issue totally the same, and no luck at all...
