### ISSUE TITLE
Multiple Logicapps with one automationaccount and runbook?

### ISSUE THREAD

**Issue by Sawal72** [Azure/RDS-Templates#350]
Is it possible make more than one Logicapps (Multiple hostpools autoscale scheduler) with using one automation account and runbook?  Gives this problems with the automation variable "OffPeakUsage-MinimumNoOfRDSH", which will be used?

**Comment by viswanadham-k** [comment]
Hi @Sawal72 
We have updated "OffPeakUsage-MinimumNoOfRDSH" with hostpoolname. So there is no problem. Now each hostpool will separately create with name like "Hostpoolname-OffPeakUsage-MinimumNoOfRDSH" by script then store dynamically created value.

Please find below commit URL and review the changes then let us know your feedback.

https://github.com/Azure/RDS-Templates/commit/4ca7651bfb5f1d933ee80fcc896c9232bdc98bd1

Thanks.

**Comment by Sawal72** [comment]
Hello,

yes, indeed there is now a variable with the hostpoolname, so it's possible the scale multiple hostpools with one automation account and runbook.

**Comment by viswanadham-k** [comment]
Hi @Sawal72 
Yeah, it's possible multiple hostpools with one automation account and runbook.

Thanks,

**Comment by RoopChevuri** [comment]
Closing as original question has been answered.
