### ISSUE TITLE
Management UX - No hosts visible (out of the box) , how to add ?

### ISSUE THREAD

**Issue by Vinisz** [Azure/RDS-Templates#353]
Hi,

For me, a couple of things are not quite clear

- Should hosts be visible in the pool automaticly ?
-If yes, then for me this is not working, why not ?
-If no, I think I need to add these with a key or something ? (see screenshot) , how ?

![image](https://user-images.githubusercontent.com/49644964/74816515-9d723d00-52fb-11ea-8a9a-5a82bc255a46.png)

**Comment by viswanadham-k** [comment]
Hi @Vinisz 

Please find the inline answers.
Should hosts be visible in the pool automaticly ?
**Yes**
-If yes, then for me this is not working, why not ?
**Reason: I hope you are not created hosts by Marketplace or ARM template.**
-If no, I think I need to add these with a key or something ? (see screenshot) , how ?
This key is used when you creating hosts manually.

Microsoft recommended to create hosts either use ARM template or from azure market place. So please access the below link and follow the readme.md file then deploy template.
https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool 

Thanks,

**Comment by ChristianMontoya** [comment]
Closing. Please re-open if you have additional closing.
