### ISSUE TITLE
Scaling Logic App - Killing user processes

### ISSUE THREAD

**Issue by Digiroka** [Azure/RDS-Templates#357]
Hi - We are using Liquidware ProfileUnity for user profile management - Liquidware are a launch partner for WVD. 

When using the WVD autoscale logic app, if the pool is auto-scaled down while a user is logged on, the script auto-closes all user processes, including the profile unity logoff dialogue.
As a result, it looks like user profile settings don’t get captured in this scenario.

Would it be possible for the script to wait for all user processes to close?
Perhaps also add a timeout value (maybe 5 minutes) to kill any hung processes?

Also the shutdown does not appear to be graceful, as the shutdown event tracker is presented to users after the host starts again - I know we can control this with policy, but a graceful shutdown would be better.

Thanks

**Comment by Digiroka** [comment]
Any thoughts?

**Comment by viswanadham-k** [comment]
Hi @Digiroka 
Scaling script functionality didn't test with "Liquidware ProfileUnity for user profile management". As we have tested with Microsoft released tools "Windows client (MSRDC)" there is no issue and user is able to see the log off message and also able to logged off with dialog.

Thanks

**Comment by Digiroka** [comment]
Thanks, so to confirm; you have not tested the approved partner product Liquidware Profile Unity, and the scaling logic app does not support it.

Please confirm this is your position.

**Comment by RoopChevuri** [comment]
Closing this as information has been passed to the partner
