### ISSUE TITLE
Scaling Logic App - Not shutting down VM's in peak hours

### ISSUE THREAD

**Issue by Misterjohnson87** [Azure/RDS-Templates#358]
I have deployed the WVD Scaling App and can see it works well with scaling up and saw it successfully power up a VM to meet user demand but it doesn't seem to power off VM's or scale down.

Here are the logs from the scaling app:

2/20/2020, 12:06:13 PM | Output | Checking session host: xxxx-0.xxx.xxx.xx.xx of sessions: 1 and status: Available
2/20/2020, 12:06:14 PM | Output | Checking session host: xxxx-1.xxx.xxx.xx.xx of sessions: 0 and status: NoHeartbeat
2/20/2020, 12:06:15 PM | Output | Checking session host: xxxx-2.xxx.xxx.xx.xx of sessions: 0 and status: Available
2/20/2020, 12:06:15 PM | Output | Current number of running hosts:2
2/20/2020, 12:06:15 PM | Output | Current total number of user sessions: 1
2/20/2020, 12:06:16 PM | Output | Current available session capacity is: 8
2/20/2020, 12:06:16 PM | Output | HostpoolName: xxx-xxx-xxx, TotalRunningCores: 8 NumberOfRunningHosts: 2
2/20/2020, 12:06:16 PM | Output | End WVD tenant scale optimization.

Here are my settings for the scaling app:

 "AutomationAccountName": "xxxxxx",
  "BeginPeakTime": "9:00",
  "ConnectionAssetName": "AzureRunAsConnection",
  "EndPeakTime": "17:30",
  "HostPoolName": "xxxxx",
  "LimitSecondsToForceLogOffUser": 0,
  "LogAnalyticsPrimaryKey": "",
  "LogAnalyticsWorkspaceId": "",
  "LogOffMessageBody": "xxxxx",
  "LogOffMessageTitle": "xxxxxxx",
  "MaintenanceTagName": "VMTAG",
  "MinimumNumberOfRDSH": 1,
  "RDBrokerURL": "https://rdbroker.wvd.microsoft.com",
  "SessionThresholdPerCPU": 1,

Thanks

**Comment by Sawal72** [comment]
Scaling down occurs in off-peak hours.

**Comment by viswanadham-k** [comment]
Hi @Misterjohnson87 

Scaling down occurs in off-peak hours.

Thanks,

**Comment by Misterjohnson87** [comment]
Ok, makes sense thanks.
