### ISSUE TITLE
Feature request - Minimal sessionhosts for peak hours

### ISSUE THREAD

**Issue by Sawal72** [Azure/RDS-Templates#361]
We can now define the number of sessionhosts during off-peak hours. But also a number of minimal server during peak-hours should be fine. This could prevent problems during a logon storm of users at the start of the peak hours, because scale up of extra sessionhost is to slow for the number of users which are logon.

**Comment by erjosito** [comment]
I have had a similar request, and am working in my own version of the script. Let me know if you are interested in a PR for this.

**Comment by RoopChevuri** [comment]
Thanks for the feedback. We will review this for future scaling functionality.
