### ISSUE TITLE
Management UX - No app registration

### ISSUE THREAD

**Issue by martinyy108** [Azure/RDS-Templates#362]
Hi,

I was able to create the management UX with ARM template as per MS doc. But I can not find the app registration in Azure AD thus the Management UX shows blank as below:

![image](https://user-images.githubusercontent.com/39147252/75305912-8c956e80-589b-11ea-81cc-f98a001f99ce.png)

Can you please advise?

Regards,

Martin

**Comment by martinyy108** [comment]
I did create the management UX with a service principal instead of my GA account. Permissions with the service principal?

**Comment by viswanadham-k** [comment]
Hi @martinyy108 
Can you please conform did you follow the below link steps and deployed management tool with service principal?
https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell

Thanks,

**Comment by IamAliBaba** [comment]
I created the same way and have this picture.

**Comment by martinyy108** [comment]
I used the ARM template as doc below:

https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui

Also used the same service principal to create host pool and that worked.

**Comment by viswanadham-k** [comment]
Hi @martinyy108 
I am little bit confuse. Please let me know your available time today(02-27-2020) in between 3:00 PM to 10:00 PM (IST) then will connect and resolve your issue. And let me know your mailing address i will send a meeting invitation.

Thanks,

**Comment by martinyy108** [comment]
I am available now if you can assist. email is martin.yang@epa.vic.gov.au

**Comment by martinyy108** [comment]
Thanks so much for your assistance! You are a star!!!
