### ISSUE TITLE
Update ARM template deploying a blank app

### ISSUE THREAD

**Issue by miguele-agileit** [Azure/RDS-Templates#369]
Just updated the application getting a blank screen

**Comment by ChristianMontoya** [comment]
@miguele-agileit : Can you clarify what you mean, and/or send some screenshots? And send a link to which template you're using?

**Comment by Vlad-Bite-Me** [comment]
![image](https://user-images.githubusercontent.com/54784156/76179630-7c17b900-61f6-11ea-9e7e-5bf9d7818932.png)
Hi , I have the same problem, was deploying from 
https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/wvd-management-ux/deploy
By clicking Deploy to Azure. Used service principal, all gone OK, but web page did not asked for authorization, and I am a Global Admin

**Comment by ChristianMontoya** [comment]
If you are deploying through service principal, go through these steps: https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell

**Comment by Vlad-Bite-Me** [comment]
Thanks Christian,
What are the steps to completely remove broken installation?

**Comment by ChristianMontoya** [comment]
@Vlad-Bite-Me : Primarily, the main resources that got deployed are:
1. An app registration in Azure AD
2. That resource group (and resources) in Azure.

If you delete the app registration from Azure AD and then the resource group in Azure, you should be good.
