### ISSUE TITLE
Deployment error with parameter "vmImageVhdUri"

### ISSUE THREAD

**Issue by wcvanzyl** [Azure/RDS-Templates#375]
The template explanation points out not to configure anything under **Vm Image Vhd Uri** because that is for **Custom** images.

Yet, when using an image from the Gallery and provision, the error type during validation is:

The value of deployment parameter 'vmImageVhdUri' is null. Please specify the value or use the parameter reference.

**Comment by nakranimohit0** [comment]
@wcvanzyl  Can you share all parameters you are passing to the template ? You can mask/clear any sensitive info.

**Comment by nakranimohit0** [comment]
Closing this out as there is no response
