### ISSUE TITLE
Update existing WVD host pool failing

### ISSUE THREAD

**Issue by PMLIO** [Azure/RDS-Templates#381]
I'm running this deployment in powershell
**New-AzResourceGroupDeployment  -ResourceGroupName $resourceGroupName -TemplateFile $templateFile -TemplateParameterFile $templateParameterFile**

I'm getting the following error. I have reviewed my parameters file and can't find anything wrong.

> New-AzResourceGroupDeployment : 12:57:59 - Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'Template parameter 
> JToken type is not valid. Expected 'Integer'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage 
>

**Comment by PMLIO** [comment]
Deployed to Azure and now I'm getting this

>  {
>     "status": "Failed",
>     "error": {
>         "code": "ResourceDeploymentFailure",
>         "message": "The resource operation completed with terminal provisioning state 'Failed'.",
>         "details": [
>             {
>                 "code": "VMExtensionProvisioningError",
>                 "message": "VM has reported a failure when processing extension 'dscextension'. Error message: \"DSC Configuration 'RegisterSessionHostAndCleanup' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant.  The SendConfigurationApply function did not succeed.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "
>             }
>         ]
>     }
> }

**Comment by Digiroka** [comment]
Hello, I assume you are attempting to use a service principal account? This does not work.
https://github.com/Azure/RDS-Templates/issues/259

**Comment by PMLIO** [comment]
> Hello, I assume you are attempting to use a service principal account? This does not work.
> #259

Yes that's correct. So this is a know outstanding issue?

**Comment by nakranimohit0** [comment]
Closing out this issue as a duplicate to #321 
Please re-open if its diff.
