### ISSUE TITLE
Refresh and Restart Buttons

### ISSUE THREAD

**Issue by stevenzelenko** [Azure/RDS-Templates#382]
This isn't so much an issue but a recommendation to make the restart and refresh buttons different images.  Perhaps a power button for restart.  Can't tell you how many times I've went for restart before refresh WITH users connected.  It's fine for me but since we will have more admins, it would be better if they were separate icons.

**Comment by nakranimohit0** [comment]
@stevenzelenko 
What part of the repo is this about ? Can you assign one of the labels ?

**Comment by stevenzelenko** [comment]
#272
