### ISSUE TITLE
Scaling automation not working

### ISSUE THREAD

**Issue by martinyy108** [Azure/RDS-Templates#383]
Hi,

I am having problems with the scaling automation which fails to run as below:

![image](https://user-images.githubusercontent.com/39147252/77050097-5459f980-6a1d-11ea-8ce8-06697b7349cf.png)

![image](https://user-images.githubusercontent.com/39147252/77050149-689df680-6a1d-11ea-8b6a-b147e94c485e.png)

Can you please assist?

Regards,

Martin

**Comment by martinyy108** [comment]
I was able to fix this issue.

**Comment by Jimbos10** [comment]
I'm having a similar issue, could you share what you did to fix the issue above?

**Comment by YariCa** [comment]
Hi, please share the solution.
thanks
