### ISSUE TITLE
Updating existing host pool failed with error: 'this.Client.SubscriptionId' cannot be null

### ISSUE THREAD

**Issue by martinyy108** [Azure/RDS-Templates#385]
Hi,

Deployment failed at installing DSC extension with error below:

![image](https://user-images.githubusercontent.com/39147252/77134983-9fc3e480-6abd-11ea-81f8-d1e986f42a92.png)

Can you please advise how I can fix this issue?

Regards,

Martin

**Comment by martinyy108** [comment]
Detailed error as below:

[
    {
        "code": "ComponentStatus/DscConfigurationLog/failed/8",
        "level": "Error",
        "displayStatus": "Provisioning failed",
        "message": "[2020-03-20 04:00:43Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0\\Status\\0.status)\r\n[2020-03-20 04:00:45Z] [WARNING] [WVDx-0]:                            [[Script]CleanupOldRdshSessionHosts] 1.0.1534.2001\r\n[2020-03-20 04:00:45Z] [VERBOSE] [WVDx-0]: LCM:  [ End    Set      ]  [[Script]CleanupOldRdshSessionHosts]  in 204.7820 seconds.\r\n[2020-03-20 04:00:46Z] [ERROR] PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: 'this.Client.SubscriptionId' cannot be null. \r\n[2020-03-20 04:00:46Z] [VERBOSE] [WVDx-0]: LCM:  [ End    Set      ]\r\n[2020-03-20 04:00:46Z] [ERROR] The SendConfigurationApply function did not succeed.\r\n[2020-03-20 04:00:46Z] [VERBOSE] Operation 'Invoke CimMethod' complete.\r\n[2020-03-20 04:00:46Z] [VERBOSE] Time taken for configuration job to complete is 347.465 seconds\r\n[2020-03-20 04:01:56Z] [VERBOSE] Performing the operation \"Start-DscConfiguration: SendMetaConfigurationApply\" on target \"MSFT_DSCLocalConfigurationManager\".\r\n[2020-03-20 04:01:56Z] [VERBOSE] Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendMetaConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.\r\n[2020-03-20 04:01:56Z] [VERBOSE] An LCM method call arrived from computer WVDx-0 with user sid S-1-5-18.\r\n[2020-03-20 04:01:56Z] [VERBOSE] [WVDx-0]: LCM:  [ Start  Resource ]  [MSFT_DSCMetaConfiguration]\r\n[2020-03-20 04:01:56Z] [VERBOSE] [WVDx-0]: LCM:  [ Start  Set      ]\r\n[2020-03-20 04:01:56Z] [VERBOSE] [WVDx-0]: LCM:  [ Start  Set      ]  [MSFT_DSCMetaConfiguration]\r\n[2020-03-20 04:01:56Z] [VERBOSE] [WVDx-0]: LCM:  [ End    Resource ]  [MSFT_DSCMetaConfiguration]\r\n[2020-03-20 04:01:56Z] [VERBOSE] [WVDx-0]: LCM:  [ End    Set      ]  [MSFT_DSCMetaConfiguration]  in 0.0470 seconds.\r\n[2020-03-20 04:01:56Z] [VERBOSE] [WVDx-0]: LCM:  [ End    Set      ]\r\n[2020-03-20 04:01:56Z] [VERBOSE] [WVDx-0]: LCM:  [ End    Set      ]    in  0.1090 seconds.\r\n[2020-03-20 04:01:56Z] [VERBOSE] Operation 'Invoke CimMethod' complete.\r\n[2020-03-20 04:01:56Z] [VERBOSE] Set-DscLocalConfigurationManager finished in 0.902 seconds."
    },
    {
        "code": "ComponentStatus/DscExtensionLog/failed/8",
        "level": "Error",
        "displayStatus": "Provisioning failed",
        "message": "[2020-03-20 03:54:36Z] Looking for the definition of the configuration function.\r\n[2020-03-20 03:54:36Z] Executing C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0\\bin\\..\\DSCWork\\Configuration.0\\Configuration.ps1\r\n[2020-03-20 03:54:36Z] Preparing configuration arguments and configuration data.\r\n[2020-03-20 03:54:39Z] Created encryption certificate 28D25C86E09B5BA336A928CA27487F3563760B34\r\n[2020-03-20 03:54:39Z] Adding encryption certificate 28D25C86E09B5BA336A928CA27487F3563760B34 to the configuration data\r\n[2020-03-20 03:54:39Z] Creating MOF files.\r\n[2020-03-20 03:54:39Z] Executing the configuration function to generate the MOF files.\r\n[2020-03-20 03:54:40Z] Meta configuration found. Injecting Thumbprint.\r\n[2020-03-20 03:54:40Z] CertificateID not present in existing meta configuration; inserting 28D25C86E09B5BA336A928CA27487F3563760B34.\r\n[2020-03-20 03:54:40Z] Verifying metaconfiguration for reboot information...\r\n[2020-03-20 03:54:40Z] Backing up C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0\\DSCWork\\Configuration.0\\RegisterSessionHostAndCleanup\\localhost.meta.mof\r\n[2020-03-20 03:54:40Z] No match for RegistrationKey found in the meta mof file\r\n[2020-03-20 03:54:40Z] WMF 5 or newer, Injecting RebootNodeIfNeeded = False and ActionAfterReboot = \"StopConfiguration\"\r\n[2020-03-20 03:54:40Z] Executing Set-DscLocalConfigurationManager...\r\n[2020-03-20 03:54:47Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0\\Status\\0.status)\r\n[2020-03-20 03:54:54Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0\\Status\\0.status)\r\n[2020-03-20 03:54:54Z] Get-DscLocalConfigurationManager: \r\n\r\nActionAfterReboot              : StopConfiguration\r\nAgentId                        : 664FD1F0-6A5E-11EA-B85D-000D3AE01C6B\r\nAllowModuleOverWrite           : False\r\nCertificateID                  : 28D25C86E09B5BA336A928CA27487F3563760B34\r\nConfigurationDownloadManagers  : {}\r\nConfigurationID                : \r\nConfigurationMode              : ApplyOnly\r\nConfigurationModeFrequencyMins : 15\r\nCredential                     : \r\nDebugMode                      : {NONE}\r\nDownloadManagerCustomData      : \r\nDownloadManagerName            : \r\nLCMCompatibleVersions          : {1.0, 2.0}\r\nLCMState                       : Idle\r\nLCMStateDetail                 : \r\nLCMVersion                     : 2.0\r\nStatusRetentionTimeInDays      : 10\r\nSignatureValidationPolicy      : NONE\r\nSignatureValidations           : {}\r\nMaximumDownloadSizeMB          : 500\r\nPartialConfigurations          : \r\nRebootNodeIfNeeded             : False\r\nRefreshFrequencyMins           : 30\r\nRefreshMode                    : PUSH\r\nReportManagers                 : {}\r\nResourceModuleManagers         : {}\r\nPSComputerName                 : \r\n\r\n\r\n\r\n\r\n[2020-03-20 03:54:54Z] Executing Start-DscConfiguration...\r\n[2020-03-20 03:54:55Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0\\Status\\0.status)\r\n[2020-03-20 04:00:47Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0\\Status\\0.status)\r\n[2020-03-20 04:00:47Z] Updating execution status (HKLM:\\SOFTWARE\\Microsoft\\Azure\\DSC\\2.80.0.0\\Status)\r\n[2020-03-20 04:00:47Z] LCM state is PendingConfiguration\r\n[2020-03-20 04:01:47Z] DSC configuration completed.\r\n[2020-03-20 04:01:47Z] Resetting metaconfiguration...\r\n[2020-03-20 04:01:47Z] Restoring C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0\\DSCWork\\Configuration.0\\RegisterSessionHostAndCleanup\\localhost.meta.mof.bk...\r\n[2020-03-20 04:01:47Z] Executing Set-DscLocalConfigurationManager...\r\n[2020-03-20 04:01:48Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0\\Status\\0.status)\r\n[2020-03-20 04:01:57Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0\\Status\\0.status)\r\n[2020-03-20 04:01:57Z] Get-DscLocalConfigurationManager: \r\n\r\nActionAfterReboot              : ContinueConfiguration\r\nAgentId                        : 664FD1F0-6A5E-11EA-B85D-000D3AE01C6B\r\nAllowModuleOverWrite           : False\r\nCertificateID                  : 28D25C86E09B5BA336A928CA27487F3563760B34\r\nConfigurationDownloadManagers  : {}\r\nConfigurationID                : \r\nConfigurationMode              : ApplyOnly\r\nConfigurationModeFrequencyMins : 15\r\nCredential                     : \r\nDebugMode                      : {NONE}\r\nDownloadManagerCustomData      : \r\nDownloadManagerName            : \r\nLCMCompatibleVersions          : {1.0, 2.0}\r\nLCMState                       : PendingConfiguration\r\nLCMStateDetail                 : \r\nLCMVersion                     : 2.0\r\nStatusRetentionTimeInDays      : 10\r\nSignatureValidationPolicy      : NONE\r\nSignatureValidations           : {}\r\nMaximumDownloadSizeMB          : 500\r\nPartialConfigurations          : \r\nRebootNodeIfNeeded             : True\r\nRefreshFrequencyMins           : 30\r\nRefreshMode                    : PUSH\r\nReportManagers                 : {}\r\nResourceModuleManagers         : {}\r\nPSComputerName                 : \r\n\r\n\r\n\r\n\r\n[2020-03-20 04:01:57Z] Settings handler status to 'error' (C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0\\Status\\0.status)"
    },
    {
        "code": "ComponentStatus/Metadata/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "VMUUId=533331F1-8456-42E7-A8C9-A4688AA4F684;AgentId=664FD1F0-6A5E-11EA-B85D-000D3AE01C6B;"
    }
]

**Comment by martinyy108** [comment]
[ScriptLog.log](https://github.com/Azure/RDS-Templates/files/4357942/ScriptLog.log)

Here is the scriptlog.log for furthur information

**Comment by nakranimohit0** [comment]
@martinyy108 

Thanks for sharing the information. This is a difficult one as the log shows no issues and the DSC completes as expected. Although the template deployment threw this error, everything should be deployed at this point as this error seems to be occurring after all the work is done by the template.
This is exactly similar to the issue #344 

Can you share the parameters used to call this template ?

**Comment by lintFan** [comment]
Hi, it looks like you are using a service principle for authentication and I think the problem is that it isn't authorized for the subscription you are using.
You can test this by signing using the service principle using the commands here https://docs.microsoft.com/en-us/azure/virtual-desktop/create-service-principal-role-powershell#sign-in-with-the-service-principal
Then set the context for the same subscription you are using for the update template using Set-AzureRmContext
and then try running this command
Get-AzureRmVM

**Comment by nakranimohit0** [comment]
@lintFan I don't think this is related to service principle. This is a different one. I think this is outside our templates.

@martinyy108 Its worth considering this post: https://stackoverflow.com/questions/41693243/new-azurermresourcegroup-this-client-subscriptionid-cannot-be-null

**Comment by martinyy108** [comment]
![image](https://user-images.githubusercontent.com/39147252/77139082-b459aa00-6ac8-11ea-8dd5-34bdc8f37bd5.png)

The service principal does have owner access in WVD

**Comment by martinyy108** [comment]
And I was able to create the host pool with this same service principal.

**Comment by martinyy108** [comment]
On the other hand, if I use my own account (Owner for subsciption and WVD), this issue won't happne?

**Comment by lintFan** [comment]
I'm guessing your own own account won't have this error, feel free to try it.
What access does the service principle have at the subscription level for the subscription you are using to run this template?

**Comment by martinyy108** [comment]
Thanks, I will have MFA taken off then try again with my Azure AD account.

**Comment by martinyy108** [comment]
Arm template for updating works now, It was an issue with the permissions assigned to service principal.

**Comment by nakranimohit0** [comment]
The resolution is to assign the service principal with a "Contributor" role to the Azure subscription
