### ISSUE TITLE
Scale Set script-Runbook takes so long to probe each VM 

### ISSUE THREAD

**Issue by prasing-github** [Azure/RDS-Templates#397]
•	The management tool shows 100 hosts ready to accept connections: 
•	Virtual machines show a random assortment of machine states:  
![image](https://user-images.githubusercontent.com/53368971/77607218-bbbc0000-6f6d-11ea-8eb9-d3bb6867102d.png)
•	The autoscaler runbook jobs looks like this:  
![image](https://user-images.githubusercontent.com/53368971/77607258-d7bfa180-6f6d-11ea-9495-0e480efa9fa3.png)

**Comment by prasing-github** [comment]
More Details:
Each Runbook takes at least an hour or 3 to complete -No errors/Warnings
 
Each call for the VM state check is minimum 15 seconds and we are talking about as of now 100 VM’s, they plan to increase that to 300 soon.
 
CPUThresholdFrequency is .5

**Comment by viswanadham-k** [comment]
Hi @prasing-github 
I hope latest version sort out your issue. So can you please follow the below steps and update the latest version.

Below are the steps to update the Azure automation-based scaling tool located here to latest version

Access below link and copy the content of basicScale.ps1 code into a clipboard
https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/wvd-scaling-script/basicScale.ps1

Login to the Azure portal
In the Azure portal, select All services. In the list of resources, enter and select Automation Accounts.
On the Automation Accounts page, select the name of Automation account where you have the scaling tool hosted
Click on Runbooks under Process Automation section on the left hand side pane.
Click on PowerShell Runbook named “WVDAutoScaleRunbook”
Click on Edit from the top pane
Replace the existing code with one from Step 1
Click “Save” and “Publish”
New code will come into effect from next run of the runbook based on recurrence interval you have scheduled.

Please let me know if you are still facing issues. If it is working fine then close this issue.

Thanks

**Comment by RoopChevuri** [comment]
Can you please validate the behavior with newer version of tool :  https://github.com/nakranimohit0/azure-docs/blob/yammer_private_preview_wvd_scaling/articles/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script.md . This will be published broadly in few weeks.

**Comment by nakranimohit0** [comment]
Closing this out. Please re open if you are still running into the same issue even with the newer version
