### ISSUE TITLE
2-Update-existing-WVD-host-pool : Didn't remove existing VMs

### ISSUE THREAD

**Issue by ChrisTav424** [Azure/RDS-Templates#398]
I am running the '2-Update-existing-WVD-host-pool' to update VMs with a new image. I have added the following parameters; 

```json
        "actionOnPreviousVirtualMachines": {
            "value": "Delete"
        },
        "userLogoffDelayInMinutes": {
            "value": 120
        },
        "userNotificationMessage": {
            "value": "Scheduled maintenance, please save your work and logoff as soon as possible"
        }
```

It created the two new VMs using the new image, but it didn't do anything to the existing VMs? My understanding was that it should send a message to the users and then delete them? 

![image](https://user-images.githubusercontent.com/44398463/77641365-dbdec580-6f53-11ea-8fdf-615e75a60115.png)

**Comment by nakranimohit0** [comment]
@ChrisTav424 
Assuming that you first created and provisioned a host pool with VM prefix name: 'WVD-PH' and then you ran the update template with a new VM prefix name: 'WVD-2-PH', correct ? If so, did you use the same host pool name & tenant as the ones used for 'WVD-PH' VMs ?

**Comment by ChrisTav424** [comment]
Yes I used the same host pool and tenant

**Comment by nakranimohit0** [comment]
@ChrisTav424 
Can you share the parameters that you passed to the [update template](https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Update%20existing%20WVD%20host%20pool) ? You mask/clear out any sensitive info that you'd like.

**Comment by ChrisTav424** [comment]
Of course; 

```json

{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "rdshImageSource": {
            "value": "CustomImage"
        },
        "vmImageVhdUri": {
            "value": ""
        },
        "rdshCustomImageSourceName": {
            "value": "WVD-MasterV5-image2"
        },
        "rdshCustomImageSourceResourceGroup": {
            "value": "rg-wvd-master"
        },
        "rdshNumberOfInstances": {
            "value": 2
        },
        "rdshVMDiskType": {
            "value": "Premium_LRS"
        },
        "rdshVmSize": {
            "value": "Standard_F2s_v2"
        },
        "enableAcceleratedNetworking": {
            "value": false
        },
        "rdshUseManagedDisks": {
            "value": true
        },
        "storageAccountResourceGroupName": {
            "value": "''"
        },
        "domainToJoin": {
            "value": "<removed>"
        },
        "existingDomainUPN": {
            "value": "<removed>"
        },
        "existingVnetName": {
            "value": "vnet-shared-services"
        },
        "newOrExistingVnet": {
            "value": "existing"
        },
        "virtualNetworkResourceGroupName": {
            "value": "rg-domain-prod"
        },
        "rdBrokerURL": {
            "value": "https://rdbroker.wvd.microsoft.com"
        },
        "existingTenantGroupName": {
            "value": "Default Tenant Group"
        },
        "existingTenantName": {
            "value": "Prod_Live"
        },
        "serviceMetadataLocation": {
            "value": "United-States"
        },
        "enablePersistentDesktop": {
            "value": false
        },
        "tenantAdminUpnOrApplicationId": {
            "value": "<removed>"
        },
        "isServicePrincipal": {
            "value": true
        },
        "aadTenantId": {
            "value": "<removed>"
        },
        "location": {
            "value": "uksouth"
        },
        "actionOnPreviousVirtualMachines": {
            "value": "Delete"
        },
        "userLogoffDelayInMinutes": {
            "value": 120
        },
        "userNotificationMessage": {
            "value": "Scheduled maintenance, please save your work and logoff as soon as possible"
        }
    }
}

```

**Comment by nakranimohit0** [comment]
I see that you are not specifying the param `rdshNamePrefix` which defaults to first 10 char of the resource group that you are running this template under. What's the resource group name that you are running this under ? Assuming you also didn't specify this param for create template, you will end up calling the update template with the same VM name prefix (`rdshNamePrefix`) which will not do anything (not even create new VMs as well as delete any old VMs). Can you also share the parameters you used for [create template](https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool) ?

For more info, please see my comments from this thread: https://github.com/Azure/RDS-Templates/issues/223#issuecomment-601153150

**Comment by ChrisTav424** [comment]
Oh sorry I should have said, I am using PowerShell inline parameters for that. On the update I added a 2 to the -rdshNamePrefix. 

My creation deployment was;
-rdshNamePrefix "WVD-$uOfficeID" `
Update
-rdshNamePrefix "WVD-2-$uOfficeID" `

```PowerShell

New-AzResourceGroupDeployment -Name "rds.wvd-provision-host-pool-$lOfficeID-script-$(Get-Date -Format yyyyMMddHHmmss)" `
    -ResourceGroupName $RG `
    -TemplateUri 'C:\Scripts\WVD\LIVE\WVDPool\Update\template.json' `
    -TemplateParameterFile 'C:\Scripts\WVD\LIVE\WVDPool\Update\parameters.json' `
    -rdshNamePrefix "WVD-2-$uOfficeID" `
    -existingDomainPassword $existingDomainPassword `
    -existingSubnetName "subnet-$lOfficeID" `
    -existinghostPoolName "$OfficeName-A" `
    -tenantAdminPassword $tenantAdminPassword `
    -ouPath "OU=Workstations,OU=$uOfficeID,OU=WVD,<removed>" `
    -Verbose `

```

**Comment by YariCa** [comment]
Hi, I resolved using a service principal using the following
https://www.robinhobo.com/how-to-create-an-azure-service-principal-for-use-with-windows-virtual-desktop-and-azure-arm-templates-like-the-arm-template-to-update-an-existing-windows-virtual-desktop-hostpool/

assuming that the prefix-name is different.
Yari

**Comment by nakranimohit0** [comment]
@ChrisTav424 
I should've asked this before but what's the exact error message are you getting ?

**Comment by ChrisTav424** [comment]
Oh interesting, I'll double check the service principal permissions. It must have the permissions to create but not delete? Strange it doesn't error! I'll report back

**Comment by nakranimohit0** [comment]
@ChrisTav424 
My guess is that your service principal probably has permissions to authenticate WVD but not Azure RM account. The DSC in create template will only authenticate with WVD, but the DSC in the VM `WVD-2-PH-0` of update template also needs to authenticate with Azure RM to remove old VMs.

That is strange that there was no error. can you please share the script log located in the VM ``WVD-2-PH-0`` @ C:\Windows\Temp\ScriptLog.log ? You can mask/clear any sensitive info from the log file that you'd like.

**Comment by tkneetz** [comment]
HI :) wvd tenant admin will be used to delete azure vms. I assigned contributor role to my wvdtenantadmin (only on my wvd-Ressourcegroup) and deleting old hosts was successful. 
when using same prefix deployment alos succesful but existing hosts will not be changed. with new prefix. new vms will be created and old ones will be deleted. it also working to reduce host.

Regards Tommy

**Comment by nakranimohit0** [comment]
@ChrisTav424 
Were you able to resolve this issue ? If so we can close this.

**Comment by ChrisTav424** [comment]
Sorry for not updating sooner. I am struggling a bit with the permissions as I don't see my Service Principal in IAM in order to give permissions. 

Which account is it using to remove the old VMs, is it the account I use to run Connect-AZAccount (this is my account which has Subscription Co-Administrator) or the account in the parameters JSON file under 'tenantAdminUpnOrApplicationId' (which doesn't have Subscription Co-Administrator).

If it's the 'tenantAdminUpnOrApplicationId' I can't work out how to add the permission.

**Comment by nakranimohit0** [comment]
@ChrisTav424 
This is the command it uses to authenticate with AzureRM, please run this command locally in a new PowerShell session. Templates use the same account for both WVD authentication & AzureRM authentication.

`Add-AzureRmAccount -Credential $TenantAdminCredentials -ServicePrincipal -TenantId $aadTenantId` 
Where `$TenantAdminCredentials` is `tenantAdminUpnOrApplicationId` & `tenantAdminPassword`

**Comment by tkneetz** [comment]
@ChrisTav424 
I assigned permisssions via azure portal and only to my ressouce group (all host are located in this RG). portal -> ResourceGroup -> access control -> add role assignment --> role contributor and select your user (Tenant Admin Upn) --> save

now your "Tenant Admin Upn" can delete old VMs (only in this resoucre group)

**Comment by ChrisTav424** [comment]
Ah, what I was using what the Enterprise Application account that I created at the beginning'

```PowerShell
New-AzureADApplication -AvailableToOtherTenants $true -DisplayName "Windows Virtual Desktop Svc Principal <TenantName>"
```
I had to click "Create Service Principal" in the portal to then be able to add the role assignment for the Service Principal (as it didn't show up in IAM). 

I have done that and tried to run the update template, it is running but is taking a very long time on 'dscextension' for one particular VM (23 minutes, instead of the usual 3minutes). 

I will leave it running and report back...

**Comment by ChrisTav424** [comment]
Applying the owner permissions to the resource group to the service principal and only using that the authenticate resolved this for me. 

Thanks for everyone's help.
