### ISSUE TITLE
Deployment failure with updating large host pool: RegisterSessionHostAndCleanup: An exception error occurred while running the command

### ISSUE THREAD

**Issue by martinyy108** [Azure/RDS-Templates#399]
Hi,  

We have a host pool with 32x Standard D4s v3 VMs and I have ran ito deployment failure with the update ARM template twice now.

But strange enough, I had no issue when tested the update process in a test host pool which has only one VM.

Below is the attached json file and error in Azure portal

[Deployment-Microsoft.Template (1).zip](https://github.com/Azure/RDS-Templates/files/4392278/Deployment-Microsoft.Template.1.zip)

![image](https://user-images.githubusercontent.com/39147252/77736458-57c63400-7060-11ea-9abc-a7efb4bee6ae.png)

Can you please advise? 

Regards,

Martin

**Comment by martinyy108** [comment]
Here is another screenshot of error.

![image](https://user-images.githubusercontent.com/39147252/77736551-85ab7880-7060-11ea-9ec4-7f014994c9f9.png)

But the same DSC extension was installed successfully on the other 31 VMs.

![image](https://user-images.githubusercontent.com/39147252/77736659-b1c6f980-7060-11ea-8da3-9f7802b0b613.png)

**Comment by martinyy108** [comment]
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'dscextension'. Error message: \\\"DSC Configuration 'RegisterSessionHostAndCleanup' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: An exception error occurred while running the command.\\nActivityId: 540651b9-e8be-40bb-8eac-1302e5e2db54\\nPowershell commands to diagnose the failure:\\nGet-RdsDiagnosticActivities -ActivityId 540651b9-e8be-40bb-8eac-1302e5e2db54\\n  The SendConfigurationApply function did not succeed.\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"
    }
  ]
}

**Comment by nakranimohit0** [comment]
@martinyy108 
Thanks for raising this issue.

Just an FYI, the DSC extension that gets run on other VMs vs the VM `EpaVicCorp2-0` is different. All the other VMs run DSC to simply install the agent and register to session host, but the DSC on VM `EpaVicCorp2-0` additionally deletes/deallocates the old VMs in the host pool after all the other VMs are registered and that is what's failing in your case. I'm still looking into this error and will update you ASAP.

**Comment by nakranimohit0** [comment]
@martinyy108 
Those deployment output files don't help much, can you please share the script log located in the VM `EpaVicCorp2-0` @ C:\Windows\Temp\ScriptLog.log ? You can mask/clear any sensitive info from the log file that you'd like.

**Comment by martinyy108** [comment]
Here is the log file for your review

[ScriptLog.log](https://github.com/Azure/RDS-Templates/files/4396083/ScriptLog.log)

I removed the authentication token bit and everything else is there.

**Comment by martinyy108** [comment]
Also I had no issue when updating the test host pool which has only one VM

**Comment by nakranimohit0** [comment]
@martinyy108 
Log shows that it successfully created new VMs starting with `epaviccorp2-` and deleted old VMs starting with `epaviccorp1-`. Although there was an error, the template deployment completed successfully. Were you able to reproduce this error 2nd time ?

**Comment by nakranimohit0** [comment]
@martinyy108 
To mitigate this for now, you can manually remove any old resources (if any) left behind after the update template deployment finishes.

**Comment by martinyy108** [comment]
It was already the 2nd time and I had to clean up in both WVD and Azure afterwards. But will this process be optimised by any chance?

**Comment by nakranimohit0** [comment]
@martinyy108 
I made some changes to help us diagnose/troubleshoot the errors better. Can you run your tests with the param `_artifactsLocation = "https://raw.githubusercontent.com/Azure/RDS-Templates/monakran_refactor/wvd-templates/"` ?

**Comment by martinyy108** [comment]
I will add this next time when updating host pool and let you know. Thanks

**Comment by nakranimohit0** [comment]
Closing this for now. Please reopen if the issue still exists.
