### ISSUE TITLE
Autoscale - Not seeing correct VM's in Host Pool

### ISSUE THREAD

**Issue by mgustin2020** [Azure/RDS-Templates#413]
Summary of Actions:
 
Initially created the automation account using steps outlined in https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script
At that time the VM’s in our Windows Virtual Desktop was named wvd-0 through wvd-6.  Auto scale worked as expected.
 
We had to update the gold image for the pool this week keeping the HostPool Name Pool the same (AllUsers) but the vm's in the poll changed from wvd-x to wvdd-x then a later update to wvdg-x
 
The automation account runbook runs as expected, but is not seeing the correct VM's assigned in the HostPool.  The output shows "Checking session host: wvdd-2.fqdn with a status of noHearbeat. 
Basically the updated VM names in the host pool are not being picked up.  All functionality of the Hostpool is fine - we only have this issue with the automation account auto-scale.

Have deleted the automation account, logic app and runbook in the associated resource group and re-created per documentation.  No errors, but output is the same - it is not seeing the correct VM's in the host pool.
 
Creating a new Hostpool I assume would fix this, but with over 200 users assigned that is not an option I would like to go down.

MS Azure Prem support ran out of options after a week (never really gave suggestions just took screen shots) and pointed us here.

Full Log:
![image](https://user-images.githubusercontent.com/62999258/78151949-c576b500-73fe-11ea-874b-657bfb74184e.png)

Current VM's in HostPool:
![image](https://user-images.githubusercontent.com/62999258/78152064-f1923600-73fe-11ea-8c65-7b37739e57f7.png)

**Comment by viswanadham-k** [comment]
Hi @mgustin2020 
Can you run the below cmdlet then you know about the issue.
Get-RDSSessionHost -TenantName <provide name of the tenant> -HostpoolName <provide name of the hostpool> | select SessionHostName

Reason: You are removed VMs from Azure not from WVD. So can you remove existing session hosts which are start with "wvdd-*" from WVD.

Please let me know if you are still facing issue.

Thanks

**Comment by mgustin2020** [comment]
That is exactly what the problem was - Remove-RdsSessionHost had not been ran.  Removed the old and everything is running correct.
