### ISSUE TITLE
“BadRequest” error when running the createazureautmationaccount.ps1

### ISSUE THREAD

**Issue by marvinq06** [Azure/RDS-Templates#416]
We drilled it down to the New-AzAutomationAccount commandlet where we were entering an invalid character (a hyphen) in the name. Maybe you can add validation or catching of some sort to make this easier to troubleshoot.

![image](https://user-images.githubusercontent.com/41982334/78282136-a3e5fe00-74d0-11ea-88e7-ae4d794297e2.png)

**Comment by RoopChevuri** [comment]
Thanks for the feedback. We will review this for newer versions of the tool.
