### ISSUE TITLE
Error: "features": required field is not set

### ISSUE THREAD

**Issue by jlombardo29** [Azure/RDS-Templates#419]
I get this error when running the tf plan.  

What am I missing ?

**Comment by daaadams** [comment]
I'm seeing this too.    Any updates on resolution?

Thx!

**Comment by rooso** [comment]
Having the same issue, still investigating but at this time no solution.

**Comment by rooso** [comment]
Got it - the following workaround shoud fix this: add a providers.tf file and add
`# Configure the Azure Provider
provider "azurerm" {
  version = "=2.1.0"
  features {}
}`
