### ISSUE TITLE
Feature Request - Weekend Logic for Session Hosts

### ISSUE THREAD

**Issue by jaycartel** [Azure/RDS-Templates#420]
Hi All, 

I am not sure on how to post for feature requests but would like to find out if there is a way to add some additional logic to basicscale script. 

What would be nice to have is the ability to specify the amount of session hosts on the weekend. 

What I mean by that is that for some businesses peak hours are Monday - Friday 08:00 to 17:00 and on weekends there is no need to have a session host running. When Monday comes again we can then have session hosts start up with the peak hours.

Let me know if you need further info? #420 #314

**Comment by erjosito** [comment]
Hey there, I have a version of the script where the Logic App supplies the parameter "WeekDaysPeak": "3 4 5". The PS script will then compare the current DayOfWeek with the supplied array, and assume off-peak if DayOfWeek not in the array.

Let me know if I should send a PR with the changes

**Comment by jaycartel** [comment]
> Hey there, I have a version of the script where the Logic App supplies the parameter "WeekDaysPeak": "3 4 5". The PS script will then compare the current DayOfWeek with the supplied array, and assume off-peak if DayOfWeek not in the array.
> 
> Let me know if I you are interested in a PR with the relevant changes (I still havent changed the createazurelogicapp.ps1 provisioning script)

Thank you very much for your prompt response @erjosito  - Apologies for my late response. That would be great if you can send me a link to that script. Thank you for all the efforts you have made to make this easier for everyone and is a great tool to handle the automated scaling of these WVD VM's during this tough time in the world.

**Comment by erjosito** [comment]
> That would be great if you can send me a link to that script

https://github.com/erjosito/RDS-Templates/blob/weekends/wvd-templates/wvd-scaling-script/basicScale.ps1: It uses a parameter where the weekdays to be considered as peak are passed in a blank-separated list, like "1 2 3 4 5" for example (0 is Sunday, 6 is Saturday)

**Comment by erjosito** [comment]
Hey @jaycartel I have another version of the scaling script where I unified the logic with and without logging for easier maintenance, plus other stuff (flag to prevent scaling up during off-peak, default values for some parameters if not supplied by the webhook, additional logic to catch endless loops). If interested you find it here: https://github.com/erjosito/RDS-Templates/blob/Unified/wvd-templates/wvd-scaling-script/basicScale.ps1

**Comment by jaycartel** [comment]
@erjosito - Thank you so much for including me in your new version. It is much appreciated and thank you so much for cleaning up the script and adding all the additional logic. I am very new to Gihub so still wrapping my head around messaging in here. Will test your script out as the script that was published yesterday seemed to have some issues in our evironment so will test out your versions which seem to have a bit more logic added into it. I know this is a constant work in progress and know that it all eventually will run quite smoothly. 

I have another question if you don't mind. This is unrelated and just a mere info asking question. We are currently running into issues where we are maxing the API call limits for WVD and causes some issues for some of our admins including myself to administer the solution. I suspect with the sheer number of host pools we are running we have multiple logic apps that kick off the runbook associated with logic app which is a copy of it so that we know which runbook runs for each region. 

The question I have is this: Is there a way to send through in a single webhook/logic app info relating to each hostpool and have the runbook process info for multiple host pools? I am not sure if this is making sense?

**Comment by jaycartel** [comment]
@erjosito - I have tested both of these scripts and both fail during offpeak. The PeakDay one fails here. 

Running with these control variables: 'MinimumNumberOfRDSH' = '1', 
           'PeakMinimumNumberOfRDSH': '3', 'WeekDaysPeak': '1 2 3 4 5', 
           'ScaleUpDuringOffpeak': 'False' 'SessionThresholdPerCPU': '0.5'

Authenticating as service principal for Azure. Result: 

Account                              SubscriptionName TenantId                             Environment
-------                              ---------------- --------                             -----------
2d49d66c-75cb-4515-ae1a-f126d16beb56 IG-TST01         4e4fba5b-9374-4b6e-bdac-ccfcb20786fb AzureCloud 

Sets the Azure subscription. Result: 

Name                                     Account             SubscriptionName    Environment         TenantId           
----                                     -------             ----------------    -----------         --------           
IG-TST01 (d3a0d164-9742-4106-b652-e98... 2d49d66c-75cb-45... IG-TST01            AzureCloud          4e4fba5b-9374-4b...

Authenticating as service principal for WVD. Result: 

DeploymentUrl                      TenantGroupName      UserName   
-------------                      ---------------      --------   
https://rdbroker.wvd.microsoft.com Default Tenant Group Certificate

Starting WVD tenant hosts scale optimization: Current Date Time is: 04/23/2020 18:46:45, current week day is 4

It is Off-peak hours

Starting to scale down WVD session hosts.

Processing hostpool NZA-TST01-RHP-ENG02

There are too few session hosts in this pool (), starting hosts to reach the minimum (1 hosts)
and the other one fails here. 

Authenticating as service principal for Azure. Result: 
Account                              SubscriptionName TenantId                             Environment
-------                              ---------------- --------                             -----------
2d49d66c-75cb-4515-ae1a-f126d16beb56 IG-TST01         4e4fba5b-9374-4b6e-bdac-ccfcb20786fb AzureCloud 

Sets the Azure subscription. Result: 

Name                                     Account             SubscriptionName    Environment         TenantId           
----                                     -------             ----------------    -----------         --------           
IG-TST01 (d3a0d164-9742-4106-b652-e98... 2d49d66c-75cb-45... IG-TST01            AzureCloud          4e4fba5b-9374-4b...

Authenticating as service principal for WVD. Result: 

DeploymentUrl                      TenantGroupName      UserName   
-------------                      ---------------      --------   
https://rdbroker.wvd.microsoft.com Default Tenant Group Certificate

Starting WVD tenant hosts scale optimization: Current Date Time is: 04/23/2020 18:53:30

It is Off-peak hours

Starting to scale down WVD session hosts ...

Processing hostpool NZA-TST01-RHP-ENG02

I admittedly haven't tried to troubleshoot too much but just thought I would let you know as you would know exactly where to look to find the issue.

**Comment by jaycartel** [comment]
@erjosito - The error from the non-peak day script.

Authenticating as service principal for Azure. Result: 
Account                              SubscriptionName TenantId                             Environment
-------                              ---------------- --------                             -----------
2d49d66c-75cb-4515-ae1a-f126d16beb56 IG-TST01         4e4fba5b-9374-4b6e-bdac-ccfcb20786fb AzureCloud 

Sets the Azure subscription. Result: 

Name                                     Account             SubscriptionName    Environment         TenantId           
----                                     -------             ----------------    -----------         --------           
IG-TST01 (d3a0d164-9742-4106-b652-e98... 2d49d66c-75cb-45... IG-TST01            AzureCloud          4e4fba5b-9374-4b...

Authenticating as service principal for WVD. Result: 

DeploymentUrl                      TenantGroupName      UserName   
-------------                      ---------------      --------   
https://rdbroker.wvd.microsoft.com Default Tenant Group Certificate

Starting WVD tenant hosts scale optimization: Current Date Time is: 04/23/2020 18:53:30

It is Off-peak hours

Starting to scale down WVD session hosts ...

Processing hostpool NZA-TST01-RHP-ENG02

**Comment by RoopChevuri** [comment]
We will consider this request for future release of this functionality. Thanks for sharing the feedback.
