### ISSUE TITLE
wvd-management-ux - Template deployment failed.

### ISSUE THREAD

**Issue by SirRestraint** [Azure/RDS-Templates#422]
Hello,
i tried to deploy the template and got error.

Resource: wvdsaas-autoAccount-ixsfbaw2vx43m/2729aa8f-6e02-5da2-a320-5731a8b23dbc
Type: Microsoft.Automation/automationAccounts/jobs
Status: Conflict

error: The resource operation completed with terminal provisioning state 'Failed'.

Any advice?

Regards
Stanislav

**Comment by mkolb31** [comment]
I am getting the same error
Management UX: Version 1.2.2

**Comment by mkolb31** [comment]
After configured "Contributor" permissions for the AD User on Subscription, the deployment worked.

**Comment by SirRestraint** [comment]
My account is Global admin for Sub/Tenant.
MFA turned off for this deploy just to be sure.
So problem will be elsewhere for me :(

**Comment by github-hayes** [comment]
We had a similar issue.  The site name was not globally unique.  The site name has to be unique across the entirety of azurewebsites.net

**Comment by SirRestraint** [comment]
![image](https://user-images.githubusercontent.com/47971660/79596714-575e0d80-80e1-11ea-97cb-13f1698b7d2e.png)

I tried different account and same error.
Account has no MFA, it has Contributor role in RG in Azure Sub.

Any help here?

**Comment by nakranimohit0** [comment]
@SirRestraint 
Is this about WVD management UX or the scaling script ? Please assign one of the labels.

**Comment by SirRestraint** [comment]
It is about WVD management UX and i don't see option to assign Label for some reason.
Maybe I am just blind.

**Comment by zdegraaf** [comment]
I am seeing the same issue when trying to deploy this in my tenant. I am a global admin with MFA on, and I used my own credentials in the configuration.

**Comment by SirRestraint** [comment]
> I am seeing the same issue when trying to deploy this in my tenant. I am a global admin with MFA on, and I used my own credentials in the configuration.

Since nobody was willing to help here and haven't found solution for this, I decided to remove this MGMT from my deployment and found another solution for it which work like a charm.

**Comment by SirRestraint** [comment]
Closing the issue as it is obsolete now.
