### ISSUE TITLE
deploy management portal ux issue with Conflict

### ISSUE THREAD

**Issue by ramisohail** [Azure/RDS-Templates#423]
hello all,

 

i am trying to deploy the web app managment portal from the RDS Template for WVD

 

https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/wvd-management-ux/deploy

 

however it keeps failing for me even though the user i am using is an owner , RDS Owner , not service principal and doesn't have MFA & global admin to the AD tenant

 
app registrations allowed to everyone as well, i tried running it manually from the runbook it failed as well.

 
status message

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'."
    }
}
 
attached image of the error

![wvd2](https://user-images.githubusercontent.com/24530983/78729503-e5e4c900-7942-11ea-8f5c-ba462b384cba.PNG)

**Comment by khaljimbo** [comment]
I am getting the same issue. 

I am also a Global Admin with no MFA and the RDS Admin. I have been advised my Azure Support to create my issue here.

**Comment by ramisohail** [comment]
@khaljimbo i was wondering what type of subscription are you using, is it MSDN because i am suspecting this might be related?

**Comment by khaljimbo** [comment]
@ramisohail no, I have an "Azure AD for Office 365" AD Tenant. 

I did notice that while the deployment fails at the part of the creating and running the run book in the automation account, if you browse to your management web app you will just the standard Azure web app holding page. I noticed that in the run books error logs it was telling me my account had MFA and it couldn't execute the run book (my account does not have MFA). 

I was able to run the runbook manually and it completed successfully and I am now getting styling in my management web app but it is still not working.

**Comment by igorpag** [comment]
I have the same issue, and also using MSDN subscription.

**Comment by viswanadham-k** [comment]
Hi All,
Thank you for trying to deploy management UX tool, i hope you are facing issue with template deployment.

Please  follow the below link for to troubleshoot the Management UX tool issues.
https://docs.microsoft.com/en-us/azure/virtual-desktop/troubleshoot-management-tool

Let me know if you are still facing issues.

Thanks,

**Comment by khaljimbo** [comment]
Hi @viswanadham-k 

Just confirming here that I my accounts have no MFA, roles are assigned in WVD, have contributor access at the subscription level and I am still facing the same issues. I have gone through the details in the link you posted above and I am still facing these issues.

Thanks,

**Comment by ramisohail** [comment]
hi @viswanadham-k  , i am also configrimg the same my account is contribuator , RDS Owner and no MFA at all and a global admin, i tried all the steps and it keeps failing

**Comment by viswanadham-k** [comment]
Hi @ramisohail 
Please let me know your availability time today, i will connect and assist you with resolved steps.
And let me know your mailing address i will send a meeting invitation.

Thanks,

**Comment by ramisohail** [comment]
Hi @viswanadham-k thanks a lot for offering your time & extend your support , my timing is GMT+3,
its 3:30 AM now, i will be available in the Afternoon from 3:00-4:00 PM or Anytime after 5:30 PM my time, let me know your suitable time today or any other day if you cant make it in this time.

my email is rami.sohail@gmail.com, thanks again

**Comment by ramisohail** [comment]
Thank @viswanadham-k for your support in solving, because of the mutli tenant issue the script fails since i have an MSDN Subscription and Azure AD in another tenant, so we had to fix thi smanully using the following steps:

Deploy the tool with error Failure.

go to to the app registration created by the Template deployment and grant the following api Permissions, then press on Grant Admin Consent for Tenant Name.

![image](https://user-images.githubusercontent.com/24530983/79605223-2b01bb80-80f8-11ea-93b7-3b35aaf67952.png)

then in the App Registration , get the APP ID and create Key with never expiry copy it and save it , and redploy the template with the below info:\

App iD:   copy it from the the app registration

passwork: the one you created and saved it

Then go to the App Registration and go to Authenticaiton in the Redirect URIs put the App Service link and Save.

https://yourappname-api.azurewebsites.net/ get the API Link that was deployedn in the Service plan and go the app service, put it in the App Service Advanced Settings-> then go Debug Console -> Powershell -> go to site -> wwwroot -> main.f336d560de5215b033ff.bundle.js 

press edit then copy the file to a notepad and search for App_URI, replace this with the API link you got above also make sure toremove the brackets, copy it and paste it in the editor and save the changes

delete the Automation account after the app is working successfully, Thats about it, good luck.
