### ISSUE TITLE
Error expanding existing host pool

### ISSUE THREAD

**Issue by chndrcks** [Azure/RDS-Templates#425]
I'm trying to expand an existing host pool following the instructions here https://docs.microsoft.com/en-us/azure/virtual-desktop/expand-existing-host-pool#redeploy-from-azure . I've done this successfully in the past, but now I'm getting the following error:

"Deployment template validation failed: 'The template parameters 'enablePersistentDesktop' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'VmImageVhdUri, storageAccountResourceGroupName, rdshGalleryImageSKU, rdshPrefix, rdshNumberOfInstances, rdshVMDiskType, rdshVmSize, enableAcceleratedNetworking, existingDomainusername, existingDomainPassword, vhds, subnet-id, rdshImageSourceResourceGroup, rdshImageSourceName, location, createAvailabilitySet'.

**Comment by chndrcks** [comment]
> @chndrcks
> It looks like you are using some older version of [mainTemplate.json](https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool/mainTemplate.json). Are you using [Azure Marketplace offering](https://docs.microsoft.com/en-us/azure/virtual-desktop/create-host-pools-azure-marketplace) or [GitHub Azure Resource Manager template](https://docs.microsoft.com/en-us/azure/virtual-desktop/create-host-pools-arm-template) ?

Thanks for the quick reply.

I initially created the hostpool through the Marketplace Offering  (on 3/23) then today I was trying to expand it by following the directions I linked above (specifically the Redeploy from Azure step). So maybe I could do the "Run the Azure Marketplace offering" option instead.

**Comment by nakranimohit0** [comment]
@chndrcks 
Thank you raising this. We have made a fix around this. You should be able to redeploy using older deployments now. Sorry for the trouble. Please reopen the issue if not resolved.
