### ISSUE TITLE
Auto scale not starting host when more than 1 host contain a portion of the VM Name

### ISSUE THREAD

**Issue by LeoLopezAtHL** [Azure/RDS-Templates#426]
Hi,
The auto scale fails to start a host when the name is contained on other VMs. i.e. wvd-1, wvd-11, wvd-12
In this situation the host named wvd-1 will not start because some "if conditions" will fail. The reason is because the code is pulling all vms that contain that VM name in the name instead of matching the exact name. Meaning, there is a possibility for the search to return more than one VM. Multiple values will make the script fail on the following "if condition". This line is repeated multiple times within the script.
$RoleInstance = Get-AzVM -Status | Where-Object { $_.Name.Contains($VMName) }

Since this line is within a foreach the result should be a single match. I was able to fix it by changing to
$RoleInstance = Get-AzVM -Status | Where-Object { $_.Name -eq $VMName }
Interestingly enough other parts of the script already contain this fix.

Since this is repeated multiple times within the script I assume other processes will fail as well. I just have noticed while starting the VMs.

Thanks,

**Comment by viswanadham-k** [comment]
Hi @LeoLopezAtHL 
Hi @govjobss 
We have fixed your issue in latest bits. So can you please follow the below steps and update the latest changes.

Below are the steps to update the Azure automation-based scaling tool located here to latest version
Access below link and copy the content of basicScale.ps1 code into a clipboard
https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/wvd-scaling-script/basicScale.ps1

Login to the Azure portal
In the Azure portal, select All services. In the list of resources, enter and select Automation Accounts.
On the Automation Accounts page, select the name of Automation account where you have the scaling tool hosted
Click on Runbooks under Process Automation section on the left hand side pane.
Click on PowerShell Runbook named “WVDAutoScaleRunbook”
Click on Edit from the top pane
Replace the existing code with one from Step 1
Click “Save” and “Publish”
New code will come into effect from next run of the runbook based on recurrence interval you have scheduled.

Please let me know if you are still facing issues. If it is working fine then close this issue.

Thanks

**Comment by nakranimohit0** [comment]
This was fixed in https://github.com/Azure/RDS-Templates/pull/467
