### ISSUE TITLE
Management UX - blank screen when built with service principal

### ISSUE THREAD

**Issue by ChrisTav424** [Azure/RDS-Templates#428]
I tried to build the WVD Management UX today with a service principal using the "Deploy to Azure" GUI template.

The deployment was successful but when I loaded the web app for the first time it displayed this after authorising;

![07152FC0-7CB8-4E15-B703-6FA0BF9550E2](https://user-images.githubusercontent.com/44398463/79023120-6b50bf00-7b77-11ea-9964-f3f0a116f284.png)

I created a global admin account with owner permissions over the resource group and this was successful. 

What permissions / configuration does the Service Principal need in order for it to work?

**Comment by ChrisTav424** [comment]
Screenshot of deployment showing as success but I believe missing automation steps? 

![62E35C9A-9D95-4C69-9E78-B39613E12BB6](https://user-images.githubusercontent.com/44398463/79023551-8112b400-7b78-11ea-8f7b-b162d6dbe94b.jpeg)

**Comment by ChrisTav424** [comment]
Screenshot of deployment showing as success but I believe missing automation steps? 

![8F82FCDD-A765-4876-89C6-909C769247C9](https://user-images.githubusercontent.com/44398463/79023647-b919f700-7b78-11ea-9417-cb9683e5e16b.jpeg)

**Comment by voltaire-at-coretek** [comment]
Ran into the same issue. Found out that the account used to deploy the App must have Contributor privileges to the Azure Subscription.

**Comment by ChrisTav424** [comment]
Ahah, I definitely didn't give it that. I'll try tomorrow!
