### ISSUE TITLE
MegaPools variant won't work against the same RG multiple times

### ISSUE THREAD

**Issue by EvanBasalik** [Azure/RDS-Templates#430]
This is because the linked template name isn't unique when run multiple times.

Can you look at adding a GUID to the vmTemplateName? 

https://raw.githubusercontent.com/Azure/RDS-Templates/noAVSetSlowerHostAvailableCheck_20200218.1900_v1/wvd-templates/Create%20and%20provision%20WVD%20host%20pool/mainTemplate.json

        "vmTemplateName": "[concat( if(variables('rdshManagedDisks'), 'managedDisks', 'unmanagedDisks'), '-', toLower(replace(parameters('rdshImageSource'),' ', '')), 'vm')]",

**Comment by nakranimohit0** [comment]
Closing this out as discussed over the email, it wouldn't affect the mega pool script as the linked template name is unique per VM name prefix.
