### ISSUE TITLE
Change Logic App action from Webhook to HTTP request

### ISSUE THREAD

**Issue by erjosito** [Azure/RDS-Templates#431]
This is a feature request

Essentially the deployment script creates a Logic App sending Webhooks to Azure Automation. The problem is that Webhooks wait for Azure Automation to reply and unsubscribe, to notify of the successful completion. However, that callback never happens. As a result, all executions are stuck at "Running"

A possibility might be changing the Webhook to a standard HTTP POST call, so that it is marked as complete right after firing it off.

Please let me know if this is something you would look into, and if I can contribute to the required code changes.

**Comment by viswanadham-k** [comment]
Hi @erjosito 
Thank you for giving your feedback.
We have aligned code as per your request, it is in testing phase once done will update you soon.

Thanks,

**Comment by erjosito** [comment]
BTW, now that we are at it: what is the value of the Logic App? Why not using the schedule functionality of Azure Automation?

**Comment by nakranimohit0** [comment]
@erjosito 
The advantage of having logic app is that you can easily modify those parameters such as begin peak time, end peak time using UI. With jobs schedule, there is no way but to redeploy using ARM.

**Comment by RoopChevuri** [comment]
We have updated this in latest version here :  https://github.com/nakranimohit0/azure-docs/blob/yammer_private_preview_wvd_scaling/articles/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script.md . Wondering if you could validate and confirm if it works. This version will be released broadly in few weeks.
