### ISSUE TITLE
Not all Available session hosts are being included in $NumberOfRunningHost

### ISSUE THREAD

**Issue by AAdamCCox** [Azure/RDS-Templates#432]
When running for one of our hostpools, basicScale.ps1 returns an incorrect value for $NumberOfRunningHost, as it appears that one particular host in the pool (wvd-stud-prd-1, which is both running and Available) is not included. Powering on or off other hosts increases or decreases the value accordingly, but this particular host is never included in the count.

Example runbook job output is below (note that three hosts have `status: Available`)
```
Starting WVD tenant hosts scale optimization: Current Date Time is: 04/16/2020 09:18:37

It is in peak hours now

Starting session hosts as needed based on current workloads.

Checking session host: wvd-stud-prd-0.xxx
  of sessions: 1 and status: Available

Checking session host: wvd-stud-prd-1.xxx
  of sessions: 0 and status: Available

Checking session host: wvd-stud-prd-2.xxx
  of sessions: 0 and status: NoHeartbeat

Checking session host: wvd-stud-prd-3.xxx
  of sessions: 0 and status: Available

Current number of running hosts:2

Current total number of user sessions: 1

Current available session capacity is: 35.84

HostpoolName: Student-Desktop, TotalRunningCores: 32 NumberOfRunningHosts: 2

End WVD tenant scale optimization.
```

**Comment by viswanadham-k** [comment]
Hi @AAdamCCox 
In our environment is working fine and also available session hosts are being included in $NumberOfRunningHost. For your reference please find below output.

Authenticating as service principal for WVD. Result: 

DeploymentUrl                      TenantGroupName      UserName   
-------------                      ---------------      --------   
https://rdbroker.wvd.microsoft.com Default Tenant Group Certificate

Starting WVD tenant hosts scale optimization: Current Date Time is: 04/16/2020 20:45:02

It is in peak hours now

Starting session hosts as needed based on current workloads.

Session host is in maintenance: SalesM-Desk-01, so script will skip this VM

Checking session host: SalesM-Desk-02.ContosoWVD.onmicrosoft.com
  of sessions: 0 and status: Available

Session host is in maintenance: SalesM-Desk-03, so script will skip this VM

Checking session host: SalesM-Desk-04.ContosoWVD.onmicrosoft.com
  of sessions: 0 and status: Available

Checking session host: SalesM-Desk-05.ContosoWVD.onmicrosoft.com
  of sessions: 0 and status: Available

Current number of running hosts:3

Current total number of user sessions: 0

Current available session capacity is: 9.0

HostpoolName: Sales and marketing, TotalRunningCores: 6 NumberOfRunningHosts: 3

End WVD tenant scale optimization.

Thanks,

**Comment by AAdamCCox** [comment]
I've reproduced the issue and traced its cause to line 1056 of basicScale.ps1:
```
$RoleInstance = Get-AzVM -Status | Where-Object { $_.Name.Contains($VMName) }
```
In our environment, naming of the VMs creates an issue here, because multiple VM names match this Where-Object clause. The result is that $RoleInstance returns the following:

```
VMName = wvd-stud-prd-1

RoleInstance =
ResourceGroupName Name            PowerState
----------------- ----            ----------
RG-WVD-PRD-WE-1   wvd-stud-prd-1  VM running
RG-WVD-PRD-WE-1   wvd-stud-prd-10 VM deallocated
RG-WVD-PRD-WE-1   wvd-stud-prd-11 VM deallocated
RG-WVD-PRD-WE-1   wvd-stud-prd-12 VM deallocated
RG-WVD-PRD-WE-1   wvd-stud-prd-13 VM deallocated
RG-WVD-PRD-WE-1   wvd-stud-prd-14 VM deallocated
RG-WVD-PRD-WE-1   wvd-stud-prd-15 VM deallocated
```

Therefore in this case, $RoleInstance contains a total of seven VMs instead of just the intended one.

I fixed the issue in our environment by amending line 1056 to:
```
$RoleInstance = Get-AzVM -Status | Where-Object { $_.Name -eq $VMName }
```

**Comment by AAdamCCox** [comment]
$RoleInstance is defined in a total of 20 locations within the script. Ten of these use "Contains" while the other ten use "Eq". Based on my testing, consistently using "Eq" for all should correct the issue.

**Comment by viswanadham-k** [comment]
Hi @AAdamCCox 
Hi @govjobss 
We have fixed your issue in latest bits. So can you please follow the below steps and update the latest changes.

Below are the steps to update the Azure automation-based scaling tool located here to latest version
Access below link and copy the content of basicScale.ps1 code into a clipboard
https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/wvd-scaling-script/basicScale.ps1

Login to the Azure portal
In the Azure portal, select All services. In the list of resources, enter and select Automation Accounts.
On the Automation Accounts page, select the name of Automation account where you have the scaling tool hosted
Click on Runbooks under Process Automation section on the left hand side pane.
Click on PowerShell Runbook named “WVDAutoScaleRunbook”
Click on Edit from the top pane
Replace the existing code with one from Step 1
Click “Save” and “Publish”
New code will come into effect from next run of the runbook based on recurrence interval you have scheduled.

Please let me know if you are still facing issues. If it is working fine then close this issue.

Thanks

**Comment by nakranimohit0** [comment]
This was fixed in PR https://github.com/Azure/RDS-Templates/pull/467

**Comment by nakranimohit0** [comment]
This is a also a duplicate to #461

**Comment by AAdamCCox** [comment]
Duplicate of #426
