### ISSUE TITLE
VM has reported a failure when processing extension 'joindomain'. Error message: \\\"Exception(s) occured while joining Domain

### ISSUE THREAD

**Issue by ram-suresh** [Azure/RDS-Templates#434]
Hi,

I have provided all the required details when trying to create Windows Virtual Desktop - Provision a host pool.  I am getting the error "The resource operation completed with terminal provisioning state 'Failed'.

I deleted the entire resource group and started from scratch but still I am getting the same error. 

The status message is as mentioned below.

`"statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceDeploymentFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"VMExtensionProvisioningError\",\"message\":\"VM has reported a failure when processing extension 'joindomain'. Error message: \\\"Exception(s) occured while joining Domain 'devopspeople.com'\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot \"}]}}"`

Can someone pls guide me on where am I doing wrong.

**Comment by nakranimohit0** [comment]
@ram-suresh 
As the error says, VM failed to join the domain, please make sure correct values are specified for the parameters: `domainToJoin`, `ouPath`, `existingDomainUPN`, `existingDomainPassword`. Please try to manually join a VM to the domain with these properties to test.

**Comment by nakranimohit0** [comment]
@ram-suresh 
Was this resolved ? If so, please close this.

**Comment by thecherrytree** [comment]
@nakranimohit0 - is there more information one can obtain than the very generic error message?

**Comment by nakranimohit0** [comment]
@thecherrytree 
Yes https://aka.ms/vmextensionwindowstroubleshoot

**Comment by thecherrytree** [comment]
@nakranimohit0 - not more documentation, more logging. The logging is not helpful. When a domainjoinextension fails, stating in the logs that the domainjoin failed isn't as helpful as giving some sort of indication as to why. There are numerous reasons it can fail, including the firewalls.

**Comment by nakranimohit0** [comment]
@thecherrytree 
WVD ARM templates don't control logging on domain join or even how they work. Its a VM extension that the ARM templates simply defines the resource with the parameters. https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-domain-join-existing

**Comment by nakranimohit0** [comment]
@stgeorgi Any thoughts here ?

**Comment by thecherrytree** [comment]
Will the VM itself specify more robust logging?

**Comment by stgeorgi** [comment]
Yes,  in the VM itself there are more logs have you looked at this

C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.3\Downloads\11 <<< downloads C:\WindowsAzure\Logs\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.3 <<< logs

I toubleshoot with those. We cannot really expose some of htat stuff as it happens outside of ARM

**Comment by thecherrytree** [comment]
@stgeorgi, not these. We'll have a look and see if they cover what we're looking for and respond back. Thank you both, @stgeorgi and @nakranimohit0!

**Comment by thecherrytree** [comment]
These do not exist on the provisioned VM:
> C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.3\Downloads\11 <<< downloads C:\WindowsAzure\Logs\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.3 <<< logs

The information that was useful to us is: 
`C:\Windows\debug/NetSetup.txt`

**Comment by nakranimohit0** [comment]
@thecherrytree 
As from the documentation "2. Check the actual extension logs for more details in C:\WindowsAzure\Logs\Plugins<extensionName>"
This might also help C:\WindowsAzure\Logs\Plugins\Microsoft.Compute.JsonADDomainExtension

**Comment by thecherrytree** [comment]
We had a look at those, they all essentially say timeout. We ended up looking at out network traffic logs from the VM's IP address and see some ports that are blocked. This is ultimately what is causing the issue.
