### ISSUE TITLE
Successful deployment when domain-join extension failed

### ISSUE THREAD

**Issue by Chai-NED** [Azure/RDS-Templates#438]
My deployment steps were all green, but in fact the domain-join extension had failed. The new host did not get added to the existing hostpool.

**Comment by nakranimohit0** [comment]
@Chai-NED 
Is this about adding VMs to existing WVD host pool ? How are calling the templates or what steps are you following ?

**Comment by Chai-NED** [comment]
I was trying to update the session host with a new image. It turned out I had a typo in the domain-join UPN which caused the domain-join extension to fail, but the template deployment said otherwise.

Thanks,

Chai

________________________________

**Comment by nakranimohit0** [comment]
@Chai-NED 
Screenshots of the template deployment output/result and domain join error would help.

**Comment by Chai-NED** [comment]
Bummer. I did not capture the screenshot. But this is super easy to reproduce. All you have to do is run the template with an incorrect user to join a domain.

**Comment by nakranimohit0** [comment]
@Chai-NED 
I'm not able to repro, this is what I see: the domain join & final deployment both shown as failed. I also got an error in my PowerShell window where I ran the command to deploy the template. Closing this for now, please reopen if the issue happens again.

![image](https://user-images.githubusercontent.com/8796443/80122744-ceacfa80-8542-11ea-9830-f905d8d798e1.png)
