### ISSUE TITLE
feature request - block new sessions in the session host before the scale in process

### ISSUE THREAD

**Issue by matiasma** [Azure/RDS-Templates#440]
About  wvd-templates/wvd-scaling-script/basicScale.ps1 :

Is it possible to block new user sessions in the VM before the shutdown action, to avoid the broker to send some user to this VM until the heardbeat check failed?

My suggestion is to add something like "Set-RdsSessionHost -TenantName $TenantName -HostPoolName $HostpoolName -Name $SessionHostName -AllowNewSession $false" in the "Stop-SessionHost" function, before the VM shutdown itself

**Comment by viswanadham-k** [comment]
Hi @matiasma 
Thank you for your suggestion, we already added this feature. You can use this feature by deploying latest scaling tool.

Thanks

**Comment by matiasma** [comment]
> Hi @matiasma
> Thank you for your suggestion, we already added this feature. You can use this feature by deploying latest scaling tool.
> 
> Thanks

Hi @viswanadham-k , thanks for your return.

Now I'm using the latest version of this script (https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/wvd-scaling-script/basicScale.ps1), but now the scale in is not working anymore...  (before the update it was working, except the drain mode before the VM shutdown)

I have only one active session (as you can see in the first picture). You can see also my parameters in the logicapp (second picture)

<img width="495" alt="scalein" src="https://user-images.githubusercontent.com/11441132/80393736-510d2580-8887-11ea-9cb7-c772da361d45.PNG">

<img width="292" alt="logicapp" src="https://user-images.githubusercontent.com/11441132/80394096-c37e0580-8887-11ea-955d-e887acf41148.PNG">

**Comment by matiasma** [comment]
with a host pool with zero connections, the scale in worked again, but the allownewsession flag didn't change.

In my tests this flag only changes in the scale out procedure, but not in the scale in.

<img width="440" alt="job" src="https://user-images.githubusercontent.com/11441132/80396450-09889880-888b-11ea-9217-4a449b3276b5.PNG">

<img width="353" alt="statusafter" src="https://user-images.githubusercontent.com/11441132/80396458-0c838900-888b-11ea-84f9-dd0c73f0512c.PNG">

**Comment by matiasma** [comment]
Hi @viswanadham-k  , take a look at this current code.

When we have no session in the session host (off peak hours) it justs shutdown the VM, with no change in the AllowNewSession flag.

This flag is only changed to False if we have at least one user session in the session host.

`# Breadth first session hosts shutdown in off peak hours
		if ($NumberOfRunningHost -gt $MinimumNumberOfRDSH) {
			foreach ($SessionHost in $AllSessionHosts) {
				#Check the status of the session host
				if ($SessionHost.Status -ne "NoHeartbeat" -or $SessionHost.Status -ne "Unavailable") {
					if ($NumberOfRunningHost -gt $MinimumNumberOfRDSH) {
						$SessionHostName = $SessionHost.SessionHostName
						$VMName = $SessionHostName.Split(".")[0]
						if ($SessionHost.Sessions -eq 0) {
							# Shutdown the Azure VM, which session host have 0 sessions
							Write-Output "Stopping Azure VM: $VMName and waiting for it to complete ..."
							$LogMessage = @{ hostpoolName_s = $HostpoolName; logmessage_s = "Stopping Azure VM: $VMName and waiting for it to complete ..." }
							Add-LogEntry -LogMessageObj $LogMessage -LogAnalyticsWorkspaceId $LogAnalyticsWorkspaceId -LogAnalyticsPrimaryKey $LogAnalyticsPrimaryKey -logType "WVDTenantScale_CL" -TimeDifferenceInHours $TimeDifference
							Stop-SessionHost -VMName $VMName -LogAnalyticsWorkspaceId $LogAnalyticsWorkspaceId -LogAnalyticsPrimaryKey $LogAnalyticsPrimaryKey -TimeDifference $TimeDifference
						}`

My suggestion is to set the Drain Mode always before the VM shutdown, with or with no active user session, to avoid failure when the broker sends a user to a VM that is in the shutdown process.

I believe you could move up the entire "drain mode" try/catch code before `if ($SessionHost.Sessions -eq 0)`.

Does it make sense?

**Comment by viswanadham-k** [comment]
Hi @matiasma 
Please let me know  your availability time today. Then i will connect and assist you to resolve your issue. Kindly share your mailing address then i will send a meeting invitation.

Thanks

**Comment by matiasma** [comment]
hi @viswanadham-k , my subscription was disabled by reached spend limit (MSDN)... I need to recreate this environment in another subscription, to test the code change I proposed above.

**Comment by matiasma** [comment]
hi @viswanadham-k , my suggestion it's working very well in my new test environment. I'm closing this feature request, to create a pull request. Thank you!

<img width="1083" alt="work" src="https://user-images.githubusercontent.com/11441132/80545650-45565780-898a-11ea-8d7f-bde07cae11a5.PNG">
