### ISSUE TITLE
In Script-RegisterSessionHost.ps1 back ticks are used

### ISSUE THREAD

**Issue by JimMoyle** [Azure/RDS-Templates#451]
lines 109 to 112 backticks shouldn't be used in code as a single space after a tick will cause errors

Use splatting instead to make readable.

https://ramblingcookiemonster.wordpress.com/2014/12/01/powershell-splatting-build-parameters-dynamically/

**Comment by nakranimohit0** [comment]
@JimMoyle 
Thank you for raising this. What kind of error do you get ? How can I generate one ?

**Comment by JimMoyle** [comment]
Add a space after the back tick and see if the script runs…….

**Comment by nakranimohit0** [comment]
Fixed in #497
