### ISSUE TITLE
wvd autoscale off peak shuts down non-running vms

### ISSUE THREAD

**Issue by minnisp** [Azure/RDS-Templates#458]
updated to the 4/21 version. But in the snip below, rdshgpulab-2 vm was not running but the script tries to shut it down anyway and doesn't shut down one of the running vms that should be shutdown. also, it reports that only one VM is running when two are running. 
![image](https://user-images.githubusercontent.com/52018536/80659209-e5c18000-8a4d-11ea-953e-299f50d12f63.png)

**Comment by viswanadham-k** [comment]
Hi @minnisp 
Can you please run the below cmdlet in your environment and share with me output.
Get-RdsSessionHost -TenantName "Provide your wvd tenanatname" -HostPoolName "Provide your hostpoolname"

Thanks,

**Comment by minnisp** [comment]
I see there’s an error on that host. What does it mean?


PS C:WINDOWSsystem32> Get-RdsSessionHost -TenantName unowvdtenant1 -HostPoolName StudentGPUlabPool
SessionHostName    : rdshGPULab-0.uno.edu
TenantName         : unowvdtenant1
TenantGroupName    : Default Tenant Group
HostPoolName       : StudentGPUlabPool
AllowNewSession    : True
Sessions           : 3
LastHeartBeat      : 4/30/2020 6:15:40 PM
AgentVersion       : 1.0.1932.4800
AssignedUser       :
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 4/28/2020 10:48:12 PM
UpdateErrorMessage :
SessionHostName    : rdshGPULab-1.uno.edu
TenantName         : unowvdtenant1
TenantGroupName    : Default Tenant Group
HostPoolName       : StudentGPUlabPool
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 4/30/2020 12:03:29 AM
AgentVersion       : 1.0.1932.4800
AssignedUser       :
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Unavailable
UpdateState        : Succeeded
LastUpdateTime     : 4/26/2020 1:18:50 AM
UpdateErrorMessage :
SessionHostName    : rdshGPULab-2.uno.edu
TenantName         : unowvdtenant1
TenantGroupName    : Default Tenant Group
HostPoolName       : StudentGPUlabPool
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 4/13/2020 4:18:51 PM
AgentVersion       : 1.0.1800.1300
AssignedUser       :
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Unavailable
UpdateState        : Succeeded
LastUpdateTime     : 3/28/2020 9:28:36 PM
UpdateErrorMessage : Agent cannot connect to broker with error NOT_FOUND. URL:
                    wss://rdbroker.wvd.microsoft.com//api/rdAgent/v1
SessionHostName    : rdshGPULab-3.uno.edu
TenantName         : unowvdtenant1
TenantGroupName    : Default Tenant Group
HostPoolName       : StudentGPUlabPool
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 4/10/2020 3:57:04 AM
AgentVersion       : 1.0.1800.1300
AssignedUser       :
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Unavailable
UpdateState        : Succeeded
LastUpdateTime     : 3/28/2020 9:46:17 PM
UpdateErrorMessage :
SessionHostName    : rdshGPULab-4.uno.edu
TenantName         : unowvdtenant1
TenantGroupName    : Default Tenant Group
HostPoolName       : StudentGPUlabPool
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 4/10/2020 3:57:16 AM
AgentVersion       : 1.0.1800.1300
AssignedUser       :
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Unavailable
UpdateState        : Succeeded
LastUpdateTime     : 3/28/2020 9:23:55 PM
UpdateErrorMessage :
SessionHostName    : rdshGPULab-5.uno.edu
TenantName         : unowvdtenant1
TenantGroupName    : Default Tenant Group
HostPoolName       : StudentGPUlabPool
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 4/10/2020 3:57:29 AM
AgentVersion       : 1.0.1800.1300
AssignedUser       :
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Unavailable
UpdateState        : Succeeded
LastUpdateTime     : 3/28/2020 9:25:26 PM
UpdateErrorMessage :
Pierre Minnis, Associate CIO
Information Technology
University of New Orleans

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by viswanadham-k** [comment]
Hi @minnisp 
It seems some of the session hosts **AgentVersion** is not updated with latest version i.e., "**1.0.1932.4800**". Please check below session hosts agentversion is "1.0.1800.1300". So kindly restart the below session hosts in your off peak time then it will automatically upgraded to latest agentversion then script will work properly.

SessionHostName    : rdshGPULab-2.uno.edu
SessionHostName    : rdshGPULab-3.uno.edu
SessionHostName    : rdshGPULab-4.uno.edu
SessionHostName    : rdshGPULab-5.uno.edu

Thanks

**Comment by minnisp** [comment]
Ok thank you, we’ll update them.

Does this autoscale solution work with the new arm version of WVD?

P

**Comment by minnisp** [comment]
Same results. Not even close

[cid:image003.png@01D62268.6BC05BC0]
[cid:image004.png@01D62268.6BC05BC0]

**Comment by minnisp** [comment]
Rdshgpulab-1 was deallocated

From: pierre minnis
Sent: Monday, May 4, 2020 11:05 PM
To: 'Azure/RDS-Templates' <reply@reply.github.com>; Azure/RDS-Templates <RDS-Templates@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/RDS-Templates] wvd autoscale off peak shuts down non-running vms (#458)

Same results. Not even close

[cid:image001.png@01D62268.8BCB54B0]
[cid:image002.png@01D62268.8BCB54B0]

**Comment by mgustin2020** [comment]
This issue was open under #410 - worked for a few days then back to the same result.  As described above it is trying to shutdown already shutdown hosts and does not touch the running hosts until it has zero sessions.  Have made zero changes from when it did work last week.  Given the number of issues reported on this it seems it should get addressed.

**Comment by mgustin2020** [comment]
I see we have a new basicScale.ps1 published May 6 - will report results.

**Comment by viswanadham-k** [comment]
Hi @minnisp 
We have published latest build today May 7.  So can you please follow the below steps and update the latest changes.

Below are the steps to update the Azure automation-based scaling tool located here to latest version
Access below link and copy the content of basicScale.ps1 code into a clipboard
https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/wvd-scaling-script/basicScale.ps1

Login to the Azure portal
In the Azure portal, select All services. In the list of resources, enter and select Automation Accounts.
On the Automation Accounts page, select the name of Automation account where you have the scaling tool hosted
Click on Runbooks under Process Automation section on the left hand side pane.
Click on PowerShell Runbook named “WVDAutoScaleRunbook”
Click on Edit from the top pane
Replace the existing code with one from Step 1
Click “Save” and “Publish”
New code will come into effect from next run of the runbook based on recurrence interval you have scheduled.

Please let me know if you are still facing issues. If it is working fine then close this issue.

Thanks

**Comment by mgustin2020** [comment]
Confirming the May 7th update corrected issue.

**Comment by minnisp** [comment]
were runnig the new script now well see how it works off peak hours and report back

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mgustin2020** [comment]
Second night and works exactly as it should.  First time we have had two days in a row.  Nice work and glad this is fixed.
