### ISSUE TITLE
Bug: scaling tool will stop a session host that is already stopped and will falsely end up decrementing the number of running hosts / cores

### ISSUE THREAD

**Issue by nakranimohit0** [Azure/RDS-Templates#461]
Bug: scaling tool will stop a session host that is already stopped and will falsely end up decrementing the number of running hosts / cores because of the following lines:

https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/wvd-scaling-script/basicScale.ps1#L613
`if ($SessionHost.Status -ne "NoHeartbeat" -or $SessionHost.Status -ne "Unavailable") {`
The above statement will always result in `$true`. `-or` should be `-and`

The same here as well: https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/wvd-scaling-script/basicScale.ps1#L1276

**Comment by Meyers93** [comment]
Unfortunately, this workaround does not work for me.... still in the loop to wait until the VM is shutted down. Runbook still fails after a while... 
I changed "or" to "and".

**Comment by nakranimohit0** [comment]
@Meyers93 
Thank you for raising your concern. I opened this issue as a bug. It is not meant to fix the particular issue you are running into. I suggest you open a separate issue for your case.
