### ISSUE TITLE
4-WVD-scaling-script 

### ISSUE THREAD

**Issue by jrruado** [Azure/RDS-Templates#462]
I have total of 11 Host. 
All of them are running. From Host-0 to Host-10

Scale run book report.
Current number of running hosts:10
Current available session capacity is: 480
HostpoolName: New Host Pool, TotalRunningCores: 80 NumberOfRunningHosts: 10
End WVD tenant scale optimization.

I have 1 missing host?.
I am thinking to redepoy it. But how to remove the previous one?

**Comment by jrruado** [comment]
@nakranimohito all 11 session host are available with 8 core each so my expectation the total core is 88. However script only detect 10 session host.

**Comment by viswanadham-k** [comment]
Hi @jrruado 
Can you please run the below cmdlet in your environment and share with me output.
Get-RdsSessionHost -TenantName "Provide your wvd tenanatname" -HostPoolName "Provide your hostpoolname"

Thanks

**Comment by jrruado** [comment]
@ viswanadham-k thank you for your response. Below is the output from the command

PS C:\temp> Get-RdsSessionHost -TenantName "sbcwvd" -HostPoolName "sbchostpool01"

SessionHostName    : sbcwvd-ipcsg-0.companyxx.com
TenantName         : sbcwvd
TenantGroupName    : Default Tenant Group
HostPoolName       : sbchostpool01
AllowNewSession    : True
Sessions           : 1
LastHeartBeat      : 5/4/2020 6:36:34 AM
AgentVersion       : 1.0.1932.4800
AssignedUser       : 
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 5/4/2020 5:22:33 AM
UpdateErrorMessage : 

SessionHostName    : sbcwvd-ipcsg-1.companyxx.com
TenantName         : sbcwvd
TenantGroupName    : Default Tenant Group
HostPoolName       : sbchostpool01
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 5/4/2020 6:36:24 AM
AgentVersion       : 1.0.1932.4800
AssignedUser       : 
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 5/4/2020 5:26:29 AM
UpdateErrorMessage : 

SessionHostName    : sbcwvd-ipcsg-10.companyxx.com
TenantName         : sbcwvd
TenantGroupName    : Default Tenant Group
HostPoolName       : sbchostpool01
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 5/4/2020 6:37:19 AM
AgentVersion       : 1.0.1932.4800
AssignedUser       : 
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 5/4/2020 5:26:47 AM
UpdateErrorMessage : 

SessionHostName    : sbcwvd-ipcsg-2.companyxx.com
TenantName         : sbcwvd
TenantGroupName    : Default Tenant Group
HostPoolName       : sbchostpool01
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 5/4/2020 6:36:30 AM
AgentVersion       : 1.0.1932.4800
AssignedUser       : 
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 5/4/2020 5:26:35 AM
UpdateErrorMessage : 

SessionHostName    : sbcwvd-ipcsg-3.companyxx.com
TenantName         : sbcwvd
TenantGroupName    : Default Tenant Group
HostPoolName       : sbchostpool01
AllowNewSession    : True
Sessions           : 1
LastHeartBeat      : 5/4/2020 6:36:25 AM
AgentVersion       : 1.0.1932.4800
AssignedUser       : 
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 5/4/2020 5:26:29 AM
UpdateErrorMessage : 

SessionHostName    : sbcwvd-ipcsg-4.companyxx.com
TenantName         : sbcwvd
TenantGroupName    : Default Tenant Group
HostPoolName       : sbchostpool01
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 5/4/2020 6:36:31 AM
AgentVersion       : 1.0.1932.4800
AssignedUser       : 
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 5/4/2020 5:26:36 AM
UpdateErrorMessage : 

SessionHostName    : sbcwvd-ipcsg-5.companyxx.com
TenantName         : sbcwvd
TenantGroupName    : Default Tenant Group
HostPoolName       : sbchostpool01
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 5/4/2020 6:36:25 AM
AgentVersion       : 1.0.1932.4800
AssignedUser       : 
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 5/4/2020 5:26:24 AM
UpdateErrorMessage : 

SessionHostName    : sbcwvd-ipcsg-6.companyxx.com
TenantName         : sbcwvd
TenantGroupName    : Default Tenant Group
HostPoolName       : sbchostpool01
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 5/4/2020 6:36:44 AM
AgentVersion       : 1.0.1932.4800
AssignedUser       : 
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 5/4/2020 5:26:50 AM
UpdateErrorMessage : 

SessionHostName    : sbcwvd-ipcsg-7.companyxx.com
TenantName         : sbcwvd
TenantGroupName    : Default Tenant Group
HostPoolName       : sbchostpool01
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 5/4/2020 6:36:23 AM
AgentVersion       : 1.0.1932.4800
AssignedUser       : 
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 5/4/2020 5:26:52 AM
UpdateErrorMessage : 

SessionHostName    : sbcwvd-ipcsg-8.companyxx.com
TenantName         : sbcwvd
TenantGroupName    : Default Tenant Group
HostPoolName       : sbchostpool01
AllowNewSession    : True
Sessions           : 1
LastHeartBeat      : 5/4/2020 6:36:40 AM
AgentVersion       : 1.0.1932.4800
AssignedUser       : 
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 5/4/2020 5:27:07 AM
UpdateErrorMessage : 

SessionHostName    : sbcwvd-ipcsg-9.companyxx.com
TenantName         : sbcwvd
TenantGroupName    : Default Tenant Group
HostPoolName       : sbchostpool01
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 5/4/2020 6:36:24 AM
AgentVersion       : 1.0.1932.4800
AssignedUser       : 
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 5/4/2020 5:26:23 AM
UpdateErrorMessage :

**Comment by jrruado** [comment]
I got fixed from other issue and it resolved.
