### ISSUE TITLE
WVD Autoscale not working properly Off-Peak hours

### ISSUE THREAD

**Issue by Ar-Sa** [Azure/RDS-Templates#463]
hi, we tried to setup autoscale with "LimitSecondsToForceLogOffUser": 0 so that sessions will not get forced logoff and it worked fine. 

i checked runbook job output and the runbook was able to stop 2 host without any session during not peak hours  but at the same time runbook set no new sessions on RUNNING  vm and set allow new sessions on stopped vm's  due to which i was not able to connect to WVD instead of having 2 host running.

**Comment by viswanadham-k** [comment]
Hi @govjobss 
We have fixed this issue in latest bits. So can you please follow the below steps and update the latest changes.

Below are the steps to update the Azure automation-based scaling tool located here to latest version
Access below link and copy the content of basicScale.ps1 code into a clipboard
https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/wvd-scaling-script/basicScale.ps1

Login to the Azure portal
In the Azure portal, select All services. In the list of resources, enter and select Automation Accounts.
On the Automation Accounts page, select the name of Automation account where you have the scaling tool hosted
Click on Runbooks under Process Automation section on the left hand side pane.
Click on PowerShell Runbook named “WVDAutoScaleRunbook”
Click on Edit from the top pane
Replace the existing code with one from Step 1
Click “Save” and “Publish”
New code will come into effect from next run of the runbook based on recurrence interval you have scheduled.

Please let me know if you are still facing issues. If it is working fine then close this issue.

Thanks

**Comment by nakranimohit0** [comment]
Closing this out as there was no response, please re open if the issue still exists
