### ISSUE TITLE
Scaling Script error on scale-in

### ISSUE THREAD

**Issue by alchemytechgroup0n123** [Azure/RDS-Templates#464]
Line: 733

if ($SessionHostInfo.UpdateState -eq "Succeeded" -and $SessionHostInfo.Status -eq "NoHeartbeat" -or $SessionHost.Status -eq "Unavailable") {

should be set to 

if ($SessionHostInfo.UpdateState -eq "Succeeded" -and $SessionHostInfo.Status -eq "NoHeartbeat" -or $SessionHostInfo.Status -eq "Unavailable") {

**Comment by cookiekaikai** [comment]
Can you post the steps to make this change?  thanks

**Comment by nakranimohit0** [comment]
Closing this out as a duplicate to #461
