### ISSUE TITLE
WVD Auto Scale Script: issue with off peak hours, shutting down VMs with user sessions

### ISSUE THREAD

**Issue by YariCa** [Azure/RDS-Templates#466]
Autoscale script seems not working correctly after peek hours.
it seems that the script hang on waiting the VM to stop.
the last lines of the log
processing hostpool POOL1
Stopping Azure VM: VM1 and waiting for it to complete ...
Azure VM has been stopped: VM1 ...

and then the script timed out (after 3 hours)
**Exception**: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: ActivityId: Powershell commands to diagnose the failure: Get-RdsDiagnosticActivities -ActivityId

next time, same host pool, we have this
Starting to scale down WVD session hosts ...
Processing hostpool POOL1

**exception**: Cannot bind argument to parameter 'ReferenceObject' because it is null. (Cannot bind argument to parameter 'ReferenceObject' because it is null.)

**Comment by viswanadham-k** [comment]
Hi @YariCa 
Thanks for your feedback.
I hope latest version WVD scaling tool sort out your issue. So can you please follow the below steps and update the latest version.

Below are the steps to update the Azure automation-based scaling tool located here to latest version

Access below link and copy the content of basicScale.ps1 code into a clipboard
https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/wvd-scaling-script/basicScale.ps1

Login to the Azure portal
In the Azure portal, select All services. In the list of resources, enter and select Automation Accounts.
On the Automation Accounts page, select the name of Automation account where you have the scaling tool hosted
Click on Runbooks under Process Automation section on the left hand side pane.
Click on PowerShell Runbook named “WVDAutoScaleRunbook”
Click on Edit from the top pane
Replace the existing code with one from Step 1
Click “Save” and “Publish”
New code will come into effect from next run of the runbook based on recurrence interval you have scheduled.

Please let me know if you are still facing issues. If it is working fine then close this issue.

Thanks

**Comment by YariCa** [comment]
Hi, we are still facing issues.
the problem seems with logging off user sessions
Starting WVD tenant hosts scale optimization: Current Date Time is: 05/07/2020 18:05:02

It is Off-peak hours

Starting to scale down WVD session hosts ...

Processing hostpool POOL1

Checking session host: HOST1
  of sessions: 3 and status: Available

Counting the current sessions on the host HOST1 :3

Script was sent a log off message to user: USER1


then the script fail after 5 minutes.
the next run, same output as above.
seems that there's no message back for user logoff.

in addition, often, for all session hosts completely down, we still see sessions as disconnected. maybe a communication problem between the session hosts and the rdbroker???

**Comment by YariCa** [comment]
adding more info.
imagine 2 session still active
The script start logging off users sending the messsage. 1 user is notified
the timeout is 300 seconds.
script fail
the next run the active sessions is 1. the script notify the other user.
other 300 seconds of timeout.
script fail.
next run 0 sessions.
shutdown the vm.
script complete.

I think the logoff message and the timeout should start the same time for all users and then force logoff. so next run we'll 0 sessions.
I'm right?

**Comment by RoopChevuri** [comment]
Could you please validate if this issue reproduces with latest version of script located here :  https://github.com/nakranimohit0/azure-docs/blob/yammer_private_preview_wvd_scaling/articles/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script.md  . We will release this version broadly in few weeks time.

**Comment by nakranimohit0** [comment]
Closing this out. Please re open if you are still running into the same issue even with the newer version
