### ISSUE TITLE
Speed up script execution

### ISSUE THREAD

**Issue by Pawel1985** [Azure/RDS-Templates#470]
https://github.com/Azure/RDS-Templates/blob/cda0cf55dcf900a371b62910e9f8d06aa61eb41d/wvd-templates/wvd-scaling-script/basicScale.ps1#L343

instead of executing get-azvm foreach vm, before foreach {} I run 
$RoleInstances = Get-AzVM -Status

and in the loop:
$RoleInstance = $RoleInstances | Where-Object { $_.Name.Contains($VMName) }

I applied this small change in my local copy, but only in sections where capacity is calculated, all sections of code where scaling is executed, so vm must be stopped or started get-azvm is not touched, this speeds up capacity calculation 

$HostPoolUserSessions = Get-RdsUserSession -TenantName $TenantName -HostPoolName $HostpoolName

//edit: here I'd do this:
### $RoleInstances = Get-AzVM -Status

		foreach ($SessionHost in $ListOfSessionHosts) {
			$SessionHostName = $SessionHost.SessionHostName | Out-String
			$VMName = $SessionHostName.Split(".")[0]

			# Check if VM is in maintenance
//edit 
### $RoleInstance = $RoleInstances | Where-Object { $_.Name.Contains($VMName) }

			#$RoleInstance = Get-AzVM -Status -Name $VMName

			if ($RoleInstance.Tags.Keys -contains $MaintenanceTagName) {
				Write-Output "Session host is in maintenance: $VMName, so script will skip this VM"
				$LogMessage = @{ hostpoolName_s = $HostpoolName; logmessage_s = "Session host is in maintenance: $VMName, so script will skip this VM" }
				Add-LogEntry -LogMessageObj $LogMessage -LogAnalyticsWorkspaceId $LogAnalyticsWorkspaceId -LogAnalyticsPrimaryKey $LogAnalyticsPrimaryKey -logType "WVDTenantScale_CL" -TimeDifferenceInHours $TimeDifference
				$SkipSessionhosts += $SessionHost
				continue
			}
			$AllSessionHosts = Compare-Object $ListOfSessionHosts $SkipSessionhosts | Where-Object { $_.SideIndicator -eq '<=' } | ForEach-Object { $_.InputObject }

**Comment by richyla** [comment]
This is a huge improvement in the execution time of the script.  With 50 session hosts the script was taking up to an hour to complete when it was attempting to scale, this minor adjustment has brought the overall time down to a few minutes.  Thanks for the share!

**Comment by RoopChevuri** [comment]
We have made improvements in this regard in later version of our tool :  https://github.com/nakranimohit0/azure-docs/blob/yammer_private_preview_wvd_scaling/articles/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script.md  . Could you please validate and provide feedback before we release it more broadly.

**Comment by nakranimohit0** [comment]
Closing this out. Please re open if you are still running into the same issue even with the newer version
