### ISSUE TITLE
capacity reserve

### ISSUE THREAD

**Issue by Pawel1985** [Azure/RDS-Templates#471]
https://github.com/Azure/RDS-Templates/blob/cda0cf55dcf900a371b62910e9f8d06aa61eb41d/wvd-templates/wvd-scaling-script/basicScale.ps1#L440

$HostPoolUserSessions.Count -ge $AvailableSessionCapacity-30

there should be some kind of 'buffor' that allows to keep few more hosts up and running in case of sudden spike, especially in the mornings when number of sessions is growing very fast, scaling script may not be that fast and users stuck with no resources available

**Comment by RoopChevuri** [comment]
Thanks for the feedback. We will consider this for future release of this functionality.
