### ISSUE TITLE
Scaling tool off peak hours bug: it does not start session hosts up to minimum requirement

### ISSUE THREAD

**Issue by nakranimohit0** [Azure/RDS-Templates#474]
MinimumNumberOfRDSH = 2
During off peak hours
Before the script runs: 1 session host is running
After the script runs: 1 session host is running

Output:
DeploymentUrl                      TenantGroupName      UserName
-------------                      ---------------      --------
https://rdbroker.wvd.microsoft.com Default Tenant Group usr@rdpgwcon.net
Starting WVD tenant hosts scale optimization: Current Date Time is: 05/08/2020 09:52:41
It is Off-peak hours
Starting to scale down WVD session hosts ...
Processing hostpool mo-hp-0
Checking session host: mo-vm-0-0.rdpgwcon.net
  of sessions: 0 and status: Available
HostpoolName: mo-hp-0, TotalRunningCores: 2 NumberOfRunningHosts: 1
End WVD tenant scale optimization.

psh > Get-RdsSessionHost $tenant $host_pool

SessionHostName    : mo-vm-0-0.rdpgwcon.net
TenantName         : tn
TenantGroupName    : Default Tenant Group
HostPoolName       : mo-hp-0
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 2020-05-08 4:44:36 PM
AgentVersion       : 1.0.1932.4800
AssignedUser       :
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Available
UpdateState        : Succeeded
LastUpdateTime     : 2020-05-07 6:15:08 PM
UpdateErrorMessage :

SessionHostName    : mo-vm-0-1.rdpgwcon.net
TenantName         : tn
TenantGroupName    : Default Tenant Group
HostPoolName       : mo-hp-0
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 2020-05-08 4:40:57 PM
AgentVersion       : 1.0.1932.4800
AssignedUser       :
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Unavailable
UpdateState        : Succeeded
LastUpdateTime     : 2020-05-07 6:18:44 PM
UpdateErrorMessage :

SessionHostName    : mo-vm-0-2.rdpgwcon.net
TenantName         : tn
TenantGroupName    : Default Tenant Group
HostPoolName       : mo-hp-0
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 2020-05-08 4:40:43 PM
AgentVersion       : 1.0.1932.4800
AssignedUser       :
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Unavailable
UpdateState        : Succeeded
LastUpdateTime     : 2020-05-07 6:18:57 PM
UpdateErrorMessage :

SessionHostName    : mo-vm-0-3.rdpgwcon.net
TenantName         : tn
TenantGroupName    : Default Tenant Group
HostPoolName       : mo-hp-0
AllowNewSession    : True
Sessions           : 0
LastHeartBeat      : 2020-05-08 4:41:06 PM
AgentVersion       : 1.0.1932.4800
AssignedUser       :
OsVersion          : 10.0.18363
SxSStackVersion    : rdp-sxs200326004
Status             : Unavailable
UpdateState        : Succeeded
LastUpdateTime     : 2020-05-07 6:19:12 PM
UpdateErrorMessage :

**Comment by viswanadham-k** [comment]
Hi @nakranimohit0 
Please cross check your logic app inputs. Script will left the MinimumnumberOfRDSH value base VM's when stopping time  in off peak hours.

Thanks,
