### ISSUE TITLE
Failed to authenticate WVD: Parameter name: errorRecordcannot cannot be null

### ISSUE THREAD

**Issue by giova82** [Azure/RDS-Templates#483]
After create resources, in the section View logs and scaling tool output, appear this message:

**Failed to authenticate WVD: Value cannot be null.
Parameter name: errorRecord**

**Comment by viswanadham-k** [comment]
Hi @giova82 
I hope you have missed one of the step. Please find below link and follow the step. 
https://docs.microsoft.com/en-us/azure/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script#create-a-role-assignment-in-windows-virtual-desktop

And also can you please check and validate the configuration steps which you have followed to setup wvd scaling tool from below link.
https://docs.microsoft.com/en-us/azure/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script

Thanks

**Comment by nakranimohit0** [comment]
@giova82 
Can you please try the newer version of tool and see if it resolves the issue: https://github.com/nakranimohit0/azure-docs/blob/yammer_private_preview_wvd_scaling/articles/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script.md . This will be published broadly in few weeks. Please re open if you are still running into the same issue even with the newer version
