### ISSUE TITLE
 Scale-out has issue: does not scale with number of connections

### ISSUE THREAD

**Issue by PasupathiMadhavan** [Azure/RDS-Templates#484]
Scale-in looks to be working fine. Only Scale-out has issue. It looks like the POOL is providing max 2 VMs, not anymore, irrespective of the number of connections

**Comment by viswanadham-k** [comment]
Hi @PasupathiMadhavan 
To investigate further I need more information, so can we sync and resolve this issue ASAP.
Please let me know your availability time today then i will connect and assist you with resolved steps. And share with me your mailing address then i will send a meeting invitation.

Thanks

**Comment by RoopChevuri** [comment]
Hi @PasupathiMadhavan - Wondering if you could share more details about the issue like Host Pool size, any errors you receive etc so we can help troubleshoot the issue.

**Comment by nakranimohit0** [comment]
@PasupathiMadhavan 
Can you please try the newer version of tool and see if it resolves the issue: https://github.com/nakranimohit0/azure-docs/blob/yammer_private_preview_wvd_scaling/articles/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script.md . This will be published broadly in few weeks. Please re open if you are still running into the same issue even with the newer version
