### ISSUE TITLE
Clarification on Script parameter

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/RDS-Templates#493]
`tenantAdminPassword` in combination with the `tenantAdminUpnOrApplicationId` parameter for https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool/mainTemplate.json

When `isServicePrincipal` is set to `true` is the password the application's secret key?

The description for the password parameter is unclear on this.

**Comment by YariCa** [comment]
Yes.

**Comment by nakranimohit0** [comment]
@davidobrien1985 Yes, that is correct.
@lintFan I think we should clarify this somewhere. 1) description of the param in the main template 2) read me file

**Comment by lintFan** [comment]
Thank you, we are tracking this internally now.
