### ISSUE TITLE
Scaling tool - wrong available hosts detection

### ISSUE THREAD

**Issue by YariCa** [Azure/RDS-Templates#494]
The scaling tool, detect the wrong number of session hosts and start a new VM.
below the log.

*******************
DeploymentUrl                      TenantGroupName      UserName   
-------------                      ---------------      --------   
https://rdbroker.wvd.microsoft.com Default Tenant Group Certificate

Starting WVD tenant hosts scale optimization: Current Date Time is: 05/26/2020 09:12:25

It is in peak hours now

Starting session hosts as needed based on current workloads.

Checking session host: SWAPP-A-0
  of sessions: 13 and status: Available

Checking session host: SWAPP-A-1
  of sessions: 0 and status: Unavailable

Checking session host: SWAPP-A-2
  of sessions: 0 and status: Unavailable

Checking session host: SWAPP-A-3
  of sessions: 0 and status: Upgrading

Current number of running hosts:0

Current number of running session hosts is less than minimum requirements, start session host ...

Starting Azure VM: SWAPP-A-1 and waiting for it to complete ...

Azure VM has been started: SWAPP-A-1 ...

'SWAPP-A-1' session host status is 'Available'

HostpoolName: GIANO, TotalRunningCores: 4 NumberOfRunningHosts: 1

End WVD tenant scale optimization.

**Comment by viswanadham-k** [comment]
Hi  @YariCa,
I am part of WVD scaling tool development and working with Microsoft.
Please let me know your availability time today then i will connect and assist you with resolved steps. And share with me your mailing address then i will send a meeting invitation.

Thanks,

**Comment by YariCa** [comment]
Hi,
I’m a Microsoft guy too 😊

My email address is yarica@microsoft.com<mailto:yarica@microsoft.com>

Thanks,
Yari

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: viswanadham-k<mailto:notifications@github.com>
Inviato: Thursday, June 11, 2020 5:43 PM
A: Azure/RDS-Templates<mailto:RDS-Templates@noreply.github.com>
Cc: YariCa<mailto:y.campagna@hotmail.it>; Mention<mailto:mention@noreply.github.com>
Oggetto: Re: [Azure/RDS-Templates] Scaling tool - wrong available hosts detection (#494)


Hi @YariCa<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FYariCa&data=02%7C01%7C%7Cb88ac8e194254e68656308d80e1e31a3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637274870121998268&sdata=Fu9XSRQoOALqBEZv1T3dR5swT7OI8AYFwlGOZQYCUjM%3D&reserved=0>,
I am part of WVD scaling tool development and working with Microsoft.
Please let me know your availability time today then i will connect and assist you with resolved steps. And share with me your mailing address then i will send a meeting invitation.

Thanks,

**Comment by Raviteja-H** [comment]
Hi All,

Can we have a document for WVD scaling in 2020 spring version

I created hos pools but need to use the scaling for multi-session hosts

I need WVD auto-scaling setup and configuration using Azure portal, please share with me anyone has documents

**Comment by nakranimohit0** [comment]
@YariCa 
Can you please try the newer version of tool and see if it resolves the issue: https://github.com/nakranimohit0/azure-docs/blob/yammer_private_preview_wvd_scaling/articles/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script.md . This will be published broadly in few weeks. Please re open if you are still running into the same issue even with the newer version

@Raviteja-H 
Please see this: #500
