### ISSUE TITLE
ApplicationId parameter in the New-RDSRoleAssignment??

### ISSUE THREAD

**Issue by ShehzadUIT** [Azure/RDS-Templates#498]
Hi,
I am following the docs article: https://docs.microsoft.com/en-us/azure/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script#create-an-azure-automation-account

until i got to: New-RdsRoleAssignment -RoleDefinitionName "RDS Contributor" -ApplicationId <applicationid> -TenantName <tenantname>

i am not sure what this applicationID is? is it for the Azure automation account created at: New-RdsRoleAssignment -RoleDefinitionName "RDS Contributor" -ApplicationId <applicationid> -TenantName <tenantname>

and if that is the case,  how to retrieve this value?

**Comment by nakranimohit0** [comment]
The applicationID is the application ID of the service principal that was created when creating an Azure Automation Run As Account. It is what you got from step 6 of https://docs.microsoft.com/en-us/azure/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script#create-an-azure-automation-run-as-account

You specify that applicationID here (below) to give your newly created service principal access to your WVD Tenant:
`New-RdsRoleAssignment -RoleDefinitionName "RDS Contributor" -ApplicationId <applicationid> -TenantName <tenantname>`

**Comment by ShehzadUIT** [comment]
we had the Run As Account created before and i am re-using it. when i run the following:
`Get-RdsRoleAssignment -SignInName "<Run-As-Account"` i returns nothing.
