### ISSUE TITLE
Need clarification on the automation account used in PS script to create the Azure Logic app and execution schedule

### ISSUE THREAD

**Issue by ShehzadUIT** [Azure/RDS-Templates#499]
i am abit confused. there are no comments available on which automation account should we use as per the section within the script that creates the Azure Logic App:

`$automationAccount = Get-AzAutomationAccount -ResourceGroupName $resourceGroup.ResourceGroupName | Out-GridView -PassThru
$automationAccountName = $automationAccount.AutomationAccountName
$automationAccountConnection = Get-AzAutomationConnection -ResourceGroupName $resourceGroup.ResourceGroupName -AutomationAccountName $automationAccount.AutomationAccountName | Out-GridView -PassThru -Title "Select the Azure RunAs connection asset"
$connectionAssetName = $automationAccountConnection.Name`

is it the Automation account created right at the start or the Automation Run As account?

can someone please clarify this?

**Comment by AAdamCCox** [comment]
Hi @ShehzadUIT 
The section of script you've quoted which is used during the Logic App creation is asking you to select the Automation Account created earlier by running this command:
` .\createazureautomationaccount.ps1 -SubscriptionID <azuresubscriptionid> -ResourceGroupName <resourcegroupname> -AutomationAccountName `**`<name of automation account>`**

Whatever name you entered there should be available to select from the gridview which is displayed by the first line of the command you quoted.

Hope that clarifies?

**Comment by viswanadham-k** [comment]
Hi @ShehzadUIT 
I hope @AAdamCCox  has clarifies your confusion. Please let me know if you are still confuse. If not close this issue.

@AAdamCCox thank you for giving guide.

Thanks,

**Comment by ShehzadUIT** [comment]
i figured it out in a different way. but yes that is one way to resolve the issue. Thanks
