### ISSUE TITLE
rds-deployment-ha-broker template SQLServer Parameter is required

### ISSUE THREAD

**Issue by Alan-AcutePath** [Azure/RDS-Templates#5]
SQLServer parameter is required, otherwise the deployment will fail with error of missing argument of sqlserver.

The description implies it is only required for dedicated database, so for Azure SQL, it should not be required. 

By providing sqlserver name, the deployment will complete but the script has errors loged for configuring the computer group for sql.

Should we check the sqlserver parameter is provided or not before running the SetupGroups in the SetupCB function?

**Comment by mmarch** [comment]
fixed in 44c0e29, closing.
