### ISSUE TITLE
Off-peak scale-down can shut down hosts with active user sessions which were initiated after script execution began

### ISSUE THREAD

**Issue by AAdamCCox** [Azure/RDS-Templates#501]
In this instance we're using a hostpool with 15 hosts, where "LimitSecondsToForceLogOffUser" is set at 0. When off-peak hours are reached, this can lead to the script attempting to shut down up to 12 hosts in a single execution. Due to the amount of time taken to wait for each host to stop, new users sessions are able to connect after script execution has begun and active sessions on each host have been counted, and therefore the VM to which they're connected will be shut down.

Here's an example of this in action, where auto-scale script execution began and a user connected three minutes later, and 18 minutes after this the VM was deallocated.

Output of scaling script (Created 6/2/2020, 5:02:26 PM , Last Update 6/2/2020, 5:51:26 PM):

>`Authenticating as service principal for Azure. Result:` 
>`Account                              SubscriptionName TenantId                             Environment`
>`-------                              ---------------- --------                             -----------`
>`c6c3d009-...                         Production       67bda7ee-fd80-41...                  AzureCloud `
>
>`Sets the Azure subscription. Result: `
>
>`Name                                     Account             SubscriptionName    Environment         TenantId           `
>`----                                     -------             ----------------    -----------         --------           `
>`Production (1a3c8479-0046-4a6f-a2ad-3... c6c3d009-78e6-4c... Production          AzureCloud  67bda7ee-fd80-41...`
>``
>Authenticating as service principal for WVD. Result: 
>``
>`DeploymentUrl                      TenantGroupName      UserName   `
>`-------------                      ---------------      --------   `
>`https://rdbroker.wvd.microsoft.com Default Tenant Group Certificate`
>
>`Starting WVD tenant hosts scale optimization: Current Date Time is: 06/02/2020 17:07:15`
>
>`It is Off-peak hours`
>
>`Starting to scale down WVD session hosts ...`
>
>`Processing hostpool Engineering-GPU-NV-1`
>
>`Checking session host: wvd-EngGPU-0.###.uk`
>`  of sessions: 0 and status: Available`
>
>`Checking session host: wvd-EngGPU-11.###.uk`
>`  of sessions: 0 and status: Available`
>
>`Checking session host: wvd-EngGPU-12.###.uk`
>`  of sessions: 0 and status: Available`
>
>`Checking session host: wvd-EngGPU-13.###.uk`
>`  of sessions: 0 and status: Available`
>
>`Checking session host: wvd-EngGPU-14.###.uk`
>`  of sessions: 0 and status: Available`
>
>`Checking session host: wvd-EngGPU-2.###.uk`
>`  of sessions: 0 and status: Available`
>
>`Checking session host: wvd-EngGPU-3.###.uk`
>`  of sessions: 0 and status: Available`
>
>`Checking session host: wvd-EngGPU-4.###.uk`
>`  of sessions: 0 and status: Available`
>
>**`Checking session host: wvd-EngGPU-5.###.uk`
>`  of sessions: 0 and status: Available`**
>
>`Checking session host: wvd-EngGPU-6.###.uk`
>`  of sessions: 0 and status: Available`
>
>`Checking session host: wvd-EngGPU-7.###.uk`
>`  of sessions: 0 and status: Available`
>
>`Checking session host: wvd-EngGPU-9.###.uk`
>`  of sessions: 0 and status: Available`
>
>`Checking session host: wvd-EngGPU-1.###.uk`
>`  of sessions: 1 and status: Available`
>
>`Checking session host: wvd-EngGPU-10.###.uk`
>`  of sessions: 1 and status: Available`
>
>`Checking session host: wvd-EngGPU-8.###.uk`
>`  of sessions: 1 and status: Available`
>
>`Stopping Azure VM: wvd-EngGPU-0 and waiting for it to complete ...`
>
>`Azure VM has been stopped: wvd-EngGPU-0 ...`
>
>`Stopping Azure VM: wvd-EngGPU-11 and waiting for it to complete ...`
>
>`Azure VM has been stopped: wvd-EngGPU-11 ...`
>
>`Stopping Azure VM: wvd-EngGPU-12 and waiting for it to complete ...`
>
>`Azure VM has been stopped: wvd-EngGPU-12 ...`
>
>`Stopping Azure VM: wvd-EngGPU-13 and waiting for it to complete ...`
>
>`Azure VM has been stopped: wvd-EngGPU-13 ...`
>
>`Stopping Azure VM: wvd-EngGPU-14 and waiting for it to complete ...`
>
>`Azure VM has been stopped: wvd-EngGPU-14 ...`
>
>`Stopping Azure VM: wvd-EngGPU-2 and waiting for it to complete ...`
>
>`Azure VM has been stopped: wvd-EngGPU-2 ...`
>
>`Stopping Azure VM: wvd-EngGPU-3 and waiting for it to complete ...`
>
>`Azure VM has been stopped: wvd-EngGPU-3 ...`
>
>`Stopping Azure VM: wvd-EngGPU-4 and waiting for it to complete ...`
>
>`Azure VM has been stopped: wvd-EngGPU-4 ...`
>
>`Stopping Azure VM: wvd-EngGPU-5 and waiting for it to complete ...`
>
>**`Azure VM has been stopped: wvd-EngGPU-5 ...`**
>
>`Stopping Azure VM: wvd-EngGPU-6 and waiting for it to complete ...`
>
>`Azure VM has been stopped: wvd-EngGPU-6 ...`
>
>`Stopping Azure VM: wvd-EngGPU-7 and waiting for it to complete ...`
>
>`Azure VM has been stopped: wvd-EngGPU-7 ...`
>
>`Stopping Azure VM: wvd-EngGPU-9 and waiting for it to complete ...`
>
>`Azure VM has been stopped: wvd-EngGPU-9 ...`
>
>`HostpoolName: Engineering-GPU-NV-1, TotalRunningCores: 36 NumberOfRunningHosts: 3`
>
>`End WVD tenant scale optimization.`

Output of Get-RdsUserSession for this hostpool (timestamp in UTC, local time was 17:10) :
![image](https://user-images.githubusercontent.com/63780844/83753895-01c6cb80-a663-11ea-83bb-abfad72b701f.png)

VM deallocation time:
![image](https://user-images.githubusercontent.com/63780844/83754098-4fdbcf00-a663-11ea-94ef-9d9fac528c45.png)

**Comment by viswanadham-k** [comment]
Hi @AAdamCCox 
I am part of WVD scaling tool development and working with Microsoft.
Please let me know your availability time today then i will connect and assist you with resolved steps. And share with me your mailing address then i will send a meeting invitation.

Thanks,

**Comment by AAdamCCox** [comment]
Hi @viswanadham-k I've emailed you directly to arrange a time to work on this, hopefully you've received that? Thanks

**Comment by nakranimohit0** [comment]
@AAdamCCox 
Can you please try the newer version of tool and see if it resolves the issue: https://github.com/nakranimohit0/azure-docs/blob/yammer_private_preview_wvd_scaling/articles/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script.md . This will be published broadly in few weeks. Please re open if you are still running into the same issue even with the newer version
