### ISSUE TITLE
Existing WVD hosts not updated/replaced

### ISSUE THREAD

**Issue by PylsaPylsa** [Azure/RDS-Templates#505]
When attempting to redeploy the hostpool with an updated VHD image, the deployment runs "successfully" but no actual updates are made to the existing hosts. They just continue running and no apparent changes are applied. I think this has worked in the past, where old hosts were deleted and then recreated. 

If I use a different prefix (i.e. the machines it is trying to create do not exist yet) everything does seem to work properly. Is this intended behaviour? Maybe I'm doing something wrong this time but I don't see it.

The security principal I use has Owner the owner role on the resource group I am deploying to and Contribute role on the subscription itself.

2-Update-existing-WVD-host-pool

**Comment by sebastiantrumstedt** [comment]
Yes that's how it works, you need to use new names for the VMs.

**Comment by PylsaPylsa** [comment]
That's insane... Also, that's not how it seems to be advertised to work.
