### ISSUE TITLE
Bug : User logoff during Scale Down

### ISSUE THREAD

**Issue by nigelwebster** [Azure/RDS-Templates#509]
We have a scenario where we we scale back after 7:00PM we find that if a user is logged out and the server is then stopped. the WVD connection broker still believes that the user is logged in and therefore in the morning the user cannot log in to the system because he has an active session on a server which is now off.

I did raise this with Microsoft and got referred back here.

I got around this by setting up an automated task to power on ALL servers managed by WVD scale around 1 hour after they had shutdown. this then registered that there were no user sessions on that server and then allowed sessions to connect again.

However this caused a period during this process when you were not allowed to login and people start complaining of not being able to access.

Is this something that we can add a pause between logging of a user and then shutting down the machine?

Could be a simply Pause -s 300

However you may be aware of this and have a different solution

**Comment by viswanadham-k** [comment]
HI @nigelwebster 
I need more information. Please let me know your availability time today then will sync up and resolve this issue.  Let me know your mailing address then i will send the meeting invitation.

Thanks

**Comment by nigelwebster** [comment]
Hi mate

This is 6:00pm on a Friday night for us so we’re hitting the weekend now.

Any chance of picking this up on Monday 9:00-3:00 GMT?

Sent from my iPhone

Portsmouth Technopole
Kingston Crescent
Portsmouth
PO2 8FA
United Kingdom
Nigel Webster
Chief Technology Officer
Mainline: 0800 101 7150
DDI: 02393 162 502
Follow Us
www.supportonthespot.co.uk
For a faster response to your IT Support requests, please email us directly at help@supportonthespot.co.uk this communication may contain information that is confidential and/or privileged, it is for the exclusive use of the addressee. If you have received this communication in error, please delete and contact the sender immediately, please check any attachments for viruses: while precautions have been made to prevent transmission of viruses, we are not responsible for any damage caused. This communication is provided for information purposes only and does not form any part of a contract or agreement. Support on the Spot act as consultants and the views expressed in this communication are not necessarily those held by Support on the Spot or the clients they represent. "Support on the Spot Limited” is a UK registered company, registered in the United Kingdom: 07025260

On 19 Jun 2020, at 17:41, viswanadham-k <notifications@github.com> wrote:

﻿

HI @nigelwebster<https://github.com/nigelwebster>
I need more information. Please let me know your availability time today then will sync up and resolve this issue. Let me know your mailing address then i will send the meeting invitation.

Thanks

**Comment by viswanadham-k** [comment]
Sure @nigelwebster i will schedule a meeting today at 11:30 AM GMT.
Can you please share with me your mailing address then i will schedule a meeting invitation.

Thanks,

**Comment by nigelwebster** [comment]
Nwebster@supportonthespot.co.uk

Sent from my iPhone

Portsmouth Technopole
Kingston Crescent
Portsmouth
PO2 8FA
United Kingdom
Nigel Webster
Chief Technology Officer
Mainline: 0800 101 7150
DDI: 02393 162 502
Follow Us
www.supportonthespot.co.uk
For a faster response to your IT Support requests, please email us directly at help@supportonthespot.co.uk this communication may contain information that is confidential and/or privileged, it is for the exclusive use of the addressee. If you have received this communication in error, please delete and contact the sender immediately, please check any attachments for viruses: while precautions have been made to prevent transmission of viruses, we are not responsible for any damage caused. This communication is provided for information purposes only and does not form any part of a contract or agreement. Support on the Spot act as consultants and the views expressed in this communication are not necessarily those held by Support on the Spot or the clients they represent. "Support on the Spot Limited” is a UK registered company, registered in the United Kingdom: 07025260

On 22 Jun 2020, at 02:48, viswanadham-k <notifications@github.com> wrote:

﻿

Sure @nigelwebster<https://github.com/nigelwebster> i will schedule a meeting today at 11:30 AM GMT.
Can you please share with me your mailing address then i will schedule a meeting invitation.

Thanks,

**Comment by viswanadham-k** [comment]
Hi @nigelwebster 
I have sent a meeting invitation. But you didn't join the call. Please propose a new time if required. We are most happy to help you.

Thanks,

**Comment by nigelwebster** [comment]
Appologies I thought you said 11:30 my time

I was at lunch when you sent through the invite as it was 2:30PM


Portsmouth Technopole
Kingston Crescent
Portsmouth
PO2 8FA
United Kingdom
Nigel Webster
Chief Technology Officer
Mainline: 0800 101 7150
DDI: 02393 162 502
Follow Us
www.supportonthespot.co.uk
For a faster response to your IT Support requests, please email us directly at help@supportonthespot.co.uk this communication may contain information that is confidential and/or privileged, it is for the exclusive use of the addressee. If you have received this communication in error, please delete and contact the sender immediately, please check any attachments for viruses: while precautions have been made to prevent transmission of viruses, we are not responsible for any damage caused. This communication is provided for information purposes only and does not form any part of a contract or agreement. Support on the Spot act as consultants and the views expressed in this communication are not necessarily those held by Support on the Spot or the clients they represent. "Support on the Spot Limited” is a UK registered company, registered in the United Kingdom: 07025260

**Comment by viswanadham-k** [comment]
Hi @nigelwebster 
Apologize it's my mistake i didn't schedule a meeting at 11:30 AM GMT. 
So shall we connect tomorrow same time at 11:30 AM GMT. Please propose new time if you required.

Thanks,

**Comment by nigelwebster** [comment]
I think because I have now turned off the force users logoff from 300 to 0 and allow windows group policy to handle the log off we do not have any issues with this any more.

However if there is a possibility of having a setting for minimum servers during peak times in addition to off peak then it will handle the logon spike in the mornings much better.

Also if there was a way to put a decimal when choosing how many people on a server per cpu or some calculation then this would enable us to find a happy medium


Portsmouth Technopole
Kingston Crescent
Portsmouth
PO2 8FA
United Kingdom
Nigel Webster
Chief Technology Officer
Mainline: 0800 101 7150
DDI: 02393 162 502
Follow Us
www.supportonthespot.co.uk
For a faster response to your IT Support requests, please email us directly at help@supportonthespot.co.uk this communication may contain information that is confidential and/or privileged, it is for the exclusive use of the addressee. If you have received this communication in error, please delete and contact the sender immediately, please check any attachments for viruses: while precautions have been made to prevent transmission of viruses, we are not responsible for any damage caused. This communication is provided for information purposes only and does not form any part of a contract or agreement. Support on the Spot act as consultants and the views expressed in this communication are not necessarily those held by Support on the Spot or the clients they represent. "Support on the Spot Limited” is a UK registered company, registered in the United Kingdom: 07025260

**Comment by viswanadham-k** [comment]
Hi @nigelwebster 
I hope your issues are fixed and scaling tool is working fine in your environment. Can you please close your issues which you have raised.

Thanks,

**Comment by RoopChevuri** [comment]
Thanks for the feedback. We will triage feedback for feature improvements for future release of the tool.
