### ISSUE TITLE
URGENT - Scaling tool fail to logoff user and set drain mode

### ISSUE THREAD

**Issue by YariCa** [Azure/RDS-Templates#510]
Hi,
we have 3 SH and 2 of them are active (tipically)
during the off-peak hours scaling down, we have 1 session per host.
The tool tries to scale down the second session host but after sending the logoff message to the connected user, the script immediately fail.
The next run the first session host is with 0 sessions and is turned off.
The next morning the session host 1 is UP but in drain mode and no one can access resources.

this is exception in failed run
{"Error":"InvalidDataFormat","Message":null} (The remote server returned an error: (400) Bad Request.)

**Comment by viswanadham-k** [comment]
Hi @YariCa 
I need more information. Please let me know your availability time today then will sync up and resolve this issue. Let me know your mailing address then i will send the meeting invitation.

Thanks,

**Comment by YariCa** [comment]
Hi, 

y.campagna@hotmail.it
thanks,

**Comment by nakranimohit0** [comment]
@YariCa 
Can you please try the newer version of tool to see if you are still having the issue: https://github.com/nakranimohit0/azure-docs/blob/yammer_private_preview_wvd_scaling/articles/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script.md . This will be published broadly in few weeks.

**Comment by nakranimohit0** [comment]
Please re open if you are still running into the same issue even with the newer version
