### ISSUE TITLE
1-Create-and-provision-host-pool - Spring Update WVD

### ISSUE THREAD

**Issue by LPM1985** [Azure/RDS-Templates#518]
1-Create-and-provision-host-pool

Unable to get this template to function with the new WVD Workspaces. Errors outputs seem to reference the old PoSH commands for WVD and reference to TenantID etc.

Is there a workable option that can support the Spring Update?

**Comment by lintFan** [comment]
@LPM1985 The templates [Create and provision host pool](https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool) and  [Update an existing Windows Virtual Desktop hostpool](https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Update%20existing%20WVD%20host%20pool)
both only support the Fall 2019 release and not the Spring Update 2020.  I will update the read me files to make that clearer.

I am reaching out internally to get you an answer on templates for the Spring Update 2020.

As a workaround you could download the ARM template that is created when you deploy a hostpool using Spring Update 2020 in the Azure portal, documentation for deploying using the portal [is here](https://docs.microsoft.com/en-us/azure/virtual-desktop/create-host-pools-azure-marketplace#begin-the-host-pool-setup-process), after you click the Create button and there should be an option to download the template.

**Comment by lintFan** [comment]
@LPM1985  Unfortunately I don't have any news for you on ARM templates to create session hosts for WVD Spring update 2020 but any updates on this will be posted to the [WVD Tech Community ](https://techcommunity.microsoft.com/t5/windows-virtual-desktop/bd-p/WindowsVirtualDesktop)

Closing this since the readme files will be updated with the next release to the master branch.

**Comment by lintFan** [comment]
@LPM1985 @ITGuy99 Good news, ARM templates for Windows Virtual Desktop with Azure Resource Manager objects (formerly known as WVD Spring Update 2020) are now available [here](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/CreateAndProvisionHostPool) and [here](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/AddVirtualMachinesToHostPool).
