### ISSUE TITLE
Azure Autoscale Fall 2019 does not start hosts that are stopped.

### ISSUE THREAD

**Issue by WVDHERE** [Azure/RDS-Templates#519]
The WVD hosts do not start when the maximum threshold of users logs in - what am I missing?

**Comment by nakranimohit0** [comment]
Please follow the instructions provided in the documentation when reporting issues:
For 2020 Spring update / ARM based WVD: https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script#report-issues
For 2019 Fall release / classic / non-ARM based WVD: https://docs.microsoft.com/en-us/azure/virtual-desktop/virtual-desktop-fall-2019/set-up-scaling-script#report-issues
