### ISSUE TITLE
Feature Request - Start N hosts at X time

### ISSUE THREAD

**Issue by hesguinho** [Azure/RDS-Templates#520]
With COVID-19 situation more companies are going full WVD
Problem is that at the start of peak time we have a massive amount on users logging simultaneously.
Even running the script every 5 minutes sometimes it happens that the users have no available host sessions.
It would be good to have a function in the script to for example start a % or a number of hosts at a specific time before the ON peak starts.

Cheers

**Comment by pcamposs** [comment]
@hesguinho take a look  .. I am starting to Write this script , it is complementary to the Scaling Script ...
https://github.com/pcamposs/ScriptsWVD

**Comment by gshystad** [comment]
This is our #1 issue with this script. We have 1,000+ users logging on within an hour of peak time and the script can't keep up with the demand. We end up with double the number of users that we'd like on the initial hosts. A "morning start" value with the number of VMs to start would make this script nearly perfect.

**Comment by mgustin2020** [comment]
We face a similar situation as gshystad points out.  I can not think of a more important feature request right now.

**Comment by Maniac0Maniac** [comment]
Huge issue for us! 2500 users creates a bit of a login storm in the morning. We scale at about one sessionhost per minute in the mornings. Really need the script to be able to spin up about 5 per 5 min cycle.

**Comment by jbargallo** [comment]
Also, apart from the login storm issue, if you have the parameter MinimumNumberOfRDSH set to 0 for off-peak hours (i.e. by night you don-t need any of them), when the peak hour comes the script does nothing at all, it checks that 0 sessions are well below the 90% threshold and no VM is ever started!! So you always need to start at least 1 manually (or with a complementary script as stated before).

**Comment by chibs89** [comment]
Are there any news to this issue? I think all companys have the same issue.
The issue jbargallo mentioned is also major for us, so we have to implement to automation scripts at the customers who do not want one sessionhost available 24/7.

**Comment by dgiesselbach** [comment]
We need this feature too! Please push up!

**Comment by SvenAelterman** [comment]
This customization, which is used regularly in education, provides this feature.
https://github.com/Microsoft-USEduAzure/Windows-Virtual-Desktop/tree/master/daily-scaling

**Comment by chibs89** [comment]
Thank you for the info @SvenAelterman I will look into this.
As this is the linked project on the official microsoft documentation, will it be updated on the same featureset as the education solution?

**Comment by michael-rknudsen-dk** [comment]
We also need this badly. @SvenAelterman thanks for the info, i will try this out immediately, but would be better to have it in the MS original MS solution.

**Comment by chibs89** [comment]
I can confirm that the posted solution works better, thank you @SvenAelterman.

**Comment by DougDaz** [comment]
We have some existing automation tasks used for shutting down and starting up Azure VMs during out of hours - for now I've just added one of our pooled hosts to a start up schedule within this.

**Comment by mgustin2020** [comment]
> We have some existing automation tasks used for shutting down and starting up Azure VMs during out of hours - for now I've just added one of our pooled hosts to a start up schedule within this.

Can you provide more details on what you did to accomplish this?

**Comment by DougDaz** [comment]
> > We have some existing automation tasks used for shutting down and starting up Azure VMs during out of hours - for now I've just added one of our pooled hosts to a start up schedule within this.
> 
> Can you provide more details on what you did to accomplish this?

Sure - it's probably a bit out of date now as we set it up a couple of years ago - however we basically created an Automation Account with a run as account and then created a Runbook with the below code. We can then set a schedule for each VM to startup or shutdown (we need a seperate one for each operation) - so you just need to enter the VM name, RG and action (startup or shutdown) parameters for each schedule and then set up the scheduled times

# Input Parameters for
# - VmName: name of the vm to perform action to
# - ResourceGroupName: resource group where the vm belongs to
# - VmAction:action to perform (startup or shutdown)
Param(
 [string]$VmName,
 [string]$ResourceGroupName,
 [ValidateSet("Startup", "Shutdown")]
 [string]$VmAction
)
 
# Authenticate with your Automation Account
$Conn = Get-AutomationConnection -Name AzureRunAsConnection
Add-AzureRMAccount -ServicePrincipal -Tenant $Conn.TenantID `
-ApplicationID $Conn.ApplicationID -CertificateThumbprint $Conn.CertificateThumbprint
 
# Startup VM
IF ($VmAction -eq "Startup") {
    Start-AzureRmVM -Name $VmName -ResourceGroupName $ResourceGroupName
}
 
# Shutdown VM
IF ($VmAction -eq "Shutdown") {
    Stop-AzureRmVM -Name $VmName -ResourceGroupName $ResourceGroupName -Force
}

**Comment by nakranimohit0** [comment]
We will not be adding any new features to the existing scaling tool. This feature will be included in the new scaling service that is currently under development as part of WVD
