### ISSUE TITLE
Logic App has bad URI

### ISSUE THREAD

**Issue by VikasPullagura-MSFT** [Azure/RDS-Templates#521]
After I ran the second script and created the logic app information, I had to go back and edit the URI to only include the URL plus the token. Can you double check that the webhook URI is actually passing on the correct logic? To be clear, as another user pointed out, it fails Http POST due to bad Webhook URI. So instead of The provided` '"CliXml": "<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\">\r\n <S>https://e15a9a62-09b7-4632-a267-0d303ba9559a.webhook.wus2.azure-automation.net/webhooks?token=TOKENHERE_x000D__x000A_</S>\r\n</Objs>"' `it should only be `https://e15a9a62-09b7-4632-a267-0d303ba9559a.webhook.wus2.azure-automation.net/webhooks?token=TOKENHERE`

This issue was opened as doc feedback and hence redirecting here to the expected RDS GitHub page.

Original Issue [#59715](https://github.com/MicrosoftDocs/azure-docs/issues/59715)

**Comment by VikasPullagura-MSFT** [comment]
@hoppyshaw Thank you for your posting your query. I have created the issue for your as you have posted the original issue as doc feedback. Please follow this issue for further updates on this.

**Comment by ChrisLacHOC** [comment]
You URI must only contain https://e15a9a62-09b7-4632-a267-0d303ba9559a.webhook.wus2.azure-automation.net/webhooks?token=TOKENHERE remove the last **x000D__x000A**

**Comment by nakranimohit0** [comment]
@hoppyshaw
What PowerShell version are you using ? You can check by printing the value of this variable: `$PSVersionTable`
Can you also provide us the output of the value of this variable `$Params` that contains all the parameters passed on to `CreateOrUpdateAzLogicApp.ps1` ? You can mask out any sensitive info that you'd like.

**Comment by nakranimohit0** [comment]
@hoppyshaw
This has been fixed. Please follow these instructions to re download the updated the script: https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script#create-or-update-an-azure-automation-account
