### ISSUE TITLE
Feature Request: Scale out as # of users per host

### ISSUE THREAD

**Issue by BrendanBTO** [Azure/RDS-Templates#522]
I'm working on a deployment of WVD Spring 2020 for Windows 10 multi-session. We're also running MS Teams which is pretty CPU intensive. I calculate that we can get about 5 sessions on a 16 core VM. ~3 CPU per sessions. The scaling tool uses SessionThresholdPerCPU and the minimum value seems to be 1. From what I can tell the scale out functionality cannot support 1 session occupying more than 1 CPU.  For example 5 sessions 16 CPU would be .31 sessions per CPU. Please confirm if the scaling tool has a way to manage this.

**Comment by nakranimohit0** [comment]
@BrendanBTO 
`SessionThresholdPerCPU` can be decimal. You can set it to .33 and it will work as expected.
