### ISSUE TITLE
power state: 'Info Not Available' trigger Start new VM #4a-WVD-scaling-logicapps

### ISSUE THREAD

**Issue by pcamposs** [Azure/RDS-Templates#529]
If for some reason azure does not correctly deliver the state of a VM that is in the "Running" state, on some occasions it delivers the "Info not Available". With this information the Script starts a new VM, since it is not necessary

could you add double validation of Azure information and WVD information?

[506] Session host: 'VMapp-0.domain.local', power state: 'Info Not Available', status: 'Unavailable', update state: 'Succeeded', sessions: 0, allow new session: False

**Comment by nakranimohit0** [comment]
@pcamposs 
In your particular case, not only the status of the session host is `Unavailable`, the session host is also in drain mode. The scaling tool will start a new VM regardless of whether power state was reported as `Running` or `Info not Available`.

In general, I don't think its a good idea for the tool to assume that `Info not Available` means the VM is in `Running` state. In fact, it is safer to assume the reverse to always make sure there are some running VMs to handle user sessions.

@RoopChevuri FYI
