### ISSUE TITLE
Scaling Tool returns No need to start/stop any session hosts Off Peak Hours

### ISSUE THREAD

**Issue by BrendanBTO** [Azure/RDS-Templates#534]
After I've configured the scaling tool I notice that it does not stop any session hosts after peak hours. The log analytics workspace shows that it logs off peak hours, running session hosts 2/2 and min required session hosts 1. When the logic app runs it returns: No need to start/stop any session hosts

**Comment by BrendanBTO** [comment]
Spring 2020 WVD by the way.

**Comment by nakranimohit0** [comment]
@BrendanBTO 
Can you please share the complete log and the version of the runbook script described [here](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script#reporting-issues) ?

**Comment by BrendanBTO** [comment]
v0.1.35 on the runbook script. Let me get the logs after removing unwanted items.

**Comment by BrendanBTO** [comment]
Logs

[query_data.xlsx](https://github.com/Azure/RDS-Templates/files/5092514/query_data.xlsx)

**Comment by nakranimohit0** [comment]
@BrendanBTO 

This is expected.

Please note this log line: `[180] Number of   user sessions is more than 90 % of the max number of sessions allowed with   minimum number of running session hosts required (4). Adjusted minimum number   of running session hosts required to 2`

Your host pool's `MaxSessionLimit` is set to 5 / session host and you have total 5 users logged in to the host pool. So if you shutdown 1 VM with only 1 VM available, any new users after all 5 users log back in to first VM will not be able to login to the host pool and they will run into resource not available error. So, the tool also keeps enough VMs available to make sure the total number of sessions in the host pool is less than 90 % of the max number of sessions allowed in the host pool. [More info](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script#how-the-scaling-tool-works)

As a workaround, you can increase the `MaxSessionLimit` to 6 or higher and the tool should shutdown the other VM.
