### ISSUE TITLE
MSIX Staging Script Fails

### ISSUE THREAD

**Issue by BrendanBTO** [Azure/RDS-Templates#536]
In my testing for MSIX packaging tool / app attach scripts. I have a package for Notepad++. When I attempt to run the staging script it mounts the VHD but fails due to a signing error. Is there any documentation for the PFX certificate / code signing or whatever the requirements are?

**Comment by nakranimohit0** [comment]
+ @stgeorgi

**Comment by stgeorgi** [comment]
Hi, the requirements for MSIX certificate signing are here https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing.
