### ISSUE TITLE
Shared Image Gallery Parameters missing for WVD deploy

### ISSUE THREAD

**Issue by danielmarker** [Azure/RDS-Templates#537]
Hi there,

So recently I have been working with Azure Image Builder as part of DevOps - and created "Gold images" from there.

I am looking to now deploy these images into a WVD Host Pool...

Found this from Everink: https://github.com/Everink/RDS-Templates/pull/1/files

wonder if you had thoughts on using this from Everink - or when this feature will be included in the "official" RDS-Templates?

Any help gratefully received.

Cheers

Dan

**Comment by danielmarker** [comment]
I can see a PR ready for this:
#408  - could this be looked at to ensure we can make best use of SIG?

**Comment by Misterjohnson87** [comment]
We use SIG images fine with these templates. Under the parameter "vmCustomImageSourceId" - Give this the resource ID of your SIG image and it will deploy a hostpool from the image. 

For example it parameter you'd give it would be: /subscriptions/xxxxxx/resourceGroups/xxxx/providers/Microsoft.Compute/galleries/xxxx/images/xxxx - This will use the latest version. If there's a specific version just grab the Resource ID of that which will look like the below:

/subscriptions/xxxxxx/resourceGroups/xxxx/providers/Microsoft.Compute/galleries/xxxx/images/xxxx/Versions/0.0.1

**Comment by lintFan** [comment]
@danielmarker Are you using the Windows Virtual Desktop (classic) release (Formerly known as the Fall 2019 release) or the later Windows Virtual Desktop release that uses Azure Resource Manager objects (Formerly known as the Sprint 2020 release)?

I think that the suggestion by Misterjohnson87 will only work for the the Spring 2020 release templates [here](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/CreateAndProvisionHostPool) and [here](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/AddVirtualMachinesToHostPool)

**Comment by danielmarker** [comment]
Thanks @lintFan and @Misterjohnson87  we will give that a go with the SIG parameters - we are using Spring 2020 via ARM. Cheers
