### ISSUE TITLE
4-WVD-scaling-tool - Failed to send a log off message to user

### ISSUE THREAD

**Issue by tadhgclifford** [Azure/RDS-Templates#540]
Error: User session ID not found 
Fails to send log off message and fails to log off user as a result

Runbook Script Version:
v0.1.35

Az.Accounts version 1.9.3
Az.Compute version 4.3.0
Az.Resources version 2.5.0
Az.Automation version 1.4.0
OMSIngestionAPI version 1.6.0
Az.DesktopVirtualization version 2.0.0

Run As account expires 2/10/2021, 12:00 AM

All Logs attached
[ARMscalingError.docx](https://github.com/Azure/RDS-Templates/files/5136022/ARMscalingError.docx)

**Comment by pcamposs** [comment]
Same error 
[291] Failed to force log off user: 'DOMAIN\user', session ID: 113 Exception : System.Exception: [404] : ActivityId: AAAAAA-BBBB-473e-a303-ed28bf6662a4 Error: User session ID not found TargetObject : { SubscriptionId = XXXXXX-YYYY-ZZZZ-AAABB-cccccccccc, ResourceGroupName = RESOURCE-RGP, HostPoolName = RESOURCE-PD, SessionHostName = Server-0.domain.local, Id = 113, Force = True } CategoryInfo : InvalidOperation: ({ SubscriptionI... Force = True }:<>f__AnonymousType20`6) [Remove-AzWvdUserSession_Delete], Exception FullyQualifiedErrorId : 404,Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Cmdlets.RemoveAzWvdUserSession_Dele te ErrorDetails : ActivityId: AAAAAA-BBBB-473e-a303-ed28bf6662a4 Error: User session ID not found InvocationInfo : System.Management.Automation.InvocationInfo ScriptStackTrace : at Remove-AzWvdUserSession<Process>, C:\Modules\User\Az.DesktopVirtualization\exports\ProxyCmdletDefinitions.ps1: line 3437 at TryForceLogOffUser<Process>, <No file>: line 287 at TryResetSessionHostDrainModeAndUserSessions<Process>, <No file>: line 326 at <ScriptBlock>, <No file>: line 807 PipelineIterationInfo : {} PSMessageDetails :

**Comment by rpeibon** [comment]
same issue

Exception : System.Exception: Failed to send a log off message to user: 'SOFTLANDCLOUD\caleman1', session ID: 115 ---> System.Exception: [404] : ActivityId: b958cfaa-dbe3-4717-8e5d- Error: User session ID not found --- End of inner exception stack trace --- TargetObject : CategoryInfo : OperationStopped: (:) [], Exception FullyQualifiedErrorId : Failed to send a log off message to user: 'SOFTLANDCLOUD\caleman1', session ID: 115 ErrorDetails : InvocationInfo : System.Management.Automation.InvocationInfo ScriptStackTrace : at <ScriptBlock>, <No file>: line 650 PipelineIterationInfo : {} PSMessageDetails : At line:741 char:3 + Write-Log -Err $ErrMsg -ErrorAction:Continue + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

**Comment by pcamposs** [comment]
any comment, any feedback, workaround ?

**Comment by nakranimohit0** [comment]
@pcamposs @rpeibon @tadhgclifford 

I'm not able to repro this in my environment.
Can you make sure that the session actually existed when the command was run ?
Are you able to repro this error when running the command locally manually ? https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/wvd-scaling-script/ARM_based/basicScale.ps1#L729

**Comment by rpeibon** [comment]
hi guys,

when i send the message manually is workininig but the script enver send
that. u can look in this picture.

[image: repro-error-hostpool.png]

**Comment by rpeibon** [comment]
and this is happened too, when the script go to logoff the user they get
stuck in the backend after computer is stopped.

[image: image.png]

**Comment by Xandven** [comment]
I've debugged this issue and finally figured out what is causing the error. The SessionHostName parameter is case-sensitive so unless all your host names are all lower-case the script will fail (the script runs ToLower on the SessionHostName variable). 

My workaround is to use the hostname as returned in the session.

```PS
[string]$SessionID = $Session.Name.Split('/')[-1]

[string]$HostName = $Session.Name.Split('/')[-2]
...
Send-AzWvdUserSessionMessage -ResourceGroupName $ResourceGroupName -HostPoolName $HostPoolName -SessionHostName $HostName -UserSessionId $SessionID -MessageTitle $LogOffMessageTitle -MessageBody "$LogOffMessageBody You will be logged off in $LimitSecondsToForceLogOffUser seconds"
```

**Comment by tadhgclifford** [comment]
@Xandven many thanks for your reply and suggestion. That makes perfect sense. However, I tried to update my script as you suggested and I still get the same error, i.e. User session ID not found.

Would you be able to upload your working version of the entire PowerShell script so that I can see where I am going wrong? Thanks in advance.

**Comment by Xandven** [comment]
@tadhgclifford I have updated my workaround above as I forgot to include the part about Get-AzWvdUserSession. Sorry about that. Just update the loop that gets the session host objects at the start of the script and replace the if block that gets the sessions and sends the message.  I hope that will solve the problem for you.

**Comment by tadhgclifford** [comment]
@Xandven I have updated my script and it all works perfectly! Thank you so much for your help!

**Comment by nakranimohit0** [comment]
This has been fixed in the latest version. @Xandven thank you for your help on this.
