### ISSUE TITLE
WVD autoscaling tool

### ISSUE THREAD

**Issue by merilthomas18** [Azure/RDS-Templates#544]
Please help with WVD auto scaling tool

**Comment by nakranimohit0** [comment]
What is this issue about ? https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script#report-issues

**Comment by nakranimohit0** [comment]
@merilthomas18 I don't see any information on what this issue is about ? https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script#report-issues
