### ISSUE TITLE
Why is it needed to check registry when installing a RDAgent in vm?

### ISSUE THREAD

**Issue by rongting** [Azure/RDS-Templates#546]
Hi, we have a requirement that to move a virtual machine from one host pool to another. And when binding vm to host pool, session host needs to be created by installing RDAgent in this vm. So if the RDAgent is installed once, it will not install it anymore. That is because you add this verify in your Script-AddRdshServer.ps1 :  https://github.com/Azure/RDS-Templates/blob/ad2b01d5bb654eda46214405420c5831e8a91b88/ARM-wvd-templates/DSC/Script-AddRdshServer.ps1#L45

I wonder if you can delete this logic so we can easily rebind a vm to a new host pool.

**Comment by lintFan** [comment]
@rongting The reason why it checks for the registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\RDInfraAgent is to prevent it from re-running on VMs that are already registered as session hosts; when the template runs it always uninstalls any existing RDAgent ( which is actually named "Remote Desktop Services Infrastructure Agent") msi installations and then reinstalls it with the registration key for the host pool when it runs on the VM.

For your use case I suggest uninstalling the RDAgent msi on the VM before you try to move it to the new host pool, that uninstall process will remove the registry key the ARM template is looking for and will let the template run again on the VM. Will that work for you? 

For a reference of how to uninstall the rdagent you can look at the function InstallRDAgents  in https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/DSC/Functions.ps1 , it is this section

```
while ($true) {
    try {
        $oldAgent = Get-Package -ProviderName msi -Name "Remote Desktop Services Infrastructure Agent"
    }
    catch {
        #Ignore the error if it was due to no packages being found.
        if ($PSItem.FullyQualifiedErrorId -eq "NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackage") {
            break
        }

        throw;
    }

    $oldVersion = $oldAgent.Version
    $productCodeParameter = $oldAgent.FastPackageReference

    RunMsiWithRetry -programDisplayName "RD Infra Agent $oldVersion" -isUninstall -argumentList @("/x $productCodeParameter", "/quiet", "/qn", "/norestart", "/passive") -msiOutputLogPath "C:\Users\AgentUninstall.txt" -msiLogVerboseOutput:$EnableVerboseMsiLogging
}

```
