### ISSUE TITLE
4-WVD-scaling-tool - Creating the Azure Logic App Fails

### ISSUE THREAD

**Issue by briangig** [Azure/RDS-Templates#548]
I am not able to enumerate my host pools via `Get-AzResource`

When running the script from https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script#create-the-azure-logic-app-and-execution-schedule, I get:

`PS C:\Temp> .\CreateOrUpdateAzLogicApp.ps1 @Params`
`C:\Temp\CreateOrUpdateAzLogicApp.ps1 : Cannot bind argument to parameter 'HostPoolName' because it is an empty string.`

When I try to enumerate them manually, I get nothing back.

`PS C:\Temp> Get-AzResource -ResourceType "Microsoft.DesktopVirtualization/hostpools"`
`PS C:\Temp>`

Does this script require the Spring 2020 release?  I am still on the Fall 2019 release, but the documentation makes no mention of that requirement.

**Comment by nakranimohit0** [comment]
@briangig  I believe you are using the wrong documentation. For Fall 2019 release: https://aka.ms/wvdscaleclassic
