### ISSUE TITLE
Hostpool without AVSet fails

### ISSUE THREAD

**Issue by glthob** [Azure/RDS-Templates#551]
I tried creating Hostpool using this ARM template, it works good if i set AVSet to True.

However, it fails with below error if i set AVSet to False. I need to have a hostpool more than 200 VMs and i need to create it without AV set. Help is greatly appreciated.

![2020-09-21 14_53_11-HZoA vs WVD-Compete-- WS1 vs Intune - OneNote](https://user-images.githubusercontent.com/71665868/93808622-3cf10880-fc1a-11ea-85f8-dc899c2642b9.png)

**Comment by lintFan** [comment]
@glthob Which ARM template did you deploy? Can you post a link to it?

**Comment by glthob** [comment]
1-Create-and-provision-host-pool-arm. URL https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/CreateAndProvisionHostPool

**Comment by datr93** [comment]
Looking at this I think you can just remove the availability set parameter -AvailabilitySetName "myAvailabilitySet" in the template

**Comment by datr93** [comment]
https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/nestedtemplates/managedDisks-galleryvm.json#L333

**Comment by datr93** [comment]
seems like createAvailabilitySet flag doesn't work properly

**Comment by glthob** [comment]
is there a way to get it fixed? how do i deploy it without AV set

**Comment by datr93** [comment]
quickest way for you is to remove: 

"availabilitySet": {
                    "id": "[resourceId('Microsoft.Compute/availabilitySets/', concat(parameters('rdshPrefix'), 'availabilitySet-', parameters('location')))]"
                },

from the nestedtemplate you're using: https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/nestedtemplates

Then you'll need to host the nested template somewhere (I recommend using azure storage blob).

Lastly you'll need to point ur template there:

"nestedTemplatesLocation": {
      "type": "string",
      "metadata": {
        "description": "The base URI where artifacts required by this template are located."
      },
      "defaultValue": "Path to the hosted nested template"
    },

Otherwise i'll try to get it done this sprint.

**Comment by glthob** [comment]
I'm a newbie in using ARM templates :) .. I'll give it a shot... Would be great having it fixed in the template .. Appreciate your inputs

**Comment by glthob** [comment]
@datr93 your suggestion worked.. thank you.

**Comment by jks05c** [comment]
Echoing this- we are also trying to deploy without AV Sets

**Comment by alishavez7** [comment]
Hi Team,

Unable to deploy the hostpool with Availabilityset, getting the below error

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidParameter\",\r\n \"message\": \"The entity name 'availabilitySetName' is invalid according to its validation rule: ^[^_\\\\W][\\\\w-._]{0,79}(?<![-.])$.\",\r\n \"target\": \"availabilitySetName\"\r\n }\r\n}"}]}

If i change the availabilityset name parameter then it create the availabilityset but hostpool vm deployment failed with below error

Main template failed with below error:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidTemplate\",\r\n \"message\": \"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'.\"\r\n }\r\n}"}]}

And VM nested template failed with this error:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidTemplate\",\r\n \"message\": \"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'.\"\r\n }\r\n}"}]}

Seems its bug with this template, could someone help me urgently.

**Comment by philipktlin** [comment]
Currently the template only have a boolean flag to control if an availability set is required to be created.  If you dive deeper, VM is also created with availability set.  The boolean flag is just to controlled if the availability set (with predefined naming pattern) already exists.

We are working on adding availability option parameter to support creating VM without availability set.  Will probably be released in Feb 2021.  Will keep post here.

**Comment by diegodct** [comment]
@philipktlin Is there any update on this ? Thank you in advanced !

**Comment by philipktlin** [comment]
Thanks for checking out.  We are going to support availability option in Azure Portal and will update ARM templates in this repo.  Will post PR link here once ready.

**Comment by philipktlin** [comment]
I created this PR, https://github.com/Azure/RDS-Templates/pull/604 with availability option support.  We would like to ask community to review this change and is targeted to commit on Mar 22.  But you are welcome to use it any time.  Thanks for your patience and support.

**Comment by diegodct** [comment]
Thanks for the update @philipktlin. Will this option be available in Azure Portal as well ? and will it require to re-create hostpools ? Thank you.

**Comment by philipktlin** [comment]
It is released in Azure Portal.  You can create VMs/session hosts with availability option when creating a new host pool or adding VMs to existing host pool.

**Comment by KateLi2013** [comment]
we still cannot use this template to deploy the Hostpool and session host with error below: please help, since my customer would like to use this template in his transform. 
 

  {
    "id": "/subscriptions/0d942dd6-0ff2-4601-a9da-0ae82683948b/resourceGroups/zsjy-rg-wvd/providers/Microsoft.Resources/deployments/Microsoft.Template-20210304150804/operations/227950C51E2E6711",
    "operationId": "227950C51E2E6711",
    "properties": {
      "provisioningOperation": "Create",
      "provisioningState": "Failed",
      "timestamp": "2021-03-04T07:08:30.5348425Z",
      "duration": "PT18.5634072S",
      "trackingId": "55ff0d17-1a76-4f22-a872-b5d333819b07",
      "serviceRequestId": "9d4ed82e-ae6a-4274-9808-93b5ecc9f5a3",
      "statusCode": "Conflict",
      "statusMessage": {
        "status": "Failed",
        "error": {
          "code": "DeploymentFailed",
          "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
          "details": [
            {
              "code": "BadRequest",
              "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"The entity name 'availabilitySetName' is invalid according to its validation rule: ^[^_\\\\W][\\\\w-._]{0,79}(?<![-.])$.\",\r\n    \"target\": \"availabilitySetName\"\r\n  }\r\n}"
            }
          ]
        }
      },
      "targetResource": {
        "id": "/subscriptions/0d942dd6-0ff2-4601-a9da-0ae82683948b/resourceGroups/zsjy-rg-wvd/providers/Microsoft.Resources/deployments/AVSet-linkedTemplate-",
        "resourceType": "Microsoft.Resources/deployments",
        "resourceName": "AVSet-linkedTemplate-"
      }
    }
  }
]

**Comment by philipktlin** [comment]
With this new template, customers need to provide the availability option parameter.  Based on the error, customers provides "AvailabilitySet" as availability option.  Therefore customers also need to provide availability set name to "availabilitySetName" parameter.  It seems this parameter is missing or invalid value, What is the value customer passed to this parameter?

**Comment by abhilash-keloth** [comment]
I have tried the latest one with availabilitySetName as testavset-wvd. It actually creates availability sets,hostpool and appgroup in the portal but it throws below error and fails deploying session hosts.
message": "The entity name 'availabilitySetName' is invalid according to its validation rule: ^[^_\\W][\\w-._]{0,79}(?<![-.])$."

**Comment by philipktlin** [comment]
PR https://github.com/Azure/RDS-Templates/pull/604 is committed to master with availability option support.
