### ISSUE TITLE
4-WVD-scaling-tool - ConnectionFailedOrchestrationFailureOnUnhealthyHost Errors

### ISSUE THREAD

**Issue by bgawale** [Azure/RDS-Templates#552]
We have have been using the GA version the WVD in our production environment and have also configured ARM based **Auto-scaling tool** that leverages automation account and logic app to turn ON and OFF session hosts based on the peak time and user connections. 

**Auto scale configuration:** 
Host pool mode - shared
Host pool connection threshold - 10
Each session host instance - 2 vCores
Sessions allowed per core - 6

**Problem:**
It  works fine in most of the case, however some times we are seeing constant logs appearing in the session details mentioning error below during peak times when auto-scale comes in the action. 

**Error:** 
ConnectionFailedOrchestrationFailureOnUnhealthyHost: Failed orchestration on session host ≤session_host_name≥ id=77d6d2fa-9b46-4251-822e-6b7c49206049 with state Unhealthy.

**Potential cause:**
We suspect that when the allowed connection for session host / session host threshold is hit i.e. 10 connections - auto scale clearly is starting new session host, however while the new session host is starting up - when new user tries to establish the connection or surge of user connection arrives then the WVD load balancer is trying to redirect these new incoming user sessions to the session host that is still being started and not fully ready and it is causing an error. 

This seem to be the design issue associated with the auto-scaling tool or if there is any workaround to address this?

**_[Update]:_** We have already tried opening a standard support request with Azure support team for this and have been informed that this is still un-supported and the WVD engineering team is still working on this feature so tool is not really recommended for the production use. Can anyone confirm?

**Comment by lintFan** [comment]
@bgawale Hi, I can confirm that the scaling tool is supported by Microsoft support. You can point the support team to the ["report issues" section ](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script#report-issues) of the scaling tool docs that says "Issue reports for the scaling tool are currently being handled by Microsoft Support."

**Comment by bgawale** [comment]
Yes that's exactly what I did, however the support representative mentioned that the issue does not seem to be associated with scaling tool as it is working fine so they have to go ahead and close the ticket.

**Comment by lintFan** [comment]
@bgawale Please post your support ticket id and I will pass it on to the support management so they can get this support process fixed for you.

**Comment by bgawale** [comment]
@lintFan thanks for the response, here is the support ticket id - 120091823000467

**Comment by nakranimohit0** [comment]
@bgawale are you still running into the issue ? Are you able to repro this consistently ? Did you talk the support about this ?

**Comment by bgawale** [comment]
We had to put a workaround in place to get more session hosts available before peak business hour starts to avoid this error, however we were able to reproduce this quite consistently few weeks back. After talking to support (refer the ticket number mentioned in one of the comment above) we were told - _"the issue does not seem to be associated with scaling tool as it is working fine"_

**Comment by nakranimohit0** [comment]
@bgawale this issue doesn't seem to be related to the scaling tool. The scaling tool scales VMs in and out, it doesn't control whether users can access WVD resources. Today, scaling tool doesn't proactively start new VMs for the morning logon storm and that is probably why users are getting this error. This feature is being developed in the new scaling service that is under development.
