### ISSUE TITLE
Update-AzWvdHostPool

### ISSUE THREAD

**Issue by henrikhelvete** [Azure/RDS-Templates#553]
I would like the possibility to change the VMTemplate parameters on an existing hostpool. This does not seem to be possible and the Update-AzWvdHostPool cmdlet does not implement a -VMTemplate parameter. How can I approach this, if I want to change for example vm sku size, without migrating all appgroups and published apps to a new hostpool?

**Comment by nakranimohit0** [comment]
@henrikhelvete I don't think this is the right channel / repo to raise an issue about the cmdlets. @datr93 please assist.

**Comment by datr93** [comment]
@henrikhelvete feature coming soon. Need to wait for next rollout.

**Comment by henrikhelvete** [comment]
@datr93 thanks for info. Any idea when such a release might come. 

Ps. I also thought this channel seemed a bit off but was sent this link by an azure support rep.
