### ISSUE TITLE
Rename this DSC extension name to the default value, which is: Microsoft.PowerShell.DSC

### ISSUE THREAD

**Issue by brwilkinson** [Azure/RDS-Templates#555]
I think I would like to rename this DSC extension name to the default value, which is: Microsoft.PowerShell.DSC

https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/nestedtemplates/managedDisks-customimagevm.json#L397
 
![default_extensionName](https://user-images.githubusercontent.com/3605266/94322052-3a5a2000-ff46-11ea-98cd-a59d8ec3cc30.jpg)

As you can see above it’s one of the default extension names to make it easier to query.

That way when the DSC extension is later redeployed (by a method other than WVD), it will just simply overwrite the current extension that was deployed from WVD.

-	Currently you would get an error, since you cannot deploy the same extension with a different name.

Am I correct that the customer deploying this … does not have any control over these templates that are used on ?

-	Is there a way to modify this on the user side ? I assume these templates are applied via a Managed Solution in the Portal ?

**Comment by brwilkinson** [comment]
Hi @nakranimohit0 

Are you able to confirm that getting these templates updated is the only way to configure these settings, since this runs as a managed application in Azure?

**Comment by nakranimohit0** [comment]
\+ @datr93

**Comment by brwilkinson** [comment]
Hi @datr93 do you think this is something that you would be interested in updating?

**Comment by philipktlin** [comment]
@datr93 would you please help to answer this questions.
1. Do you know PowerShell DSC supporting multiple version on a single machine?
2. Do we need to ensure that a specific version of PowerShell DSC should be run in order to support WVD scenario?

**Comment by datr93** [comment]
i'm not sure can you do some digging.

**Comment by brwilkinson** [comment]
I am not exactly sure on the question . .  however any particular VM extension can only exist once.

if you deploy it a second time, it will work, so long as you have the exact same name.

if you deploy the same extension (type) with a different name it will fail, unless you delete the extension first.

e.g. the script extension or the dsc extension.

By using a non default name, when you deploy this for WVD, you limit anyone else redeploying over the top of the to re-use the same extension (type).
