### ISSUE TITLE
Support for Depth-First load balancing

### ISSUE THREAD

**Issue by chrisjones00** [Azure/RDS-Templates#556]
I have enabled the script for my host pools which are configured for "Depth-First" load balancing, however the script is running and changing the load balancing on the Host pool to "Breadth-First".

**Comment by nakranimohit0** [comment]
@chrisjones00 
You can this param to the request body of the HTTP request of logic app scheduler: "SkipUpdateLoadBalancerType": true,
This will prevent the script from changing the load balancer type.
