### ISSUE TITLE
hostpool deployment failed with AVSet and also without AVSet

### ISSUE THREAD

**Issue by alishavez7** [Azure/RDS-Templates#560]
Hi Team,

Unable to deploy the hostpool with Availabilityset, getting the below error

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidParameter\",\r\n \"message\": \"The entity name 'availabilitySetName' is invalid according to its validation rule: ^[^_\\\\W][\\\\w-._]{0,79}(?<![-.])$.\",\r\n \"target\": \"availabilitySetName\"\r\n }\r\n}"}]}

If i change the availabilityset name parameter then it create the availabilityset but hostpool vm deployment failed with below error

Main template failed with below error:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidTemplate\",\r\n \"message\": \"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'.\"\r\n }\r\n}"}]}

And VM nested template failed with this error:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidTemplate\",\r\n \"message\": \"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'.\"\r\n }\r\n}"}]}

Seems its bug with this template, could someone help me urgently.

**Comment by lintFan** [comment]
@alishavez7 Hi, Which ARM template did you deploy? Can you post a link to the template in this repo you are using?

How are you trying to deploy it without the availability set and what error do you get in that case?

**Comment by lintFan** [comment]
Closing due to no response
