### ISSUE TITLE
4-WVD-scaling-tool - Failed to power on /poweroff VM with scaling mechanism 

### ISSUE THREAD

**Issue by jvanzeir** [Azure/RDS-Templates#561]
Hi,

The WVD is working fine and want to implement it for a customer of mine.

I configured the scaling mechanism with Logic app / Automation Account and runbooks, like mentioned in the documentation.
https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script#reporting-issues
But powering on and off the VM does not work at all.

In the Output , you see that need to start 2VM is been mentioned. In my environment there are  3WDV Vm and one is power On and the other 2 are power Off  state. In fact, i would expect that one Vm should be powered on after the schedule of 15 mins. But it doesn't start up.

When playing with the endpeaktime, the Vm's are still running, i expect that 2 VM's should be powered off. This neither works as well.

Any help is very welcome

Cheers

2020-10-21 14:52:58 [340] Request params: 
AADTenantId                   : 4243c4d6-8f65-4eeb-a15b-a0804c3649f0
BeginPeakTime                 : 09:00
ConnectionAssetName           : AzureRunAsConnection
EndPeakTime                   : 12:30
HostPoolName                  : vmpool2
LimitSecondsToForceLogOffUser : 10
LogAnalyticsPrimaryKey        : qTLpEQdIxbkkbdyBn2AfZPVYZRwmOG92P7pHXzf1PB5kINMci1ahnANB8CmFgNGb6NwgrE8iMSpN76VCCgLQWg==
LogAnalyticsWorkspaceId       : 12bd38a4-d1e4-49b6-9e41-070677dd5f17
LogOffMessageBody             : wdi
LogOffMessageTitle            : signed out by wdi
MaintenanceTagName            : customer2
MinimumNumberOfRDSH           : 2
ResourceGroupName             : mum-customer2-rg
SessionThresholdPerCPU        : 1
SubscriptionId                : 83d557b0-9882-4ae2-ba15-e624b5417d84
TimeDifference                : +2
UseARMAPI                     : @{IsPresent=True}

2020-10-21 14:53:00 [343] Log ananlytics is enabled

2020-10-21 14:53:00 [353] Get auto connection from asset: 'AzureRunAsConnection'

2020-10-21 14:53:11 [368] Successfully authenticated with Azure using service principal: 

Name               : 
Account            : d3878c7b-25a5-40a8-9a32-31dda7b37e9c
Environment        : AzureCloud
Subscription       : 83d557b0-9882-4ae2-ba15-e624b5417d84
Tenant             : 4243c4d6-8f65-4eeb-a15b-a0804c3649f0
TokenCache         : Microsoft.Azure.Commands.Common.Authentication.Core.ProtectedFileTokenCache
VersionProfile     : 
ExtendedProperties : {}

2020-10-21 14:53:12 [395] Get Hostpool info of 'vmpool2' in resource group 'mum-customer2-rg'

2020-10-21 14:53:32 [410] Get all session hosts

2020-10-21 14:53:34 [418] Get number of user sessions in Hostpool

2020-10-21 14:53:35 [430] HostPool info: 

ApplicationGroupReference                  : {/subscriptions/83d557b0-9882-4ae2-ba15-e624b5417d84/resourcegroups/mum-cus
                                             tomer2-rg/providers/Microsoft.DesktopVirtualization/applicationgroups/vmpoo
                                             l2-DAG}
CustomRdpProperty                          : 
Description                                : Created through the WVD extension
FriendlyName                               : 
HostPoolType                               : Pooled
Id                                         : /subscriptions/83d557b0-9882-4ae2-ba15-e624b5417d84/resourcegroups/mum-cust
                                             omer2-rg/providers/Microsoft.DesktopVirtualization/hostpools/vmpool2
LoadBalancerType                           : BreadthFirst
Location                                   : eastus
MaxSessionLimit                            : 1
Name                                       : vmpool2
PersonalDesktopAssignmentType              : 
PreferredAppGroupType                      : Desktop
RegistrationInfoExpirationTime             : 
RegistrationInfoRegistrationTokenOperation : None
RegistrationInfoToken                      : 
Ring                                       : 
SsoContext                                 : 
Tag                                        : Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api10.Track
                                             edResourceTags
Type                                       : Microsoft.DesktopVirtualization/hostpools
VMTemplate                                 : {"domain":"cadcloudsolution.com","galleryImageOffer":null,"galleryImagePubl
                                             isher":null,"galleryImageSKU":null,"imageType":"CustomImage","imageUri":nul
                                             l,"customImageId":"/subscriptions/83d557b0-9882-4ae2-ba15-e624b5417d84/reso
                                             urceGroups/mum-image-rg/providers/Microsoft.Compute/images/myvmimage02-imag
                                             e-20201015145507","namePrefix":"custvm2","osDiskType":"StandardSSD_LRS","us
                                             eManagedDisks":true,"vmSize":{"id":"Standard_D2s_v3","cores":2,"ram":8},"ga
                                             lleryItemId":null}
ValidationEnvironment                      : False

2020-10-21 14:53:35 [431] Number of session hosts in the HostPool: 3

2020-10-21 14:53:36 [453] Using current time: 2020-10-21 14:53:36, begin peak time: 2020-10-21 09:00:00, end peak time: 2020-10-21 12:30:00

2020-10-21 14:53:36 [460] Off peak hours

2020-10-21 14:53:36 [486] Get all VMs, check session host status and get usage info

2020-10-21 14:53:54 [494] VM 'custvm2-0' is in maintenance and will be ignored

2020-10-21 14:53:54 [494] VM 'custvm2-1' is in maintenance and will be ignored

2020-10-21 14:53:55 [494] VM 'custvm2-2' is in maintenance and will be ignored

2020-10-21 14:53:56 [563] Number of running session hosts: 0 of total 0

2020-10-21 14:53:56 [564] Number of user sessions: 0 of total allowed 0

2020-10-21 14:53:57 [565] Number of user sessions per Core: 0, threshold: 1

2020-10-21 14:53:57 [566] Minimum number of running session hosts required: 2

2020-10-21 14:53:58 [186] Number of running session host is less than minimum required. Need to start 2 VMs

2020-10-21 14:53:58 [596] All session hosts are running

2020-10-21 14:53:59 [597] End

**Comment by nakranimohit0** [comment]
@jvanzeir as you can see in the logs, all 3 VMs have maintenance tag "customer2" assigned to them. Because of this, the script is going to completely ignore them and not take any action on them. Once you remove the tag from VM instances in Azure, the scaling tool will start acknowledging the VMs and scale them
