### ISSUE TITLE
documentation: RDS-Templates / rds-deployment-ha-gateway / azuredeploy.parameters.json

### ISSUE THREAD

**Issue by jagilber** [Azure/RDS-Templates#57]
documentation: RDS-Templates / rds-deployment-ha-gateway / azuredeploy.parameters.json

issue:
rds-deployment installs 1 rd gateway.

deploying rds-deployment-ha-gateway with default value of '2' for 'numberOfWebGwInstances' will deploy 2 additional instances of remote desktop gateway. this will give a total of 3 rd gateways.

setting value to '1' for numberOfWebGwInstances will deploy 1 additional rd gateway so that the total will be 2 rd gateways.

changing default value from 2 to 1

change from:
    "numberOfWebGwInstances": { 
       "value": 2 
     }, 

change to:
    "numberOfWebGwInstances": { 
       "value": 1 
     },

**Comment by afilenkov** [comment]
Merged
