### ISSUE TITLE
WVD Spring - AutoScaling-Question: why is the runbook triggered by a Logic App

### ISSUE THREAD

**Issue by XristophD** [Azure/RDS-Templates#571]
Hello, 
I was wondering why the architectural decision was taken to trigger the runbook via a webhook from a logic app. 
A runbook could be triggered on schedule, also parameters could be passed into the scheduled run. 

Isn't it just yet another azure resource we need to deploy - wouldn't it be sufficient to trigger via a runbook schedule and rewrite the scaling script so it takes the params not from the request body of the webhook call but the params from the runbook schedule? 

I may overlook something here in regards of the Logic App. Any input would be highly appreciated.

Best Regards
Christoph

**Comment by nakranimohit0** [comment]
@XristophD logic apps schedulers has intuitive UI designer allowing the admins to easily change parameters such as `SessionThresholdPerCPU` without needing to run any ARM template or script. However, with runbook schedules, once initialized, the parameters can only be changed via a script or ARM templates making it difficult for admins to manage the tool.
