### ISSUE TITLE
networkSecurityGroupRules default value is not an array

### ISSUE THREAD

**Issue by thecohenoam** [Azure/RDS-Templates#572]
https://github.com/Azure/RDS-Templates/blame/b996d113d1b11ab6e51dbeddef3df49c1c260694/ARM-wvd-templates/nestedtemplates/managedDisks-customimagevm.json#L154

This should be an array and not an object.

**Comment by philipktlin** [comment]
If you are talking about networkSecurityGroupRules; it is array type already.

**Comment by thecohenoam** [comment]
Not in [`managedDisks-customimagevm.json`](https://github.com/Azure/RDS-Templates/blame/b996d113d1b11ab6e51dbeddef3df49c1c260694/ARM-wvd-templates/nestedtemplates/managedDisks-customimagevm.json#L154)

**Comment by philipktlin** [comment]
Correct me if I am wrong.  [Iine 155](https://github.com/Azure/RDS-Templates/blame/b996d113d1b11ab6e51dbeddef3df49c1c260694/ARM-wvd-templates/nestedtemplates/managedDisks-customimagevm.json#L155) specifies array as type. right?

**Comment by thecohenoam** [comment]
You are correct Iine 155 does specifies array as type, but [line 159](https://github.com/Azure/RDS-Templates/blame/b996d113d1b11ab6e51dbeddef3df49c1c260694/ARM-wvd-templates/nestedtemplates/managedDisks-customimagevm.json#L159) specifies an **object** as the default value.
It's only working because the value is overridden by `AddVirtualMachinesTemplate.json`.
An error will be thrown if I use `managedDisks-customimagevm.json` alone, without specifying a value for `networkSecurityGroupRules`.

Notice how [AddVirtualMachinesTemplate.jso#252](https://github.com/Azure/RDS-Templates/blob/b996d113d1b11ab6e51dbeddef3df49c1c260694/ARM-wvd-templates/AddVirtualMachinesToHostPool/AddVirtualMachinesTemplate.json#L252) got the default value right as an array.

**Comment by philipktlin** [comment]
Sorry for the problem.  We will fix it in the next release for ARM template.

**Comment by philipktlin** [comment]
PR is under review: https://github.com/Azure/RDS-Templates/pull/590
