### ISSUE TITLE
Get-AzRoleAssignment : Cannot find principal using the specified options

### ISSUE THREAD

**Issue by gokul2018** [Azure/RDS-Templates#575]
Hi Team,
I've a WVD setup for which i am setting up auto scaling feature using Azure automation and logic app.
Followed the link https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script#how-the-scaling-tool-works

1st step is to login to AzAccount, done that.
------------

2nd step is to pull the the script for creating the Azure Automation account using the following command:
---------------
New-Item -ItemType Directory -Path "C:\Temp" -Force
Set-Location -Path "C:\Temp"
$Uri = "https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/wvd-scaling-script/CreateOrUpdateAzAutoAccount.ps1"
Invoke-WebRequest -Uri $Uri -OutFile ".\CreateOrUpdateAzAutoAccount.ps1"

3rd step is to execute the downloaded script to create automation accounts using the following parameters
------------------------------------------------------------
$Params = @{
     "UseARMAPI"             = $true
     "Location"              = "East US"
    }
.\CreateOrUpdateAzAutoAccount.ps1 @Params

When the above line is executed, it is failing with the following error:

Get-AzRoleAssignment : Cannot find principal using the specified options
At C:\Temp\CreateOrUpdateAzAutoAccount.ps1:83 char:20
+ ... signments = Get-AzRoleAssignment -SignInName $AzContext.Account -Expa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzRoleAssignment], KeyNotFoundException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand
 
I am the owner of the subscription and i have global admin access in the AAD

**Comment by nakranimohit0** [comment]
@gokul2018 
Please make sure you are on the correct subscription and tenant ID by running this command in PowerShell (v7)
`Get-AzContext | FL -Force`

Also make sure either the value of `Account` field from the above output is listed as `SignInName` or the group that you are part of is in one of the role assignments here:
`Get-AzRoleAssignment | FL -Force`
