### ISSUE TITLE
4-WVD-scaling-tool - Issue with deploying logic app in same subscription as automation account, but different subscription than host pool.

### ISSUE THREAD

**Issue by asbtho** [Azure/RDS-Templates#576]
A complete log from the All Logs tab in the job that caused the issue: There is no Job issue. Issue is with deployment of logic app.

The version of the runbook script you're using: v0.1.38

Az.Accounts: 2.1.2
Az.Compute: 4.6.0
Az.Resources: 3.0.0
Az.Automation: 1.4.0
OMSIngestionAPI: 1.6.0
Az.DesktopVirtualization: 2.0.0

The expiration date for your Run As account: 3/17/2021, 1:00 AM

**ISSUE:**
Automation account is updated fine, runbook is created fine.
When creating logic app in the same subscription that automation account is, the script cannot find host pools. Host pools are in another subscription.

**This line returns empty:** 
$WVDHostPool = Get-AzResource -ResourceType "Microsoft.DesktopVirtualization/hostpools" | Out-GridView -OutputMode:Single -Title "Select the host pool you'd like to scale"

**This limitation is written on the documentation:** 
This solution manages VMs in any region, but can only be used in the same subscription as your Azure Automation account and Azure Logic App.

Does this mean that the automation account, the logic app AND the host pool all have to be in the same subscription?

**Comment by nakranimohit0** [comment]
@asbtho 
Yes the HostPool resource object (not the VMs) has to be in the same subscription as the Azure Automation account and Azure Logic App
