### ISSUE TITLE
SIG as a source

### ISSUE THREAD

**Issue by tsrob50** [Azure/RDS-Templates#591]
Could the option to use a Shared Image Gallery be added to the template?

**Comment by lintFan** [comment]
@tsrob50 Hi, are you asking about the ARM templates for Windows Virtual Desktop classic here  https://github.com/Azure/RDS-Templates/tree/master/wvd-templates
or the ARM templates for Windows Virtual Desktop (non-classic) with Azure Resource Manager objects  here https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates ?

**Comment by tsrob50** [comment]
The ARM version, specifically the one to add Sessions Hosts to an existing
Host Pools.

I’m using Image Builder to add updated images to an SIG. this temple would
help to rotate updated session hosts into a host pool as part of an update
workflow.

Thanks
-Travis

**Comment by lintFan** [comment]
@tsrob50 I've labelled this so the team working on those templates will see your request.

**Comment by nakranimohit0** [comment]
Might be related to #537

**Comment by tsrob50** [comment]
That looks like it might be what I am looking for.  I can test in the next couple of days to verify.  

 

Thanks,

Travis

**Comment by lintFan** [comment]
@tsrob50 Feel free to re-open if it didn't work for you.

**Comment by mobilejon** [comment]
According to 537, it says to specify it in vmCustomImageSourceId but that parameter is no longer in the current template.

How would we do it now?
