### ISSUE TITLE
VM has reported a failure when processing extension 'dscextension'

### ISSUE THREAD

**Issue by riglesaum** [Azure/RDS-Templates#592]
When I tried to deploy a host pool I'm getting this issue: 
"
VM has reported a failure when processing extension 'dscextension'. Error message: \"The DSC Extension failed to execute: Error unpacking 'Configuration.zip'; verify this is a valid ZIP package.\nError details: Exception calling \".ctor\" with \"3\" argument(s): \"End of Central Directory record could not be found.\".\r\nMore information about the failure can be found in the logs located under 'C:\\WindowsAzure\\Logs\\Plugins\\Microsoft.Powershell.DSC\\2.80.3.0' on the VM.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "
"
Any pointers?

**Comment by lintFan** [comment]
Hi @riglesaum Are you using this ARM template for [ARM based WVD](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/CreateAndProvisionHostPool) or this one for [non-ARM based WVD (AKA WVD classic)](https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool)?
I wonder if a firewall rule could be blocking the download of Configuration.zip? For example for the ARM based WVD template the URL to the Configuration.zip is listed under [artifactsLocation here](https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/CreateAndProvisionHostPool/CreateHostpoolTemplate.json).

**Comment by riglesaum** [comment]
Hi @lintFan , it was a firewall issue that i was able to find. Thanks!!!
