### ISSUE TITLE
Issue : CreateOrUpdateAzAutoAccount.ps1 script execution Error - New-AzAutomationVariable : {"Message":"The request is  invalid.","ModelState":{"variable.properties.value":["Invalid JSON primitive: https."]}}

### ISSUE THREAD

**Issue by AaaBokkaLe** [Azure/RDS-Templates#595]
been trying to execute the script and getting this error. Ensured the pre-requisites are in place

VERBOSE: Performing the operation "Creating Deployment" on target "WVD".
VERBOSE: 20:12:17 - Template is valid.
VERBOSE: 20:12:17 - Create template deployment 'runbookCreationTemplate'
VERBOSE: 20:12:17 - Checking deployment status in 5 seconds
VERBOSE: 20:12:22 - Checking deployment status in 5 seconds
VERBOSE: 20:12:27 - Resource Microsoft.Automation/automationAccounts/runbooks 'WVDAutoScaleAutomationAccou
nt/WVDAutoScaleRunbook' provisioning status is succeeded
VERBOSE: 20:12:27 - Resource Microsoft.Automation/automationAccounts 'WVDAutoScaleAutomationAccount' provi
sioning status is succeeded
VERBOSE: Performing the operation "For security purposes, the URL of the created webhook will only be view
able in the output of this command. No other commands will return the webhook URL. Make sure to copy down 
the webhook URL from this command's output before closing your PowerShell session, and to store it securel
y." on target "WVDAutoScaleWebhook".
**Automation Account Webhook is created with name 'WVDAutoScaleWebhook'
New-AzAutomationVariable : {"Message":"The request is 
invalid.","ModelState":{"variable.properties.value":["Invalid JSON primitive: https."]}}
At line:226 char:2**
+     New-AzAutomationVariable -Name $WebhookURIAutoVarName -Encrypted  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzAutomationVariable], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.NewAzureAutomationVariable
 

PS C:\Windows\system32>

**Comment by Zipak** [comment]
Same Problem

New-AzAutomationWebhook : Property 'uri' cannot be updated.
At C:\Users\xjaroslav.DAQUAS\Downloads\WVDLogixAutoScale\Scripts\CreateOrUpdateAzAutoAccount.ps1:229 char:13
+ ...  $Webhook = New-AzAutomationWebhook -Name $WebhookName -RunbookName $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzAutomationWebhook], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.NewAzureAutomationWebhook

**Comment by MathiasBaden27** [comment]
I solved my problem with it...
I had to downgrade the Az.Automation module in Powershell to 1.4.0 and after that it worked.

Uninstall-Module -Name Az.Automation
Install-Module -Name Az.Automation -RequiredVersion 1.4.0
Import-Module -Name Az.Automation -RequiredVersion 1.4.0

**Comment by philippwitschi** [comment]
thank you MathiasBaden27

that solved my problem !!!

**Comment by GeorgeSnes** [comment]
I had this exact problem and suspected the module was to blame.

Thanks for clarifying!

**Comment by nakranimohit0** [comment]
@AaaBokkaLe  Not able to reproduce the issue with the following modules:

PS > Get-Module


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.2.4      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     1.4.2      Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationDscNodeReportContent, Export-AzAutomationRunbook, Get-AzAutomationAccount...}
Script     2.3.0      Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-AzOperationalInsightsLinuxPerformanceCollection, Disable-AzOperationalInsightsLinuxSyslogCollection...}
Script     3.2.0      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzADAppCredential...}
Manifest   7.0.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty...}
Manifest   7.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}
Manifest   7.0.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Manifest   7.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}
Script     0.2.0      PowerShellEditorServices.Commands   {Clear-Host, ConvertFrom-ScriptExtent, ConvertTo-ScriptExtent, Find-Ast...}
Binary     0.2.0      PowerShellEditorServices.VSCode     {Close-VSCodeHtmlContentView, New-VSCodeHtmlContentView, Set-VSCodeHtmlContentView, Show-VSCodeHtmlContentView...}
Script     2.2.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}


PS > $PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3

**Comment by AaaBokkaLe** [comment]
Hi Mohit,

Sorry couldn't get more details on this when reported but the issue is resolved once I've update the modules to latest version. 

PS C:\Users\punee> $PSVersionTable

Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      5.1.19041.868                                                                                
PSEdition                      Desktop                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.19041.868                                                                               
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1                                                                                      

ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                       
---------- -------    ----                                ----------------                                                                                                                                                                                       
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                                                                                              

Key   : PSVersion
Value : 5.1.19041.868
Name  : PSVersion


Key   : PSEdition
Value : Desktop
Name  : PSEdition


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions


Key   : BuildVersion
Value : 10.0.19041.868
Name  : BuildVersion


Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion

Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
