### ISSUE TITLE
New-AzAutomationVariable : {"Message":"The request is invalid.}

### ISSUE THREAD

**Issue by MathiasBaden27** [Azure/RDS-Templates#596]
Anyone know what im missing here? Thanks

New-AzAutomationVariable : {"Message":"The request is invalid.","ModelState":{"variable.properties.value":["Invalid
JSON primitive: https."]}}
At C:\WVD\CreateOrUpdateAzAutoAccount2.ps1:234 char:2
+     New-AzAutomationVariable -Name $WebhookURIAutoVarName -Encrypted  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzAutomationVariable], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.NewAzureAutomationVariable

**Comment by AaaBokkaLe** [comment]
Been facing same issue for quite sometime now. Issue # 595

**Comment by MathiasBaden27** [comment]
I solved my problem... 
I had to downgrade the Az.Automation module in Powershell to 1.4.0 and after that it worked. 

Uninstall-Module -Name Az.Automation
Install-Module -Name Az.Automation -RequiredVersion 1.4.0
Import-Module -Name Az.Automation -RequiredVersion 1.4.0
