### ISSUE TITLE
Registering a Session Host with terraform-azurerm-windowsvirtualdesktop

### ISSUE THREAD

**Issue by davetustin** [Azure/RDS-Templates#597]
Hi,

I use your script to deploy a Session Host to a Host Pool, and 99% of it works with no issues. I had to update some code but I think that is due to the azurerm provider I am using in Terraform.

I have been trying to fix the RegisterSessionHost function. The script appears to be using the old method of using a WVD Tenant, which now isn't required. 

Is there a way around using the Tenant Name? I think the script that is responsible for this bit is RDS-Templates/wvd-templates/DSC/Script-RegisterSessionHost.ps1.

Any help would be appreciated.

Cheers
Dave

**Comment by lintFan** [comment]
Hi @davetustin 
It sounds like you are using this [Create and provision WVD host pool](https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool)  ARM template which only supports Windows Virtual Desktop (classic), which doesn't support Windows Virtual Desktop with Azure Resource Manager objects. ARM templates for Windows Virtual Desktop with Azure Resource Manager objects are available [here](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/CreateAndProvisionHostPool) and [here](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/AddVirtualMachinesToHostPool).

Does that solve the problem you are having?

**Comment by lintFan** [comment]
The powerhell DSC code that the ARM templates for Windows Virtual Desktop with Azure Resource Manager objects [uses here](https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/DSC/Configuration.ps1) is much simpler and doesn't require the tenant name. It also doesn't doesn't require any of the WVD powershell modules.

There are some helpful notes about how the Configuration.zip it uses is created [here](https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/DSC/README.md).

**Comment by davetustin** [comment]
Hi @lintFan 

That's amazing! How did I not find these! I appreciate you pointing me in the right direction, I just couldn't work out what I needed to do and have been bashing my head against a wall for a couple of weeks!

I will give these a go!

Cheers
Dave
