### ISSUE TITLE
Configuration.ps1 in Configuration.zip missing aadJoin parameter for addSessionHost

### ISSUE THREAD

**Issue by StevenKusters** [Azure/RDS-Templates#598]
https://catalogartifact.azureedge.net/publicartifacts/Microsoft.Hostpool-ARM-1.0.22-preview/managedDisks-galleryvm.json
references
https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration.zip
Configuration doesn't contain the new aadJoin parameter in the AddSessionHost part of the DSC

this is not up to date, while the version from January 25 2021 does contain the parameter:
https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_1-25-2021.zip

**Comment by lintFan** [comment]
@philipktlin or @dhrump can you take a look at this?

**Comment by philipktlin** [comment]
That's the default value we used long time ago.  I think we should update https://catalogartifact.azureedge.net/publicartifacts/Microsoft.Hostpool-ARM-1.0.22-preview/managedDisks-galleryvm.json to use https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_1-25-2021.zip as default value for artifactsLocation parameter.  @dhrump what do you think?

**Comment by philipktlin** [comment]
@StevenKusters why are you using https://catalogartifact.azureedge.net/publicartifacts/Microsoft.Hostpool-ARM-1.0.22-preview/managedDisks-galleryvm.json directly?  This is ARM template used in Azure Portal.  If you want to use ARM template for deployment, you can use ARM template from https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/nestedtemplates/managedDisks-galleryvm.json. Please let me know if it helps.

**Comment by StevenKusters** [comment]
Why am I using this? Because I build most of my custom deloyment templates based on the azure resource deployer and then download the template at the end when I’m done. Because I want to have full control over what happens here, I make these deployment scripts based on a certain API versions and file versions, which I populate with full nested templates skipping the usage of hosted templates as much as possible. This is how I came across the missing parameter in the deployed build. The script I downloaded and wanted to reuse however, was an unchanged script. It referenced the latest resource file which was missing the parameters mentioned, which I found out by looking for a dated release and this is how I found the right file. So this is a bug, because it is a result of a download of the template files at the end of an azure resource deployment, which fails when the exact template is reused.
Please let me know if I can be of any further assistance in this.

**Comment by philipktlin** [comment]
Thanks for sharing your scenario.  Will get back to you asap.

**Comment by philipktlin** [comment]
Thanks for waiting, I am going to update the configuration zip default value in ARM templates.

**Comment by StevenKusters** [comment]
> Thanks for waiting, I am going to update the configuration zip default value in ARM templates.

No problem at all. Like I mentioned in the OP, I had a workaround using the actually datestamped version, so I am just happy this could get resolved! Looking forward to the released build.
Thank you and take care!

**Comment by philipktlin** [comment]
The change in ARM template in Azure Portal is updated, and it will be targeted to release next week.  thanks.
