### ISSUE TITLE
RD Infra Agent and Bootloader install strings don't support spaces

### ISSUE THREAD

**Issue by ld0614** [Azure/RDS-Templates#606]
The latest version of the RDAgentBootLoader contains a space in the title.  (Microsoft.RDInfra.RDAgentBootLoader.Installer-x64 (7).msi) (Downloaded from https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWrxrH).  

This causes the DSC Installation to hang in a transitioning phase as the msiexec command can't recognise the install and therefore throws up the help GUI which as DSC is headless indefinitely locks the installation process:

```
03-10-21 17:14:55 - MSFT_ScriptResource:472 - Installing RDAgent BootLoader on VM C:\DeployAgent\RDAgentBootLoaderInstall\Microsoft.RDInfra.RDAgentBootLoader.Installer-x64 (7).msi
03-10-21 17:14:55 - MSFT_ScriptResource:384 - Installing RDAgent BootLoader

```

If you dump the MSIexec process and analyse the call stack you can see it has called the ShowHelp function and created a dialog box:
![image](https://user-images.githubusercontent.com/20439950/110775905-60a31c00-8257-11eb-9bc5-4ee7b3183031.png)

The fix should be simple: Encapsulate all /i $Path strings so they look like /i '$Path', the main locations for this are around https://github.com/Azure/RDS-Templates/blame/master/wvd-templates/DSC/Functions.ps1#L477

Ideally, the script should go further and timeout the MSIexec installations but that is a more complicated piece of work

**Comment by lintFan** [comment]
@ld0614 Thank you, I will take a look at this. In the mean time the download of Microsoft.RDInfra.RDAgentBootLoader.Installer-x64 has been update so there is no longer a space in the name.

**Comment by ld0614** [comment]
@lintFan thanks for the swift change in installer naming, on a side note I also noticed that the RDAgent msi currently has [1] in its name (Microsoft.RDInfra.RDAgent.Installer-x64-1.0.2800.2800[1].msi) Downloading with PowerShell lower than 7.1 causes this to fail (https://github.com/PowerShell/PowerShell/issues/3174), would it be possible to replace the square brackets with something else please?

**Comment by lintFan** [comment]
@ld0614 When I download the RDAgent from the  [docs ](https://docs.microsoft.com/en-us/azure/virtual-desktop/create-host-pools-powershell#update-the-agent) using this link https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWrmXv I get the name Microsoft.RDInfra.RDAgent.Installer-x64-1.0.2800.2800.msi so it appears to be fixed.

**Comment by dhrump** [comment]
Please reopen if you still see the issue

**Comment by lintFan** [comment]
The MSI names are ok but this bug that doesn't support spaces in the MSI name still exists in the code per the previous comments.

**Comment by webreidi** [comment]
Tracking bug internally. Closing.
