### ISSUE TITLE
Unable to deploy session hosts with avset

### ISSUE THREAD

**Issue by abhilash-keloth** [Azure/RDS-Templates#609]
I have tried the latest one with availabilitySetName as testavset-wvd. It actually creates availability sets,hostpool and appgroup in the portal but it throws below error and fails deploying session hosts.
message": "The entity name 'availabilitySetName' is invalid according to its validation rule: ^[^\W][\w-.]{0,79}(?<![-.])$."

**Comment by philipktlin** [comment]
Just want to confirm, are you using ARM templates from https://github.com/Azure/RDS-Templates/pull/604? if not, please share the link where you get the ARM template.  thanks.

**Comment by abhilash-keloth** [comment]
> Just want to confirm, are you using ARM templates from #604? if not, please share the link where you get the ARM template. And did you pass the value of nestedTemplatesLocation and artifactsLocation parameters to CreateHostpoolTemplate.json?

Thanks for your reply Philip. After using the latest code from the master, I am able to create the session hosts. But the session host VM seems to be unavailable. I didn't try to redeploy or add more but I guess it's due to the version of the agent running inside. I will try to redeploy and also to re-install the agent and will keep you posted. In the mean time please check if anyone has reported similar behavior.

**Comment by philipktlin** [comment]
Which ARM template are you using? [CreateHostpoolTemplate.json](https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/CreateAndProvisionHostPool/CreateHostpoolTemplate.json) or  [AddVirtualMachinesTemplate.json](https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/AddVirtualMachinesToHostPool/AddVirtualMachinesTemplate.json)?

> After using the latest code from the master, I am able to create the session hosts. But the session host VM seems to be unavailable
you should check the deployment history in the corresponding resource group and find our the error details.

> I didn't try to redeploy or add more but I guess it's due to the version of the agent running inside. I will try to redeploy and also to re-install the agent and will keep you posted.
All existing session hosts in existing host pool should still work as usual.  Would you please tell me why do you need to re-install the agent?  Would you please share what the steps are you doing?

Thank you!

**Comment by dhrump** [comment]
Please reopen if you are still hitting the issue
