### ISSUE TITLE
Error on wvd-scaling-script

### ISSUE THREAD

**Issue by Enterplay** [Azure/RDS-Templates#616]
Hello,
Fist of all I want to congrat you for the great piece of code!
I followed the steps described in: https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script and everything was fine during the creation of the azure resources.
When the runbook runs the script, I´m getting this warning:

"2021-04-09 08:15:35 [548] Sum of user sessions reported by every running session host (0) is not equal to the total number of user sessions reported by the host pool (8) "

and this error:

"Exception : System.Management.Automation.RuntimeException: There are 6/6 session hosts whose VM instance was not found in Azure TargetObject : There are 6/6 session hosts whose VM instance was not found in Azure CategoryInfo : OperationStopped: (There are 6/6 s... found in Azure:String) [], RuntimeException FullyQualifiedErrorId : There are 6/6 session hosts whose VM instance was not found in Azure ErrorDetails : InvocationInfo : System.Management.Automation.InvocationInfo ScriptStackTrace : at <ScriptBlock>, <No file>: line 560 PipelineIterationInfo : {} PSMessageDetails : Version: 0.1.38 ( Exception : System.Management.Automation.RuntimeException: There are 6/6 session hosts whose VM instance was not found in Azure TargetObject : There are 6/6 session hosts whose VM instance was not found in Azure CategoryInfo : OperationStopped: (There are 6/6 s... found in Azure:String) [], RuntimeException FullyQualifiedErrorId : There are 6/6 session hosts whose VM instance was not found in Azure ErrorDetails : InvocationInfo : System.Management.Automation.InvocationInfo ScriptStackTrace : at <ScriptBlock>, <No file>: line 560 PipelineIterationInfo : {} PSMessageDetails : Version: 0.1.38 (There are 6/6 session hosts whose VM instance was not found in Azure))"

The script fails!
Any clue?

Kind regards.
Fabio

**Comment by nakranimohit0** [comment]
The warning is a result of the error "VM instance was not found". This can be due to number of reasons but basically the script is not able to find the VM instances on Azure for the corresponding session hosts. The command that script uses to get VM instances is "Get-AzVM -Status". Also make sure that the session host name starts with the VM name because thats how the script determines which VM instance is associated with each session host. Another reason could be that the default run as account (service principal) that the script uses to authenticate with Azure doesn't have access or proper permissions to get VMs

**Comment by nakranimohit0** [comment]
@Enterplay ^^

**Comment by Enterplay** [comment]
Hello @nakranimohit0,
Hope you are fine. 
Thank you to point me in the right direction. I verified that my VM names did not match the names of the sessions, so I changed some things in the script and now everything works like a charm!!
Again, tks!!!!
Best regards,

@Enterplay

**Comment by garcimbo** [comment]
Hi there,

Thanks for the script.

I'm having the same issue,  but I don't understand what the problem is, how are the VM names expected to be? should the VM names have some prefix?

**Comment by Enterplay** [comment]
> Hi there,
> 
> Thanks for the script.
> 
> I'm having the same issue, but I don't understand what the problem is, how are the VM names expected to be? should the VM names have some prefix?

Yes, the Azure VM name must be the same as windows computer name.

**Comment by garcimbo** [comment]
> 
> 
> > Hi there,
> > Thanks for the script.
> > I'm having the same issue, but I don't understand what the problem is, how are the VM names expected to be? should the VM names have some prefix?
> 
> Yes, the Azure VM name must be the same as windows computer name.

Thanks @Enterplay, now the script is running without errors.
