### ISSUE TITLE
WVD Deployment has lost its host pool

### ISSUE THREAD

**Issue by chi-ltd** [Azure/RDS-Templates#618]
Hi
We deployed WVD some time ago (i think using the ARM template not classic) and possibly just before it went GA, or just after (according to my notes Dec 2019) and i now seem to not have a host pool available and cannot log into the VMs from RDApp or browser.

MS Azure support have suggested building a new environment as it was built in classic however the WVD tenant is showing the host pool as created through ARM template..  I assume a host pool can be created.  I've followed https://docs.microsoft.com/en-us/azure/virtual-desktop/create-host-pools-azure-marketplace but i only see West & North Europe and not UK South which is where we deployed WVD.

Any suggestions here?
Thanks

**Comment by dhrump** [comment]
@chi-ltd we were wondering if you are using ARM template from github or downloading ARM from portal after creating hostpool.
In either case currently hostpool creation is only supported in Locations listed below in the image. So sounds like creation is working in West & North Europe, but not in UK South since it is not supported Location. Link to https://docs.microsoft.com/en-us/azure/virtual-desktop/data-locations for WVD supported data locations.

![image](https://user-images.githubusercontent.com/54289398/115073396-23145d00-9ead-11eb-9df1-6e09cbb5d678.png)

Moreover VMs can be created in any location regardless of the host pool region. E.g. You can create the host pool in North Europe and the VMs in UK South

Please let us know if you have further questions

Thanks

**Comment by chi-ltd** [comment]
Hi
I was using the template from within Azure.  In this case I searched for Windows virtual desktop under the market place and picked 'Windows Virtual Desktop - Provision a host pool'.
The Windows virtual Desktop service didn't allow me to pick UK South when created the host pool.

Should i be using the (what appears to be newer) version of WVD within azure portal?  Currently with my newly provisioned WVD hostpool i can connect fine to the 4x WVD instances, however i cannot see any of the host pools, application groups, workspaces or users under the WVD service.

Thanks

**Comment by lintFan** [comment]
@chi-ltd Yes you will need to use the "Windows Virtual Desktop" listed under "Services" in the portal, as [described here ](https://docs.microsoft.com/en-us/azure/virtual-desktop/create-host-pools-azure-marketplace#begin-the-host-pool-setup-process), if you want to create a hostpool and session hosts using the non-classic WVD. 

The[ "Windows Virtual Desktop - Provision a host pool" in the marketplace](https://portal.azure.com/#create/rds.wvd-provision-host-poolpreview) is for WVD classic as [documented here](https://docs.microsoft.com/en-us/azure/virtual-desktop/virtual-desktop-fall-2019/create-host-pools-azure-marketplace-2019).

**Comment by chi-ltd** [comment]
Thanks for confirming.  I see the main difference between the two deployment modes is WVD required firewall, the classic (older version) does not.
If i deploy the azure firewall within the same vnet and RG as other resources in production, but apply a separate subnet for WVD, will the firewall control all resources in the vnet or just the items within the subnet?
Thanks

**Comment by lintFan** [comment]
@chi-ltd It is possible to deploy the non-classic WVD without a firewall. I don't know the answer to your question about the firewall but I see in the portal when you are creating a host pool in the "Virtual Machines" tab it says "Use Azure Firewall to secure your VNET and host pool resources. [Learn more](https://docs.microsoft.com/azure/firewall/protect-windows-virtual-desktop?WT.mc_id=Portal-Microsoft_Azure_WVD) " but if that article doesn't answer your question you can create a support request by going to https://azure.microsoft.com/support/create-ticket/ and then then selecting Windows Virtual Desktop for the service.

**Comment by chi-ltd** [comment]
Thanks
