### ISSUE TITLE
add aadjoin support for arm templates of hostpool and session hosts

### ISSUE THREAD

**Issue by abhilash-keloth** [Azure/RDS-Templates#619]
I understand that currently aadjoin is not supported in below templates. Does that means on-premise AD still can be used without azure AD ? Could you please let me know the timeline if any ?

https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/AddVirtualMachinesToHostPool/AddVirtualMachinesTemplate.json

https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/CreateAndProvisionHostPool/CreateHostpoolTemplate.json

**Comment by philipktlin** [comment]
yes. on-premise AD is still supported.  For AADJ timeline, will get back to you soon.

**Comment by abhilash-keloth** [comment]
Thanks @philipktlin. Please keep me posted on AADJ timeline.

**Comment by philipktlin** [comment]
FYI we haven't finalize the timeline for AADJ.  Will update once the timeline is settled.

**Comment by dhrump** [comment]
AADJ support is now checked in
