### ISSUE TITLE
Routing WVD outbound connections though VPN rather than directly out to the web?

### ISSUE THREAD

**Issue by chi-ltd** [Azure/RDS-Templates#620]
Hi 
Is the above possible?
Thanks

**Comment by sefriend** [comment]
Hi @chi-ltd, Private Link will solve this and we are currently investigating that with WVD.

**Comment by chi-ltd** [comment]
Sorry, please confirm?

**Comment by sefriend** [comment]
WVD is currently looking into private link which will accomplish what you are asking. You can read more about it here: https://docs.microsoft.com/en-us/azure/private-link/private-link-overview. Currently there is no way to do what you are asking.
