### ISSUE TITLE
Custom image ARM templates validation failed using DevOps

### ISSUE THREAD

**Issue by rkreddy03** [Azure/RDS-Templates#626]
Custom image ARM validation failed using DevOps.

We are deploying WVD infrastructure using Azure Devops pipeline but validation got  failed While choosing custom image and getting the following error:
imagerefernece.publisher is invalid

>

**Comment by rkreddy03** [comment]
Getting below error while doing validation of ARM templated by selecting Custom Image ID 


The template deployment 'arm-wvd-AddVirtualMachinesTemplate-20210531-020410-43fd' is not valid according to the validation procedure. The tracking id is 'a20ee3e0-239a-47d3-b0b0-e0d6c5d29b78'. See inner errors for details.
Details:
InvalidParameter: Resource 'HPi1win10vm-1' has invalid parameters. Details: The value of parameter imageReference.publisher is invalid.
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
Details:
DeploymentFailed: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
Task failed while creating or updating the template deployment

**Comment by rkreddy03** [comment]
Current ARM template doesn't include Shared image gallery

**Comment by lintFan** [comment]
@rkreddy03  Hi, which ARM template are you using to deploy WVD? The WVD ARM based ARM templates are here https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates and the WVD classic (non-ARM based) are here https://github.com/Azure/RDS-Templates/tree/master/wvd-templates

**Comment by rkreddy03** [comment]
I am using https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates. Validation failed when using custom image from Azure Devops. 
Addition of SIG nested template for shared image gallery

**Comment by lintFan** [comment]
@rkreddy03 are you using https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/CreateAndProvisionHostPool or https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/AddVirtualMachinesToHostPool ?

**Comment by rkreddy03** [comment]
Using  https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/AddVirtualMachinesToHostPool 

Add Virtual machines to Hostpool

**Comment by dhrump** [comment]
@rkreddy03 for custom image we are not suppose to give any value for the publisher. I would like to see what all values you are providing to your ARM template parameters and is it possible to share custom image with us so we can troubleshoot issue on our side. Thanks

**Comment by dhrump** [comment]
Please reopen if you are still facing the issue
