### ISSUE TITLE
issue of CreateOrUpdateAzAutoAccount.ps1

### ISSUE THREAD

**Issue by situzhiheng** [Azure/RDS-Templates#631]
I followed the docs https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script#create-or-update-an-azure-automation-account to run the CreateOrUpdateAzAutoAccount.ps1 script, then prompt a error "No parameters were found that matched the parameter name "automationAccountName".
When I try to TS, I found the value of $ArtifactsURI is invalid in CreateOrUpdateAzAutoAccount.ps1. Would you kindly help to double check and update? thks.

**Comment by nakranimohit0** [comment]
@situzhiheng I'm unable to reproduce this issue. Please share more info about your PowerShell environment such as this https://github.com/Azure/RDS-Templates/issues/627#issuecomment-887022868

**Comment by nakranimohit0** [comment]
@situzhiheng This seems related to a known issue with Az module https://github.com/Azure/azure-powershell/issues/15841
Workaround is to use Az v6.3.0

**Comment by nakranimohit0** [comment]
Closing due to no response. Please reopen if it occurs again.
