### ISSUE TITLE
4-WVD-scaling-tool - error getting webhook url

### ISSUE THREAD

**Issue by obsjmartin** [Azure/RDS-Templates#635]
The issue here is the same as described in issue 614 - https://github.com/Azure/RDS-Templates/issues/614
Following the documentation at https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script
I have powershell v7 loaded and the output error  #is:

> `PS C:\temp> .\CreateOrUpdateAzAutoAccount.ps1 @Params

VERBOSE: Performing the operation "Creating Deployment" on target "OpalAVD".
VERBOSE: 2:30:08 PM - Template is valid.
VERBOSE: 2:30:09 PM - Create template deployment 'runbookCreationTemplate'
VERBOSE: 2:30:09 PM - Checking deployment status in 5 seconds
VERBOSE: 2:30:14 PM - Resource Microsoft.Automation/automationAccounts/runbooks 'AVDAutoScaleAutomationAccount/WVDAutoScaleRunbookARMBased' provisioning status is succeeded
VERBOSE: 2:30:14 PM - Resource Microsoft.Automation/automationAccounts 'AVDAutoScaleAutomationAccount' provisioning status is succeeded
VERBOSE: Performing the operation "For security purposes, the URL of the created webhook will only be viewable in the output of this command. No other commands will return the webhook URL. Make sure to copy down the webhook URL from this command's output before closing your PowerShell session, and to store it securely." on target "WVDAutoScaleWebhookARMBased".
Automation Account Webhook is created with name 'WVDAutoScaleWebhookARMBased'

> New-AzAutomationVariable: C:\temp\CreateOrUpdateAzAutoAccount.ps1:233

Line |
 233 |      New-AzAutomationVariable -Name $WebhookURIAutoVarName -Encrypted  …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"Message":"The request is invalid.","ModelState":{"variable.properties.value":["Invalid JSON
     | primitive: https."]}}` #

**Comment by obsjmartin** [comment]
Update: After installing powershell v7 AND updating the az modules, this worked. 
Use `Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber` to update az powershell module.

**Comment by nakranimohit0** [comment]
@obsjmartin I'm unable to reproduce this issue. Please share more info about your PowerShell environment such as https://github.com/Azure/RDS-Templates/issues/627#issuecomment-887022868
