### ISSUE TITLE
Need to update 'aadjoin' due to GAed.

### ISSUE THREAD

**Issue by Naotaka-Kawakami-MSFT** [Azure/RDS-Templates#650]
There is the description below but AADJ for AVD is now GA. Hence URL's need to be updated in the Github templates here:

https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/nestedtemplates/managedDisks-galleryvm.json
"IMPORTANT: You can use this parameter for the test purpose only as AAD Join is public preview. True if AAD Join, false if AD join"

**Comment by dhrump** [comment]
Fix is checked in. Thanks
