### ISSUE TITLE
System.InvalidOperationException: This command cannot be run due to the error: Access is denied.

### ISSUE THREAD

**Issue by rjnls** [Azure/RDS-Templates#652]
This seems to have just started happening to us from within Script-AddRdshServer.ps1. Any advice would be much appreciated thx!

2021-10-13T15:12:40.0041501Z ##[error]VMExtensionProvisioningError: VM has reported a failure when processing extension 'dscextension'. Error message: "DSC Configuration 'AddSessionHost' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: Some error occurred in DSC ExecuteRdAgentInstallClient SetScript: 

Exception             : System.InvalidOperationException: This command cannot be run due to the error: Access is denied.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord 
                        errorRecord)
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at RunMsiWithRetry, C:\Packages\Plugins\Microsoft.Powershell.DSC\2.83.2.0\DSCWork\Configuration_
                        7-20-2020.0\Functions.ps1: line 387
                        at InstallRDAgents, C:\Packages\Plugins\Microsoft.Powershell.DSC\2.83.2.0\DSCWork\Configuration_
                        7-20-2020.0\Functions.ps1: line 447
                        at <ScriptBlock>, C:\Packages\Plugins\Microsoft.Powershell.DSC\2.83.2.0\DSCWork\Configuration_7-
                        20-2020.0\Script-AddRdshServer.ps1: line 55
                        at <ScriptBlock>, <No file>: line 11
                        at ScriptExecutionHelper, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfi
                        guration\DscResources\MSFT_ScriptResource\MSFT_ScriptResource.psm1: line 317
                        at Set-TargetResource, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfigur
                        ation\DscResources\MSFT_ScriptResource\MSFT_ScriptResource.psm1: line 153
PipelineIterationInfo : {}
PSMessageDetails      : 

  The SendConfigurationApply function did not succeed."

**Comment by lintFan** [comment]
@rjnls Hi, Which ARM template are you running?

This line in that error message Functions.ps1: line 387  should refer to this [line 387 in Functions.ps1](https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/DSC/Functions.ps1#L387)
`        $processResult = Start-Process -FilePath "msiexec.exe" -ArgumentList $argumentList -Wait -Passthru
`
which is trying to run msiexec.exe to either uninstall or install the Azure Virtual Desktop Agent or Azure Virtual Desktop Agent Bootloader MSI. Maybe check if any permissions have changed recently on the VM?

I suggest checking if any of these files exist on that VM as they would have logs from msiexec.exe :
C:\Users\AgentUninstall.txt
C:\Users\AgentBootLoaderUnInstall.txt
C:\Users\AgentInstall.txt
C:\Users\AgentBootLoaderInstall.txt
but if that access denied was on starting msiexec.exe then they won't exist.

You can also get the path to the log file that has information for the powershell commands run the dscextension extension in this ARM template using this powershell command:
"$([environment]::GetEnvironmentVariable('TEMP', 'Machine'))\ScriptLog.log"
I suggest checking that to see if it has any additional information.

**Comment by lintFan** [comment]
I was wondering if you were running the ARM template  [AddVirtualMachinesTemplate.json](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/AddVirtualMachinesToHostPool)  or  [CreateHostpoolTemplate.json](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/CreateAndProvisionHostPool).

The Configuration_7-20-2020.zip you linked to is using an older version of [Functions.ps1](https://github.com/Azure/RDS-Templates/blob/f1cbff9ee19e2aa64e152915816224bd81ba12a8/wvd-templates/DSC/Functions.ps1) and based on your error message I can tell that it is failing when it is running a powershell command that should look like this:
`$processResult = Start-Process -FilePath "msiexec.exe" -ArgumentList  @("/x {A38EE409-424D-4A0D-B5B6-5D66F20F62A5}", "/quiet", "/qn", "/norestart", "/passive", "/l* C:\Users\AgentBootLoaderUnInstall.txt") -Wait -Passthru`
which is trying to uninstall an older version of the Azure Virtual Desktop Agent Bootloader MSI if it exists.
