### ISSUE TITLE
Scaling Automation fails in Azure Gov; API version "2021-07-12" does not exist

### ISSUE THREAD

**Issue by jamasten** [Azure/RDS-Templates#660]
The Scaling Automation solution deploys the latest modules to Automation Account.  Version 3.1.0 of the Az.DesktopVirtualization module uses API version "2021-07-12".  This API version is not supported in Azure US Gov.  The "CreateOrUpdateAzAutoAccount.ps1" file should be updated to use version 3.0.0 for the Az.DesktopVirtualization module until there is feature parity is Azure US Gov.  Error included below: 

Exception : System.Exception: Failed to get Hostpool info of 'hp-avd0deu' in resource group 'rg-avd0deu-infra'. Ensure that you have entered the correct values ---> System.Exception: [NoRegisteredProviderFound] : No registered resource provider found for location 'usgovvirginia' and API version '2021-07-12' for type 'hostpools'. The supported api-versions are '2019-01-23-preview, 2019-09-24-preview, 2019-12-10-preview, 2020-09-21-preview, 2020-10-19-preview, 2020-11-02-preview, 2020-11-10-preview, 2021-01-14-preview, 2021-02-01-preview, 2021-03-09-preview'. The supported locations are 'usgovarizona, usgovvirginia'. --- End of inner exception stack trace --- TargetObject : CategoryInfo : OperationStopped: (:) [], Exception FullyQualifiedErrorId : Failed to get Hostpool info of 'hp-avd0deu' in resource group 'rg-avd0deu-infra'. Ensure that you have entered the correct values ErrorDetails : InvocationInfo : System.Management.Automation.InvocationInfo ScriptStackTrace : at <ScriptBlock>, <No file>: line 406 PipelineIterationInfo : {} PSMessageDetails : Version: 0.1.38 ( Exception : System.Exception: Failed to get Hostpool info of 'hp-avd0deu' in resource group 'rg-avd0deu-infra'. Ensure that you have entered the correct values ---> System.Exception: [NoRegisteredProviderFound] : No registered resource provider found for location 'usgovvirginia' and API version '2021-07-12' for type 'hostpools'. The supported api-versions are '2019-01-23-preview, 2019-09-24-preview, 2019-12-10-preview, 2020-09-21-preview, 2020-10-19-preview, 2020-11-02-preview, 2020-11-10-preview, 2021-01-14-preview, 2021-02-01-preview, 2021-03-09-preview'. The supported locations are 'usgovarizona, usgovvirginia'. --- End of inner exception stack trace --- TargetObject : CategoryInfo : OperationStopped: (:) [], Exception FullyQualifiedErrorId : Failed to get Hostpool info of 'hp-avd0deu' in resource group 'rg-avd0deu-infra'. Ensure that you have entered the correct values ErrorDetails : InvocationInfo : System.Management.Automation.InvocationInfo ScriptStackTrace : at <ScriptBlock>, <No file>: line 406 PipelineIterationInfo : {} PSMessageDetails : Version: 0.1.38 (Failed to get Hostpool info of 'hp-avd0deu' in resource group 'rg-avd0deu-infra'. Ensure that you have entered the correct values ([NoRegisteredProviderFound] : No registered resource provider found for location 'usgovvirginia' and API version '2021-07-12' for type 'hostpools'. The supported api-versions are '2019-01-23-preview, 2019-09-24-preview, 2019-12-10-preview, 2020-09-21-preview, 2020-10-19-preview, 2020-11-02-preview, 2020-11-10-preview, 2021-01-14-preview, 2021-02-01-preview, 2021-03-09-preview'. The supported locations are 'usgovarizona, usgovvirginia'.)))

**Comment by nakranimohit0** [comment]
@jamasten thanks for bringing this up. We have logged a bug internally to track the work.

**Comment by jamasten** [comment]
This issue has resolved itself.  I'm not sure if a new version of AVD was released or what, but I no longer need to downgrade the AZ module anymore.

**Comment by nakranimohit0** [comment]
@jamasten thanks for updating. Good to know.
