### ISSUE TITLE
No canonical location for the DSC configuration file

### ISSUE THREAD

**Issue by MarkWilsonDLG** [Azure/RDS-Templates#674]
If you look in the portal when manually deploying new hosts then the ARM templates reference this DSC config:-

https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_02-23-2022.zip

You can see all the files here:- 

https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts?restype=container&comp=list

However it would appear a copy of this is also maintained here:- 

https://raw.githubusercontent.com/Azure/RDS-Templates/master/ARM-wvd-templates/DSC/Configuration.zip

albeit not quite as up-to-date as what is on the share.

How am I supposed to know which one to use? It seems to get updated quite often.

**Comment by philipktlin** [comment]
We recommended to use https://raw.githubusercontent.com/Azure/RDS-Templates/master/ARM-wvd-templates/DSC/Configuration.zip in this repo for 3rd party integration.

Confiugration zip file in this repo should always be updated to the latest version of configuration.zip used in Azure Portal (in general, no later than 2 weeks).  It is tested and verified with basic scenarios (e.g. host pool creation with session hosts).  It is recommended to have a copy of configuration zip to use in your system; and test the updated version before use in your production system.

tested and verified
recommended to make a copy

**Comment by lintFan** [comment]
@MarkWilsonDLG The https://raw.githubusercontent.com/Azure/RDS-Templates/master/ARM-wvd-templates/DSC/Configuration.zip is versioned with the other files in https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates ; so a version of Configuration.zip is only guaranteed to work with the files in https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates from that same commit version. 

For example if you are using the templates in this commit https://github.com/Azure/RDS-Templates/tree/34911ed52119bcee47534eb4d0d71c80529279c7/ARM-wvd-templates then you could reference the Configuration.zip from that same commit like https://raw.githubusercontent.com/Azure/RDS-Templates/34911ed52119bcee47534eb4d0d71c80529279c7/ARM-wvd-templates/DSC/Configuration.zip .

In practice breaking changes in Configuration.zip are pretty rare but it is possible.

**Comment by MarkWilsonDLG** [comment]
We are using our own ARM templates for host creation, adding a host to a host pool is a discrete operation using DSC but we just need to be able to consistently have a correct DSC config. It sounds like the one in Github is the way to go.

@lintFan I don't understand how there would be a connection between the ARM templates to create a VM and the subsequent adding of that VM to a host pool? When I search through the templates and sub-templates there doesn't appear to be anything AVD specific?
