### ISSUE TITLE
4-WVD-Scaling-Tool Get-AzAutomationVariable can no longer retrieve values of encrypted variables

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/RDS-Templates#682]
I don't know in which release of the Az modules this changed, but I had leveraged the scripts from this repo to build my own single script to deploy the scaling tool.

Previously, `Get-AzAutomationVariable` would correctly retrieve the value of the WebhookURI variable, but it no longer does. It must be related to either a change in the PS modules or a change to these scripts that marked the variable as Encrypted where it previously didn't.

I don't know a solution to the problem. For me, the Webhook URI is shown on the screen after running the `CreateOrUpdateAzAutoAccount.ps1` script in one place instead of two. But it's problematic for a downstream script that needs that URI.

Perhaps the script can return the value using `return $WebhookURI` as the last line?

**Comment by SvenAelterman** [comment]
I just realize that the cause is in fact that the script now treats the variable as Encrypted: https://github.com/Azure/RDS-Templates/pull/670

This was a breaking change unfortunately.

**Comment by nakranimohit0** [comment]
@SvenAelterman Thanks for bringing this up. Yes, this is a breaking change and documentation was updated to address this: https://aka.ms/wvdscale. It was an Azure Security Center that advised to make the variable value encrypted for security reasons.
