### ISSUE TITLE
creating a new session host using CreateAndProvisionHostPool template is trying to delete NSG 

### ISSUE THREAD

**Issue by luisnjuarez** [Azure/RDS-Templates#695]
Hi There,

has anyone had experiencing the following error?

Operation Name: Delete Network Security Group - Failed
Error code: InUseNetworkSecurityGroupCannotBeDeleted

Basically, anytime I am creating a new session host is trying to delete an existing NSG
My first concern is why it is even trying to delete this NSG and how to avoid this. We dont want to have this NSG delete, which is a bit concerning

The network architecture is as follows

- Core VNET with subnets, each subnet is using the same NSG
- In the json template, I am passing the params of the NSG Resource ID, the vnet and the subnet.

The deployment operation takes 1 hour and 20 mins approx and it fails every time. I can't find any more details, This is the only error it shows repepetively, trying to delete the NSG multiple times

I wonder if there is anyone that has experienced this behaviour. It is very similar to this issue
https://stackoverflow.com/questions/59573551/azure-terraform-network-security-group-getting-deleted

Any help is greatly appreciated. Please let me know if there is anything else I can add to this post that might be helpful to find the issue

**Comment by lintFan** [comment]
@luisnjuarez Hi, is this the ARM template you are using https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/CreateAndProvisionHostPool ?

**Comment by luisnjuarez** [comment]
I am sorry, the issue is not related to the template, it is with the deployment mode, that by mistake I was using completed. I will close this issue as it was never an issue

**Comment by lintFan** [comment]
Thanks for the follow up.
