### ISSUE TITLE
Deployment template validation failed: 'The template parameters 'vmImageVhdUri, storageAccountResourceGroupName' in the parameters file are not valid;

### ISSUE THREAD

**Issue by Atul-183** [Azure/RDS-Templates#713]
We were using a template to deploy our VDI in Azure, for 2 years it was working fine but all of a sudden we start getting this error and all our deployment are getting failed. The error message we get --

{
    "status": "Failed",
    "error": {
        "code": "InvalidTemplate",
        "message": "Deployment template validation failed: 'The template parameters 'vmImageVhdUri, storageAccountResourceGroupName' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'artifactsLocation, availabilityOption, availabilitySetName, availabilityZones, vmGalleryImageOffer, vmGalleryImagePublisher, vmGalleryImageHasPlan, vmGalleryImageSKU, vmGalleryImageVersion, rdshPrefix, rdshNumberOfInstances, rdshVMDiskType, rdshVmSize, rdshVmDiskSizeGB, rdshHibernate, enableAcceleratedNetworking, administratorAccountUsername, administratorAccountPassword, vmAdministratorAccountUsername, vmAdministratorAccountPassword, vhds, subnet-id, rdshImageSourceId, location, createNetworkSecurityGroup, networkSecurityGroupId, networkSecurityGroupRules, networkInterfaceTags, networkSecurityGroupTags, virtualMachineTags, imageTags, vmInitialNumber, _guidValue, hostpoolToken, hostpoolName, ouPath, domain, aadJoin, intune, bootDiagnostics, userAssignedIdentity, customConfigurationTemplateUrl, customConfigurationParameterUrl, SessionHostConfigurationVersion, systemData, securityType, secureBoot, vTPM'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.",
        "additionalInfo": [
            {
                "type": "TemplateViolation",
                "info": {
                    "lineNumber": 0,
                    "linePosition": 0,
                    "path": ""
                }
            }
        ]
    }
}

We tested by deploying the VDI directly through Azure portal and it got deployed but getting failed with template. Please let me know if anyone have some solution for this or require any additional information.

**Comment by philipktlin** [comment]
Sorry to hear about this problem. Custom image in blob storage is not the recommended from Azure, therefore we decided not to support in AVD ARM template anymore.  AFAIK, we posted message in community to communicate about this change few weeks ago.

To solve this problem, there are 2 options.
1. you can use the old version of ARM templates in history, e.g. https://github.com/Azure/RDS-Templates/blob/da5d6a53874cbc37ed749ed9a283f698272ffb8a/ARM-wvd-templates/nestedtemplates/managedDisks-galleryvm.json
2. you should use Azure Compute Gallery and create a new image there.  You can get more information from https://learn.microsoft.com/en-us/azure/virtual-machines/azure-compute-gallery and you can follow https://learn.microsoft.com/en-us/azure/virtual-machines/capture-image-portal to create an image in Azure Compute Gallery. Then you can use "CustomImage" for vmImageType; and specify value for vmCustomImageSourceId in ARM template.

Please feel free to re-open if you have any questions. thanks.

**Comment by lintFan** [comment]
If you want to continue using the older version of the ARM template you have been using then I believe you should be able to fix the error you are getting by passing in the following value for the "nestedTemplatesLocation" parameter 
"https://raw.githubusercontent.com/Azure/RDS-Templates/d722d8635665f8c2aadfbb79e2b4c732da9d8373/ARM-wvd-templates/nestedtemplates/"
this will make the ARM template use older versions of the [nestedTemplates](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/nestedtemplates) files that are used internally by the ARM template that are compatible with older versions of the [AddVirtualMachinesTemplate.json](https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/AddVirtualMachinesToHostPool/AddVirtualMachinesTemplate.json) or 
[CreateHostpoolTemplate.json](https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/CreateAndProvisionHostPool/CreateHostpoolTemplate.json) templates.

FYI I got that nestedTemplatesLocation value by browsing to an older version of one of the [nestedTemplates](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/nestedtemplates) files like [this](https://github.com/Azure/RDS-Templates/blob/d722d8635665f8c2aadfbb79e2b4c732da9d8373/ARM-wvd-templates/nestedtemplates/managedDisks-galleryvm.json) and then clicking the "Raw" button and then removing the filename from the URL.

**Comment by schrx1964** [comment]
I think i am missing some knowledge here. I have the same problem since last week and indeed changing the parameter works, but i prefer to go to a newer ARM template. I do NOT use blob storage hence the value of vmImageVHDUri is empty. How do i get a new template without this property? The last new one i find on github the property still exist. If i delete the property I get an error that the parameter is missing. Can someone please explain?
