### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by quasilyte** [Azure/RDS-Templates#77]
This repository misses the license file.
The severity of that varies from project to project, but my goal here is to attract some attention.

If it's not a problem, this issue can be closed.

I'm leaving it here just in case: https://help.github.com/articles/adding-a-license-to-a-repository/.

Thanks.

**Comment by ChristianMontoya** [comment]
@quasilyte : thank you for raising this! Yes, this repo conforms with the same MIT license as other Azure repo's. You'll see it's added now.
